<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>
<style>
#insertstring>div>div
{
	padding: 5px;
}
#insertstring>div>div>div
{
	padding: 5px;
}
#insertstring label
{
	width:70px;
	float:left;
}
#insertstring input#group_id
{
	width:20px;	
}
#insertstring>div>div>div>select
{
	width:150px;
}
#insertstring>div>div>div>input#button
{
	margin-left:60px;
}
</style>
<form id="insertstring" class="myform" action="" name="string" method="post">
<div id="box">
<h3>Edit Language</h3>
	<div id='body'>
		<div>
			<label for="street">Key : </label>
			<input readonly="readonly" id="id" type="text" tabindex="1" value="<?php echo $this->key?>" name="key">
		</div>
		<div>
			<label for="street">Group: </label>
			<input readonly="readonly" id="group_name" type="text" tabindex="1" value="<?php echo $this->group_name?>" name="group_name">								
		</div>		
		<div>
			<label for="street"><?php echo $this->lang_default?></label>
			<textarea rows="3" cols="30" name="default"><?php echo $this->lang_default_text?></textarea>
		</div>
		<div>
			<label for="street"><?php echo $this->lang_index?></label>
			<textarea rows="3" cols="30" name="index"><?php echo $this->lang_index_text?></textarea>
		</div>		
		<?php if($this->viewtype!="dialog"){?>
			<div>
			<input id="button" type="submit" value="OK">
			<input id="button1" type="button" onclick="history.go(-1)" value="Quay lại">
			</div>
		<?php } ?>		
	</div>
</div>
</form>

