<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Chip & Zin Support</title>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl ?>/media/css/theme.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl ?>/media/css/style.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl ?>/media/css/chipzin-style.css" />
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/media/css/jquery-ui-1.8.16.custom.css" />

<script type="text/javascript" src="<?php echo $this->baseUrl ?>/media/scripts/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl ?>/media/scripts/jquery-ui-1.8.16.custom.min.js" ></script>
<script type="text/javascript" src="<?php echo $this->baseUrl ?>/media/scripts/form.js"></script>


<script>
   var StyleFile = "theme" + document.cookie.charAt(6) + ".css";
   document.writeln('<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl ?>/media/css/' + StyleFile + '">');
</script>
<!--[if IE]>
<link rel="stylesheet" type="text/css" href="css/ie-sucks.css" />
<![endif]-->
</head>

<body>
	<div id="container">
    	<div id="header">			
			<?php $this->topMenu($this) ?>			
			<?php $this->showHello($this->user, $this) ?>
      </div>
        
		<?php $this->topPanel($this->controllerName, $this) ?>      
		<div style="clear:both">	</div>
        <div id="wrapper">
            <div id="content">
				<?php echo $this->layout()->content ?>       			              
            </div>            
      </div>
        <div id="footer">
			<div id="credits">
				<img style="vertical-align: middle" width="16" height="16" src="<?php echo $this->baseUrl ?>/media/images/logo.gif"/>&nbsp;<b>P2 TEAM</b>
			</div>
		</div>
</div>
</body>
</html>
