<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>
<form id ="formPaging" name='formPaging' action="" method="post">

<div id="box">
	<h3>Download</h3>
	<table class="filter">
	</table>
	<table>	
		<tr>
			<table>
				<thead>
				<th width="40"><a href="#">STT</a></th>
				<th width="40"><a href="#">Name</a></th> 
				<th ><a href="#">Thời gian </a></th>
				<th width="80">Thao tác</th>
				</thead>
				<tr>
					<?php $this->listFile($this->data, $this->page, $this->items, $this,$this->baseUrl) ?>
				</tr>				
			</table>
		</tr>
	
	</table>
	<?php echo $this->pagingControl($this->items, $this->page, $this->totalRecord, $this) ?>
</div>
</form>
<script type="text/javascript">

function deleteres(key)
{
	
	id = $("#Id-"+key).text();
	
	if(!confirm("Bạn có muốn xóa file : \""+id+"\"  không ?")){
		return false;
	};
	$.ajax({
		type: "POST",
		url: "<?php echo $this->baseUrl.'/shop/download/delete'?> ",
		data:{
			id:id,
			
		},
		success: function(msg){
			alert("Thành công ! ");
			if(msg){	
					
				window.location.reload();
			}
			else{
				window.location.reload();		
			}			
		}
	});	
	
}

</script>

