<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>
<div id="box">
	<h3 id="adduser">Đổi mật khẩu</h3>
	<form id="form" action="" method="post">	  
		<label for="currentpass">Mật khẩu hiện tại : </label> 
		<input name="oldpass" id="oldpass" type="password" tabindex="1" />
		<br />
		<label for="password">Mật khẩu mới : </label>
		<input name="newpass" id="password" type="password" tabindex="2" />		
		<br />
		<label for="pass-2">Xác nhận: </label>
		<input name="newpass2" id="pass-2" type="password" 
		tabindex="2" />
		<br />	   
	  <div align="center">
	  <input id="button1" type="submit" value="Lưu" /> 	  
	  </div>
	</form>
</div>