<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>
<style>
.choice
{
	background-color: buttonface;
}
</style>
<form id="frmLayout" class="myform" action="" method="post">
<div class="mybox">
	<h3>Layout</h3>
	<table class="filter" style="width: 80%;margin: auto;margin-bottom: 20px;margin-top: 10px";>
		<tr>
			<td>
			<a class="btn add" href="javascript:newlayoutDialog()">Add</a>
			</td>
		</tr>		
	</table>
	<table class="list" id="list_layout" style="width: 80%;margin:auto ;border: 1px solid;">	
		<thead>
			<tr>									
				<td width="40"><a href="#">ID</a></td>
				<td>Layout Name</td>							
				<td>Point</td>
				<td></td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<?php $this->listLayout($this->data, $this->page, $this->items, $this) ?>
			</tr>
		</tbody>						
	</table>
	<?php 
	if( $this->items == "")
	{
		 $this->items = 10;
	}
	?>	
	<?php echo $this->pagingControl($this->items, $this->page, $this->totalRecord, $this) ?>	
	<div align="center" style="margin: 20px;">		
	</div>
</div>
</form>

<div style='display:none'  id='edit-layout'>
<form  id="layout" name="layout" action="" method="post">
	<table>
		<tr>
			<td colspan="3">
			Tên layout :<input type="text" name="namelayout" id='namelayout'>
			</td>
		</tr>
		<tr>
			<td>1<input type="checkbox" name="point" id="0" value="0" /></td>
			<td>4<input type="checkbox" name="point" id="3" value="3" /></td>
			<td>7<input type="checkbox" name="point" id="6" value="6" /></td>
		</tr>
		<tr>
			<td>2<input type="checkbox" name="point" id="1" value="1" /></td>
			<td>5<input type="checkbox" name="point" id="4" value="4" /></td>
			<td>8<input type="checkbox" name="point" id="7" value="7" /></td>
		</tr>
		<tr>
			<td>3<input type="checkbox" name="point" id="2" value="2" /></td>
			<td>6<input type="checkbox" name="point" id="5" value="5" /></td>
			<td>9<input type="checkbox" name="point" id="8" value="8" /></td>
		</tr>
	</table>
</form>	
</div>

<div style='display:none' id='insert-layout'>
	<form  id="newlayout" name="newlayout" action="" method="post">
		<table>
			<tr>
				<td colspan="3">
				Tên layout :<input type="text" name="namelayoutnew">
				</td>
			</tr>
			<tr>
				<td>1<input type="checkbox" name="point" value="0" /></td>
				<td>4<input type="checkbox" name="point" value="3" /></td>
				<td>7<input type="checkbox" name="point" value="6" /></td>
			</tr>
			<tr>
				<td>2<input type="checkbox" name="point" value="1" /></td>
				<td>5<input type="checkbox" name="point" value="4" /></td>
				<td>8<input type="checkbox" name="point" value="7" /></td>
			</tr>
			<tr>
				<td>3<input type="checkbox" name="point" value="2" /></td>
				<td>6<input type="checkbox" name="point" value="5" /></td>
				<td>9<input type="checkbox" name="point" value="8" /></td>
			</tr>
		</table>
	</form>	
</div>

<div style='display:none' id='warming'>
<form  id="warming" name="warming" action="" method="post">
	<table>
		<tbody id = 'campaignlist'>
		</tbody>
	</table>
</form>
</div>

<script type="text/javascript">
function deleteLayout(id)
{
	if(!confirm("Bạn có muốn xóa Layout: " + id))
	{
		return;
	};
	$.ajax
	({
		type: "POST",
		url: "<?php echo $this->baseUrl.'/campaign/Layout/delete/'?> ",
		data: "ID="+ id,
		dataType: 'json',
		success: function(data)
		{			
			if(data.length == 0)
			{					
				window.location.reload();
			}
			else
			{
				$('#campaignlist').html('');
				$('#campaignlist').append('<p>Các Campain sử dụng Layout này</p>');
				$.each(data, function(key, val) 
				{
					$('#campaignlist').append('<tr><td><p>'+data[key]['Name']+'</p></td><td><p><a class="tool-16 edit" href="<?php echo $this->baseUrl?>/campaign/campaign/edit/id/'+data[key]['ID']+'"></a></p></td></tr>');
				});

				$("#warming").dialog
				({
					title: "Không xóa được",
					height: 280,
					width: 250,
					modal: true,
					buttons: 
					{
						"close": function() 
						{
							$(this).dialog("close");							
						}										
					}
				});	
			}			
		}
	});		
}

function editLayout(id,point,name)
{	
	$('input[name="namelayout"]').val(name);
	for (var i=0; i <= 8; i++)
	{
		if (point[i] == '1')
	    {
			$('input[id='+i+']').attr('checked', true);
	    }
		else
		{
			$('input[id='+i+']').attr('checked', false);
		}
	}
	$("#edit-layout").dialog
	({
		title: "Edit Layout",
		height: 250,
		width: 220,
		modal: true,
		buttons: 
		{
			"Save": function() 
			{
				var Name = $("#namelayout").val();
				var arraytemp = new Array();
				var c_value = "[";
				for (var i=0; i < document.layout.point.length; i++)
				{
					if (document.layout.point[i].checked)
				    {
						arraytemp[i] = 1;
				    }
					else
					{
						arraytemp[i] = 0;
					}
				}
				c_value += arraytemp[0]+','+arraytemp[3] +','+ arraytemp[6] + ','+ arraytemp[1] + ','+ arraytemp[4] + ','+ arraytemp[7] + ','+ arraytemp[2] + ','+ arraytemp[5] + ','+ arraytemp[8];
				c_value += "]&ID="+id+"&Name=" + Name;
				$.ajax
				({
					type: "POST",
					url: "<?php echo $this->baseUrl.'/campaign/Layout/update' ?>",
					data: "point=" + c_value,
					success: function(msg)
					{	
						if(msg == '1')
						{
							alert('Thành công');
							window.location.reload();	
						}
						else
							alert('Lỗi');							
					}
				});	
				$(this).dialog("close");					
			}									
		}
	});
	return;
}
function newlayoutDialog()
{
	$("#insert-layout").dialog
	({
		title: "New Layout",
		height: 250,
		width: 220,
		modal: true,
		buttons: 
		{
			"Save": function() 
			{
				insertLayout();
				$(this).dialog("close");							
			}										
		}
	});
}

function insertLayout()
{
	var arraytemp = new Array();
	var name = document.newlayout.namelayoutnew.value;
	c_value = "[";
	for (var i=0; i < document.newlayout.point.length; i++){
		if (document.newlayout.point[i].checked) {
			arraytemp[i] = 1;
		}else{
			arraytemp[i] = 0;
		}
	}
	c_value += arraytemp[0]+','+arraytemp[3] +','+ arraytemp[6] + ','+ arraytemp[1] + ','+ arraytemp[4] + ','+ arraytemp[7] + ','+ arraytemp[2] + ','+ arraytemp[5] + ','+ arraytemp[8];
	c_value += "]&name="+name;
	$.ajax({
		type: "POST",
		url: "<?php echo $this->baseUrl.'/campaign/Layout/insert' ?> ",
		data: "point=" + c_value,
		dataType:"json",
		success: function(msg)
		{					
			if(msg.msg == "1")
			{
				window.location.reload();
			}
			else
			{
				alert(msg.msg);
			}
		}
	});	
}

</script>
