<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>


<div id="box">
	<h3 id="adduser">Chỉnh sửa Quest</h3>
	<form id="form" action="" method="post" enctype="multipart/form-data">
	  <fieldset id="personal">
		<legend>Thông tin Quest</legend>
		<label for="id">Quest Id : </label> 
		<input name="id" value="<?php echo $this->form->QuestID ?>" id="alias" type="text" tabindex="1" />
		<br />
		<label for="name">Quest Line : </label> 
		<?php $this->selectQuestLine(1) ;?>
		<br />		
	
	  </fieldset>
	</form>
</div>