<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>

<?php //print_r($this->arrAwardItems)?>
<div  class="mybox" id="quest">
	<h3>Chỉnh sửa Quest</h3>
	<form class="quest" id="form" action="<?php echo $this->baseUrl.'/Quest/save/' ?>" method="post" enctype="multipart/form-data">
	  <fieldset id="info">
		<legend>Thông tin Quest </legend>
		<table id="quest">
			<tr>
				<td>
					<label for="QuestID">Quest ID : </label> 
					<input class="disabled" readonly name="QuestID" value="<?php echo $this->obj->QuestID ?>" id="QuestID" type="text" tabindex="1" \/></td>
				<td>
					<label for="name" >Quest Line : </label>							
					<?php $this->selectQuestLine2($this->obj->QuestLineID,$this->arrQuestLine) ;?>
				</td>
			</tr>
			<tr>
				<td>
					<label for="questname">Quest Name : </label> 
					<input name="QuestName" class="width" value="<?php echo $this->obj->QuestName?>" id="questnamestring" type="text" tabindex="1" /></td>
				<td>
					<label for="queststring">Quest String: </label> 
					<input name="QuestString" value="<?php echo $this->obj->QuestString?>" id="queststring" type="text" tabindex="1" />					
				</td>

			</tr>
			
			<tr>
				<td>
					<label for="questgroup">Quest Group: </label> 
					<input name="QuestGroup" value="<?php echo $this->obj->QuestGroup?>" id="questgroup" type="text" tabindex="1" />
				</td>
				<td>
					<label for="QuestGroupString">Q_Group String: </label> 
					<input name="QuestGroupString" value="<?php echo $this->obj->QuestGroupString?>" id="questgroupstring" type="text" tabindex="1" />
				</td>		
		
			</tr>
			
			<tr>
				<td>
					<label for="QuestDesc">Quest Desc: </label> 
					<input name="QuestDesc" value="<?php echo $this->obj->QuestDesc?>" id="questdesc" type="text" tabindex="1" />
				</td>
				<td>
					<label for="questdescString">Q_Desc String: </label> 
					<input name="QuestDescString" value="<?php echo $this->obj->QuestDescString?>" id="questdescstring" type="text" tabindex="1" />
				</td>			
			</tr>
				
			
			<tr>
				<td>
					<label>Gold: </label><input name="AwardGold" value="<?php echo $this->obj->AwardGold?>" id="awardgold" type="text" tabindex="1" /><br/>
					<label>EXP: </label><input name="AwardExp" value="<?php echo $this->obj->AwardExp?>" id="awardexp" type="text" tabindex="1" /><br/>
				</td>
				<td>
					<label for="name">Next Quest : </label> 		
					<?php $this->SelectNextQuest($this->obj->NextQuest,$this->arrQuest) ;?>
				</td>
			</tr>
			<tr>		
					<td>
					<label for="2">ITems: </label>
					<a class='ico-16 add' title='Add Item' href='javascript:addAwardItem(0)'></a>
		        	<?php $this->ListQuestAwardItems($this->arrAwardItems) ;?>
		        	<div id="addItem"></div>
					</td>
				
					<td id="list-need-quest">
					<label>Need Quest : </label><a class='ico-16 add' title="Thêm Need Quest" href="javascript:addNeedQuest(0)"></a><br/>					
					<?php $this->listNeedQuest($this->arrNeedQuest,$this->arrQuest)?>
					<div id="add-need-quest"></div>
				</td>
			</tr>
			
			<tr>				
				

			</tr>
		</table>
		<div style="margin: auto; text-align: center">
			<input id="button1" type="submit" value="Save" /> &nbsp;&nbsp; 	  
 			<input id="button1" type="button" value="Cancel	" onclick="window.location='<?php echo $this->baseUrl ?>/quest/index'" />
		
		</div>		
		</fieldset>		
		</form>
		<fieldset id="tasks">
		<legend>Task:  <a id='addItem' class='ico-16 add' title='Add Task' href='javascript:addTask(0)'></a></legend>
			<div id='list-task' style="margin-top: 10px;">	
				
			</div>
			<div style="margin: auto; text-align: center; margin-top: 10px">				  
 				<a id="save-all"  class="btn save" href="javascript:saveAll()"> Save All</a>		
			</div>		
	  	</fieldset>	
	  	
</div>
<script>
function  addAwardItem(key){	
	var count = $(".award_item").size();
	count = count;
	//alert(count);
	
	var btnDelete = "&nbsp<a class='tool-16 delete' title='Delete Item' href='javascript:deleteAwardItem("+count+")'></a>" ;
	var input = "<label></label><input name='additem[]' value='' id='' type='text' tabindex='1'/>";
	

	$("#addItem").before("<div class='award_item add_item' id='award_item_"+count+"'>" +input + btnDelete+ "</div>");
}

function  deleteAwardItem(key){		
	if($("#award_item_"+key).hasClass("add_item")){
		$("#award_item_"+key).html(""); 
		return false;
	}
	$("#award_item_"+key+" a").remove();
	$("#award_item_"+key+" label").remove();
	$("#award_item_"+key+" input").val("");
	$("#award_item_"+key).hide();

}

////////////////////////////////
function  addNeedQuest(key){	
	var id = $("#QuestID").serialize();
	var count = $(".need_quest").size() + 1;
	var btnDelete = "<a class='tool-16 delete' title='Delete Item' href='javascript:deleteNeedQuest("+count+")'></a>";
	var select = "<select id='type' name='need-quest-add[]' style='margin-bottom:5px;margin-top:5px;min-width:50px'>";
	$.ajax({
		type: "POST",
		url:"<?php echo $this->baseUrl.'/quest/listquest/'?> ",	
		data:id,		
		success: function(data){
			if(data != ""){
			
				var div = "<div class='need_quest new' id='need_quest_"+count+"'><label></label>"+ select+data+"</select>"+btnDelete+"</div>";
				$("#add-need-quest").before(div);
			}
			else
			{
				alert("Thêm  không thành công");
				
			}
			
		}
	});
	
}
function  deleteNeedQuest(key){
	//alert("asd");
	var div =  $("div#need_quest_" + key);
	if(div.hasClass("new"))
		div.html("");
	else{	
		div.hide();
		div.children("a").remove();
		div.children("select").children(".data").remove();
		
	}	
}
/////////////////////////Task/////////////////////////////////
function addTask(key){
	alert($(".form-task-51").serialize());
	count = $(".task").size();
	if(count >= 3){
		alert("Fail!!!! Limited 3 Task in a Quest");
		return false;
	}
	
	quest_id = $("#QuestID").val();
	$.ajax({
		type: "POST",
		url:"<?php echo $this->baseUrl.'/task/new/'?> ",
		data: "id=" + quest_id,	
		success: function(data){			
			if(data != ""){					
				loadTask(quest_id);
			}else{
				alert("Error");				
			}
			
		}
	});
}

function deleteTask(key){		
	task_id = $("#task-"+key+" input#TaskID").val();	
	task_name = $("#task-"+key+" input#TaskName").val();
	quest_id = $("#QuestID").val();
	div = 	$("#task-"+key);
	if(!confirm("Do you want to delelte Task: " + task_name)){
		return false;
	}		
	$.ajax({
		type: "POST",
		url:"<?php echo $this->baseUrl.'/task/delete/'?> ",
		data: "id=" + task_id,	
		success: function(data){			
			if(data != ""){					
				loadTask(quest_id);
			}else{
				alert("Error");				
			}
			
		}
	});

}
function loadTask(key){	
	$.ajax({
		type: "POST",
		url:"<?php echo $this->baseUrl.'/quest/listtask/'?> ",
		data: "id=" + key,	
		success: function(data){		
			if(data != ""){ 				
				$("#list-task").html(data);
				$(".add-target").click(function(){
					addTarget(this);
					return false;
				});
				$("input[name=target]").change(function(){
					targetChange(this);
				});
			}else{
				alert("Error");				
			}
			
		}
	});
	
}
///////////////////////////////////////
function targetChange(key){
	
	selected = ($(key).val());
	if(selected == "TargetType"){
		
	}else{
		
	}
}
function addTarget(key){
	parent = $(key).parent();	
	count = parent.children('.target-list').size();	
	input ='<input id = "target-'+count+'" class="target-list" style="margin-left: 50px;width: 153px;" type="text" name="TargetList[]" value=""> <br>'

	parent.append(input);
}
function saveAll(){	
	quest_id = $("#QuestID").val();
	$(".task").each(function (index){		
		data = $(".form-task-"+ index).serialize();
		$.ajax({
			type: "POST",
			url:"<?php echo $this->baseUrl.'/task/save/'?> ",
			data: data + "&QuestID=" + quest_id,	
			success: function(msg){		
				if(msg != ""){ 				
					alert(msg);
				}else{
					alert("Error");				
				}
				
			}
		});
	
	});
}
$(document).ready(function(){	
	loadTask(<?php echo $this->obj->QuestID?>);	
});

</script>