<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>

<?php 

foreach($this->arrTask as $key =>$val){  ?>
<div class='task' id="task-<?php echo $key;?>">
<h4><a href="#">+</a>Task <?php echo $key+1?>&nbsp&nbsp<a class='ico-16 del' title='Delete Task' href='javascript:deleteTask(<?php echo $key?>)'></a>
	
</h4>
<form  id="form" class="form-task-<?php echo $key?>" action="" method="post" enctype="multipart/form-data">
<table>
	<tr>
		<td>Task ID</td>
		<td><input type="text" id="TaskID" name="TaskID" class="disabled" readonly="readonly" class="taskid" value="<?php echo $val->TaskID?>"/></td>
		<td>Task Name</td>
		<td><input type="text" id="TaskName" name="TaskName" value="<?php echo $val->TaskName?>"/></td>
		
	</tr>
	<tr>
		<td>Task String</td>
		<td><input type="text" id="TaskString" name="TaskString" value="<?php echo $val->TaskString?>"/></td>
		<td>Action (*) </td>
		<td>
		<select id="Action" name="Action">
			
			<?php 
				foreach($this->arrAction as $row)
				{
					$str="";
					if($val->ActionID == $row->ActionID )
					{
						$str= "selected";
					}
			?>
					<option <?php echo $str;?> value="<?php echo $row->ActionID ?>"><?php echo $row->ActionName ?></option>
			<?php
				}
			?>
		</select>
		</td>
	</tr>
	<tr> 

		<td>Quantity (*) </td>
		<td><input type="text" id="Quantity" name="Quantity" value="<?php echo $val->Quantity?>"/></td>	
		
		<!-- 
		<td>
		<INPUT TYPE=RADIO NAME="TargetType" VALUE="" CHECKED> Target Type<BR>
		<INPUT TYPE=RADIO NAME="TargetType" VALUE="null"> Target List<BR>
		</td>
		--><td>UnlockCoin (*) </td>
		<td><input type="text" id="UnlockCoin" name="UnlockCoin" value="<?php echo $val->UnlockCoin?>"/></td>
	</tr>
	<tr>		
		<td rowspan=1">Target(*)</td>
		<td rowspan="1" id="target">
			<input checked type="radio" name="Target"  value="TargetType"> Type<input style="margin-left: 10px;width: 153px;" type="text" name="TargetType" value="<?php echo $val->TargetType;?>"> <br>
			<div>
			<input type="radio" name="Target" value="TargetList"> List <a class="ico-16 add add-target" href="#"></a><br>
			
			<?php
			$count = 0;
			foreach ($this->arrTaskTarget as $row)
			{
				
				if ($val->TaskID == $row->TaskID)
				{
			?>
					<input id="target-"<?php echo $count?>" class="target-list" type="text" value="<?php echo $row->TargetID?>" name="TargetList[]" style="margin-left: 50px; width: 153px;"><br>
					
			<?php 
					$count++;
				}
			}
			?>
			</div>
		</td>
		<td>Quest Task Client</td>
		<!-- ////////////////Hien Quest Task Client vao commbobox/////////////////// -->
		
		<td>
		<select id="QuestTC" name="QuestTC">
			
			<?php 
				foreach($this->arrQuestTC as $row)
				{
					$str="";
					if($val->QTC_ID == $row->QTC_ID )
					{
						$str= "selected";
					}
			?>
					<option <?php echo $str;?> value="<?php echo $row->QTC_ID ?>"><?php echo $row->QTC_Name ?></option>
			<?php
				}
			?>
		</select>
		</td>
		
		<!--   <td><input type="text" id="QTC_ID" name="QTC_ID" value="<?php echo $val->QTC_ID?>"/></td>-->
		<!-- /////////////////////////////////// -->
	</tr>
	<tr>
		
	</tr>
</table>
</form>
</div>
<?php }?>





