<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>

<?php //print_r($this->arrAwardItems)?>
<div id="box">
	<h3 id="adduser">Chỉnh sửa Quest</h3>
	<form id="form" action="" method="post" enctype="multipart/form-data">
	  <fieldset id="personal">
		<legend>Thông tin Quest</legend>
		<table>
			<tr>
				<td>
					<label for="QuestID">Quest Id : </label> 
					<input name="QuestID" value="<?php echo $this->obj->QuestID ?>" id="alias" type="text" tabindex="1" /></td>
				<td>
					<label for="name" >Quest Line : </label>							
					<?php $this->selectQuestLine2($this->obj->QuestLineID,$this->arrValue) ;?>
				</td>
			</tr>
			<tr>
				<td>
					<label for="questname">Quest Name : </label> 
					<input name="QuestName" value="<?php echo $this->obj->QuestName?>" id="questnamestring" type="text" tabindex="1" /></td>
				<td>
					<label for="queststring">Quest String: </label> 
					<input name="QuestString" value="<?php echo $this->obj->QuestString?>" id="queststring" type="text" tabindex="1" />
					
				</td>
			</tr>
			
			<tr>
				<td>
					<label for="questgroup">Quest Group: </label> 
					<input name="QuestGroup" value="<?php echo $this->obj->QuestGroup?>" id="questgroup" type="text" tabindex="1" />
				</td>
				<td>
					<label for="QuestGroupString">Q_Group String: </label> 
					<input name="QuestGroupString" value="<?php echo $this->obj->QuestGroupString?>" id="questgroupstring" type="text" tabindex="1" />
				</td>
			</tr>
			
			<tr>
				<td>
					<label for="QuestDesc">Quest Desc: </label> 
					<input name="QuestDesc" value="<?php echo $this->obj->QuestDesc?>" id="questdesc" type="text" tabindex="1" />
				</td>
				<td>
					<label for="questdescString">Q_Desc String: </label> 
					<input name="QuestDescString" value="<?php echo $this->obj->QuestDescString?>" id="questdescstring" type="text" tabindex="1" />
				</td>
			</tr>
				
			
			<tr>
				<td rowspan=2">
		<p>Award: </p>
		<label>Gold: </label><input name="AwardGold" value="<?php echo $this->obj->AwardGold?>" id="awardgold" type="text" tabindex="1" /><br/>
		<label>EXP: </label><input name="AwardExp" value="<?php echo $this->obj->AwardExp?>" id="awardexp" type="text" tabindex="1" /><br/>
		<label for="2">ITems: </label><a id='add-award_0' title='Add Item' href='javascript:addAwardItem()'><img style='vertical-align: middle' src='/vng/game-tool/sourcecode/chipzin/media/images/icons/add.png'></a>
		        <?php $this->ListQuestAwardItems($this->arrAwardItems) ;?>
		 
				</td>
				<td>
					<label for="name">Next Quest : </label> 		
					<?php $this->SelectNextQuest($this->obj->NextQuest,$this->arrQuest) ;?>
				</td>
			</tr>
			
			<tr>				
				<td>
					<label for="name">Need Quest : </label> <a title="Thêm Need Quest" href="javascript:addNeedQuest(0)"><img style="vertical-align: middle" src="/vng/game-tool/sourcecode/chipzin/media/images/icons/add.png"></a><br/>
					<div class="need_quest" id="need_quest_0"></div>
					<?php $this->listNeedQuest($this->arrNeedQuest,$this->arrQuest)?>															
					
				</td>
			</tr>
		</table>
		</fieldset>
		
		<fieldset id="personal">
		<legend>Task:  <a id='addItem0' title='Add Item' href='javascript:addTask()'><img style='vertical-align: middle' src='<?php echo $this->baseUrl .'/media/images/icons/add.png'?>'></a>	</legend>
			<div id='list-task'>				
				<div class='task' id='task-0'>						
					<div class="content"></div>			
				</div>
				
				<div class='task' id='task-1'>					
					<div class="content"></div>
				</div>
				
				<div class='task' id='task-2'>					
					<div class="content"></div>
				</div>
			</div>	
	  	</fieldset>
  		<input id="button1" type="submit" value="Save All" /> &nbsp;&nbsp; 	  
 		<input id="button1" type="button" value="Cancel	" onclick="window.location='<?php echo $this->baseUrl ?>/quest/index'" />		
		<br />	
		
	</form>
</div>
<script>
function  addAwardItem(){	

	var count = $(".awarditem").size();
	count = count + 1;
	var btnDelete = " <a class='btn-delete' title='Delete Item' href='javascript:deleteAwardItem("+count+")'>Delete</a>" ;
	var input = "<label></label><input name='awarditem[]' value='' id='' type='text' tabindex='1'/>";
	$("#add-award_0").after("<div class='awarditem' id='award_"+count+"'>"+input + btnDelete+"</div>");
}

function  addNeedQuest(key){
	$.ajax({
		type: "POST",
		url:"<?php echo $this->baseUrl.'/quest/listquest/'?> ",		
		success: function(data){
			if(data != "")
			{	
				var count = $(".need_quest").size();
				var cur = count - 1;
				count = count;	
				var html = "<div class='need_quest' id='need_quest_"+count+"'><label></label>" + data + " <a title='Delete Item' href='javascript:deleteNeedQuest("+count+")'>Delete</a></div>";	
				//alert(count);	
				//alert(html);	
				$("#need_quest_0").after(html);
			}
			else
			{
				alert("Thêm  không thành công");
				
			}
			
		}
	});
	
}

function  deleteAwardItem(key){
	$("#award_"+key).remove();	
}
/////////////////////////
function  deleteTask(key){
	$("#task-"+key+" h3").remove();
	$("#task-"+key+" .content").html("");
	arr = $(".task h3");
	
	
}

function  addTask(){
	//$("#award_"+key).remove();
	var count = $(".task h3").size();
	
	var cur = count +1;
	var btnDelete = "<a title='Delete Task' href='javascript:deleteTask("+count+")'><img style='vertical-align: middle' src='<?php echo $this->baseUrl .'/media/images/icons/delete.gif'?>'></a>"
	var btnAdd = " ";
	if(count<2){
		btnAdd = "<a title='Add Task' href='javascript:addTask()'><img style='vertical-align: middle' src='<?php echo $this->baseUrl .'/media/images/icons/add.png'?>'></a>"
	}
	$.ajax({
		type: "POST",
		url:"<?php echo $this->baseUrl.'/task/edit/'?> ",			
		success: function(data){			
			if(data != "")
			{	
				 		
				$("#task-" + count+ " .content").html(data);				
				$("#task-" + count+ " .content").before("<h3>Task "+cur+ btnAdd + btnDelete +"</h3> ");		
			}
			else
			{
				alert("Thêm  không thành công");
				
			}
			
		}
	});
	//alert(count);	
}


function  deleteNeedQuest(key){
	//alert("asd");
	$("div#need_quest_" + key).remove();
}
//////////////
function loadtask(pos,task_id){
	var btnDelete = "<a title='Delete Task' href='javascript:deleteTask("+pos+")'><img style='vertical-align: middle' src='<?php echo $this->baseUrl .'/media/images/icons/delete.gif'?>'></a>"
	var btnAdd = " ";
	if(pos < 2){
		btnAdd = "<a title='Add Task' href='javascript:addTask()'><img style='vertical-align: middle' src='<?php echo $this->baseUrl .'/media/images/icons/add.png'?>'></a>"
	}
		
	$.ajax({
		type: "POST",
		url:"<?php echo $this->baseUrl.'/task/edit/'?> ",
		data: "id=" + task_id,	
		success: function(data){			
			if(data != "")
			{	
				 		
				$("#task-" + pos+ " .content").html(data);
				num = pos +1;
				$("#task-" + pos+ " .content").before("<h3>Task "+num+ btnAdd + btnDelete+"</h3>");	
			}
			else
			{
				alert("Thêm  không thành công");
				
			}
			
		}
	});
}
$(function(){
	<?php
		if(!empty($this->arrTask)){  
			foreach ($this->arrTask as $key=>$value) {?>
				loadtask(<?php echo$key?>,<?php echo $value->TaskID?>);
			<?php }?>
		<?php }?>	
	
});
</script>