<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>
 
<?php //print_r($this->arrawardtype);?>
<div  class="mybox" id="quest">
	<h3>Thêm Quest</h3>
	<form class="quest-info" id="form" action="" method="post" enctype="multipart/form-data">
	  <fieldset id="info">
		<legend>Thông tin Quest </legend>
		<table id="quest">
			<tr>
				<td>
					<label for="QuestID">Quest ID : </label> 
					<input class="disabled" readonly name="QuestID" value="<?php echo $this->obj->QuestID ?>" id="QuestID" type="text" tabindex="1" /></td>
				<td>
					<label for="name" >Quest Line : </label>							
					<?php $this->selectQuestLine2($this->obj->QuestLineID,$this->arrQuestLine) ;?>
				</td>
			</tr>
			<tr>
				<td>
					<label for="questname">Quest Name : </label> 
					<input name="QuestName" class="width" value="<?php echo $this->obj->QuestName?>" id="questnamestring" type="text" tabindex="1" /></td>
				<td>
					<label for="queststring">Quest String: </label> 
					<input name="QuestString" value="<?php echo $this->obj->QuestString?>" id="queststring" type="text" tabindex="1" />					
				</td>

			</tr>
			
			<tr>
				<td>
					<label for="questgroup">Quest Group: </label> 
					<input name="QuestGroup" value="<?php echo $this->obj->QuestGroup?>" id="questgroup" type="text" tabindex="1" />
				</td>
				<td>
					<label for="QuestGroupString">Q_Group String: </label> 
					<input name="QuestGroupString" value="<?php echo $this->obj->QuestGroupString?>" id="questgroupstring" type="text" tabindex="1" />
				</td>		
		
			</tr>
			
			<tr>
				<td>
					<label for="QuestDesc">Quest Desc: </label> 
					<input name="QuestDesc" value="<?php echo $this->obj->QuestDesc?>" id="questdesc" type="text" tabindex="1" />
				</td>
				<td>
					<label for="questdescString">Q_Desc String: </label> 
					<input name="QuestDescString" value="<?php echo $this->obj->QuestDescString?>" id="questdescstring" type="text" tabindex="1" />
				</td>			
			</tr>
				
			
			<tr>
				<td class="q_award">
					<label>Award</label>
					<div><a class='tool-16 add' href=''></a></div>
				</td>
				<td id="list-need-quest">
					<label>Need Quest : </label>				
					<select name='NeedQuest' style='margin-bottom:5px;margin-top:5px;min-width:50px'>
						<option value=''></option>
						<?php 
						$strSelectQuest = "";
						foreach ($this->arrNeedQuest as $row)
						{
							$select = "";
							if($row->QuestID == $this->obj->NeedQuest)
							{
								$select = "selected";
							}
							$strSelectQuest .= "<option $select value='". $row->QuestID ."'>(ID:$row->QuestID) $row->QuestName</option>";
						}
						echo $strSelectQuest;
						?>
					</select>
				</td>
			</tr>
			<tr>		
					<td>
		        	<?php $this->ListQuestAwardItems($this->arrAwardItems) ;?>
		        	<div id="addItem"></div>
					</td>
					
					<td>
					<label>Temp Field: </label><input name="Temp" value="" id="Temp" type="text" tabindex="1" /><br/>
					</td>
					
			</tr>
		</table>				
		</fieldset>		
		</form>
		<div id="mybox">
			<fieldset>
				<legend>Task:  <a id='addItem' class='ico-16 add' title='Add Task' href='javascript:addTask(0)'></a></legend>
				<div id='list-task' style="margin-top: 10px;">
					<div id='task-0'></div>									
				</div>
					
		  	</fieldset>
	  	</div>
	  	<div style="margin: auto; text-align: center; margin-top: 10px;margin-bottom: 10px">				  
 				<a id="save-all"  class="btn save" href="javascript:saveAll()"> Save All</a>		
		</div>			  	
</div>

<div id='dialog'>
	<div id='ct'></div>
	<div id='ft'> </div>
</div>
<div style="display:none" id='tempAward'>
	<div>
		<select name='Awardtype[]' style='margin-bottom:5px;margin-top:5px;min-width:50px'>
		<?php foreach ($this->arrawardtype as $row)
		{
		?>
		<option value ='<?php echo $row->AwardTypeID;?>'><?php echo $row->Name;?></option>
		<?php 
		}
		?>
		</select>
		<label></label><input name='additem[]' value='' id='' type='text' tabindex='1' style='margin-bottom:5px;margin-top:5px;min-width:50px; max-width:100px;'/>
		&nbsp;<a class='tool-16 delete' title='Delete Item' href=''></a><br>
	</div>
</div>
<script>

function  addAwardItem(e)
{		
	var parent_div = $(e).parent();
	var parent_td = parent_div.parent();
	var parent_tr = parent_td.parent();
	var html=$("#tempAward").html();
	parent_td.append(html);
	parent_tr.change();
}

function deleteAwardItem(e)
{
	var parent_div = $(e).parent();
	var parent_td = parent_div.parent();
	var parent_tr = parent_td.parent();
	parent_div.remove();
	parent_tr.change();
}
///////Add A Award///////
$("table#quest").delegate("td.q_award .add", "click", function() {
	addAwardItem(this);		
	return false;		
});
///////Remove A Award///////
$("table#quest").delegate("td.q_award .delete", "click", function() {
	deleteAwardItem(this);
	return false;		
});

////////////////////////////////
function  addNeedQuest(key){	
	var id = $("#QuestID").serialize();
	var count = $(".need_quest").size() + 1;
	var btnDelete = "<a class='tool-16 delete' title='Delete Item' href='javascript:deleteNeedQuest("+count+")'></a>";
	var select = "<select id='type' name='need-quest-add[]' style='margin-bottom:5px;margin-top:5px;min-width:50px'>";
	$.ajax({
		type: "POST",
		url:"<?php echo $this->baseUrl.'/quest/listquest/'?> ",	
		data:id,		
		success: function(data){
			if(data != ""){
			
				var div = "<div class='need_quest new' id='need_quest_"+count+"'><label></label>"+ select+data+"</select>"+btnDelete+"</div>";
				$("#add-need-quest").before(div);
			}
			else
			{
				alert("Thêm  không thành công");
				
			}
			
		}
	});
	
}
function  deleteNeedQuest(key){
	//alert("asd");
	var div =  $("div#need_quest_" + key);
	if(div.hasClass("new"))
		div.html("");
	else{	
		div.hide();
		div.children("a").remove();
		div.children("select").children(".data").remove();
		
	}	
}
/////////////////////////Task/////////////////////////////////
function addTemplate(key){
	data = $("#task-div-"+key + " .task_form").serialize();
	$.ajax({
			type: "POST",
			url:"<?php echo $this->baseUrl.'/template/save/'?> ",
			data: data,		
			success: function(msg){
				if(parseInt(msg)==1)
					alert("Successfull");
			}
		});
}
function addTask(key){
	var count_div = $(".task-div").size();
	count_form = $("#list-task form").size();	
	if(count_form >= 3){
		alert("Failed!!!! Limited 3 Task in a Quest");
		return false;
	}			
	count_form = count_form + 1;
	$.ajax({
		type: "POST",
		url:"<?php echo $this->baseUrl.'/task/new/'?> ",
		data :{
				flag: count_div
		},
		success: function(data){					
			if(data != ""){
				var btnDel = "<a class='ico-16 del' title='Delete Task' href='javascript:deleteTask("+count_div+")'></a>";
				var btnAddTo = "<a class='ico-16 template' title='Add To Template' href='javascript:addTemplate("+count_div+")'>Add To Template</a>";
				var edittemp = "<a title='Edit Temp' href='<?php echo $this->baseUrl.'/template'?>'>Edit Template</a>";
				var title = "<h4> Task "+count_form+"&nbsp"+btnDel+"&nbsp&nbsp&nbsp&nbsp"+btnAddTo+edittemp+"</h4>";
				var str = "<div class='task-div' id='task-div-"+count_div+"'>"+title + data+"</div>";
				$("#task-0").before(str);
				
			}else{
				alert("Error");				
			}
			
		}
	});
}

function deleteTask(key){
	alert(key);
	task_div = $("#task-div-"+key);	
	task_div.children('h4').remove();
	task_div.children('form').remove();
}
///////////////////////////////////////
function targetChange(key){
	
	selected = ($(key).val());
	if(selected == "TargetType"){
		
	}else{
		
	}
}
function addTarget(key){
	count = $("#target-list-"+key +' .target-list').size();	
	input ='<input id = "target-'+count+'"  class="target-list" style="margin-left: 50px;width: 153px;" type="text" name="TargetList[]" value=""> <br>'
	$("#target-list-"+key).append(input);
}


function saveTask(){
	quest_id = $("#QuestID").val();

	$(".task_form").each(function(key,value){		
		var data = $(this).serialize();	
		key = key + 1;
		taskname = $(this).find("#TaskName").val();	
		$.ajax({
			type: "POST",
			url:"<?php echo $this->baseUrl.'/task/insert/'?> ",
			data: data + "&QuestID="+ quest_id,		
			success: function(msg){				
				if(parseInt(msg)==1){
					$("#dialog #ft").before("<p class='success'>Task "+ key +":Success<p>");
				}else{					
					$("#dialog #ft").before("<p class='error'>Task " + key + ":	<br>"+ msg + "</p>");					
				}		
			}
		});
	});
	
			
}
function validate(){
	flag=true;
	
	$(".task_form").each(function(key,val){
		num = key+1;
		value = $(val).find(" #TaskString").val();		
		if(value=='')
		{
			$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>TaskString không được để trống</p>");					
			flag=false;
		}		
		value = $(val).find(" #TaskName").val();
		
		value = $(val).find(" #DescID").val();
		if(value=='')
		{
			$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>DescID không được để trống</p>");	
			flag=false;
		}
		value = $(val).find(" #DescString").val();
		if(value=='')
		{
			$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>DescString không được để trống</p>");	
			flag=false;
		}
		value = $(val).find(" #QuestTC").val();
		value = $(val).find(" #UnlockCoin").val();
		if(isNaN(value))
		{
			$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>UnlockCoin phải là số</p>");					
			flag=false;
		}
		if(value=='')
		{
			$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>UnlickCoin không được để trống</p>");					
			flag=false;
		}
		value = $(val).find("#Quantity").val();
		if(isNaN(value))
		{
			$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>Quantity phải là số</p>");					
			flag=false;
		}
		if(value=='')
		{
			$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>Quantity không được để trống</p>");					
			flag=false;
		}
		value = $(val).find("#Action").val();	
		if(value=='')
		{
			$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>Hãy chọn Action</p>");					
			flag=false;
		}
		
		target = $(val).find("#target :radio:checked").val();		
		if(target == "TargetType")
		{
			targetType=$(val).find("#TargetType").val();
			if(targetType=='')
			{
				$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>TargetType không được bỏ trống</p>");					
				flag=false;
			}
			else if(isNaN(targetType))
			{
				$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>TargetType phải là số</p>");					
				flag=false;
			}
		}
		else
		{			
			targetList=$(val).find(".target-list").val();
			count = $(val).find(".target-list").size();			
			if(count==0)
			{								
					$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>TargetList chưa được tạo</p>");					
					flag=false;				
			}
			else if(targetList=='' && count!=0)
			{
				
				$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>TargetList không được bỏ trống</p>");					
				flag=false;
			}
			else if(isNaN(targetList) &&count!=0)
			{
				$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>TargetList phải là số</p>");					
				flag=false;
			}
		}		
	});
		return flag;	
}
function saveAll(){	
	quest_id = $("#QuestID").val();
	data = $(".quest-info").serialize();		
	$("#dialog #ct").html("");	
	test = validate();
	if(test==true)
	{
		$("#dialog").dialog({			
			height: 400,
			width: 350,
			modal: true,
			buttons: {
				"Continue": function() {								
					$(this).dialog("close");						
				}										
			}
		});
	}	
	else{
	$.ajax({
		type: "POST",
		url:"<?php echo $this->baseUrl.'/quest/new/'?>",
		data: data,		
		success: function(msg){				
			if(parseInt(msg)==1){	
				$("#dialog #ct").append("<p class='msg'>Add Quest Success<p>");
				saveTask();	
				//$("#dialog").dialog("open");
				$("#dialog").dialog({
					height: 300,
					width: 350,
					modal: true,
					buttons: {
						"Success": function() {								
							$(this).dialog("close");
							location.replace("<?php echo $this->baseUrl.'/quest/'?>");							
						},
						"Edit": function() {								
							$(this).dialog("close");
							location.replace("<?php echo $this->baseUrl.'/quest/edit/id/'?>"+quest_id);
							//alert(quest_id);
						},
						"New": function() {								
							$(this).dialog("close");
							location.replace("<?php echo $this->baseUrl.'/quest/new/'?>");							
						}										
					}
					});
			}else{				
				$("#dialog #ct").append("<p class='error'>Failed:<br>"+msg+"<p>");				
				$("#dialog").dialog({
					height: 300,
					width: 350,
					modal: true,
					buttons: {
						"Error": function() {								
							$(this).dialog("close");
							//location.replace("<?php echo $this->baseUrl.'/quest/'?>");							
						}
					}
					});
			}
						
								
		}
	});	
	}	
}
/////////////////////////////


//$(document).ready(function(){	
//	
//	$("#dialog").dialog({
//		autoOpen: false,
//		height: 400,
//		width: 400,
//		modal: true,
//		close: function(event, ui) {
//			
//		},
//		buttons: {
//			"Continue": function() {								
//				$(this).dialog("close");
//										
//			},
//			"Edit This Quest": function() {	
//				quest_id = $("#QuestID").val();							
//				$(this).dialog("close");
//				window.location.replace("<?php echo $this->baseUrl.'/quest/edit/id/'?>"+quest_id);				
//			},
//			"Add New Quest": function() {								
//				$(this).dialog("close");
//				location.reload();							
//			}
//		}
//	});	
//});
////////////////////////////////////Load template//////////////////////
function loadTemplate(key){
	var id = $("#Template"+key).val();
	$.ajax({
		type: "POST",		
		url:"<?php echo $this->baseUrl.'/task/loadtemplate/'?> ",
		data: "id=" + id,	
		dataType: "json",
		success: function(msg){	
			
			if(msg.TargetType==null){
				$("#task-div-" + key +" .task_form #TargetType").val("");
				$("#target-list-"+key + " .list").html("");
				$("#task-div-" + key +" .task_form #List").attr("checked", true);				
				$.each(msg.TargetList, function(key1,val){				
					count = $("#target-list-"+key +' .target-list').size();	
					input ='<input id = "target-'+count+'" class="target-list" style="margin-left: 50px;width: 153px;" type="text" name="TargetList[]" value="'+val.TargetID+'"> <br>';
					$("#target-list-"+key + " .list").append(input);
				});
			}else{								
				$("#task-div-" + key +" .task_form #TargetType").val(msg.TargetType	);
				$("#target-list-"+key + " .list").html("");
				$("#task-div-" + key +" .task_form #Type").attr("checked", true);
			}
						
			$("#task-div-" + key +" .task_form #TaskString").val(msg.TaskString);
			$("#task-div-" + key +" .task_form #TaskName").val(msg.TaskName);
			$("#task-div-" + key +" .task_form #DescID").val(msg.DescID);
			$("#task-div-" + key +" .task_form #DescString").val(msg.DescString);
			$("#task-div-" + key +" .task_form #QuestTC").val(msg.QTC_ID);
			$("#task-div-" + key +" .task_form #UnlockCoin").val(msg.UnlockCoin);
			$("#task-div-" + key +" .task_form #Quantity").val(msg.Quantity);
			$("#task-div-" + key +" .task_form #Action").val(msg.ActionID);
			$("#task-div-" + key +" .task_form #IconClassName").val(msg.IconClassName);
			$("#task-div-" + key +" .task_form #IconPackageName").val(msg.IconPackageName);
		}
	});
	
}

///////Add A Award///////
$("table#battle").delegate("td.b_award .add", "click", function() {
	addAward(this);		
	return false;		
});
///////Remove A Award///////
$("table#battle").delegate("td.b_award .delete", "click", function(){ 	
	removeAward(this);		
	return false;		
});

</script>