<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<form name="formPaging" action="" method="post">
<div id="box">
	<h3>Người dùng</h3>
	<table width="100%">
		<thead>
			<tr>
				<th width="40px"><a href="#">STT<!--<img src="<?php echo $this->baseUrl ?>/media/images/icons/arrow_down_mini.gif" width="16" height="16" align="absmiddle" />--></a></th>
				<th><a href="#">Tài khoản</a></th>
				<th><a href="#">Họ tên</a></th>	
				<th><a href="#">Nhóm</a></th>
				<th width="120px">Trạng thái</th>				
				<th width="60px">Thao tác</th>
			</tr>
		</thead>
		<?php $this->listUser($this->data, $this->page, $this->items, $this) ?>		
	</table>	
	<?php echo $this->pagingControl($this->items, $this->page, $this->totalRecord, $this) ?>
</div>
</form>
