<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>

<form id="frmSoldierEditor" class="myform" action="" method="post">
<div class="mybox">
	<h1>SOLDIER EDITOR</h1>
	<table class="filter" style="width: 80%;margin: auto;margin-bottom: 20px;margin-top: 10px";>
		<tr>
			<td>Soldier ID</td>
			<td><input style="width:110px;" type="text" name="searchID" id="searchID" class="searchbox" /></td>
			<td><input type="submit" name="search_soldier" class="btn search" id="search_soldier" value="search" /></td>
		
		</tr>		
		<tr>
			<td><label>ID</label>
				<input id="SoldierID"  name="SoldierID" readonly="readonly" type="text" style="width:30px;" />
			</td>
			<td><label>Name</label>			
				<input id="SoldierName" type="text" name="SoldierName"/>
			</td>
			<td><label>Name Server</label>
				<input name='nameSV' id="nameSV" type="text" readonly="readonly"/>
			</td>
			<td>
				<a class="btn save disabled " href="">Save</a>
				<!--  <a class="btn add disabled " href="">Add</a>-->
				<a class="btn cancel disabled " href="">Cancel</a>
			</td>
		</tr>
	</table>
	<table class="list" id="list_soldier" style="width: 80%;margin:auto ;border: 1px solid;">	
		<thead>
			<tr>									
				<td width="40"><a href="#">ID</a></td>
				<td>Soldier Name</td>
				<td>Server Name</td>							
				<td class="center" width="80">Action</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<?php $this->ListSoldier($this->data, $this->page, $this->items, $this) ?>
			</tr>
		</tbody>						
	</table>	
	
	<div align="center" style="margin: 20px;">		
		<input class="btn big sync"  type="submit" value="Sync">
	</div>
</div>
</form>
<div id="ed">
</div>
<script type="text/javascript">
$("a.btn.disabled").click(function(){
	//alert("disabled");
	return false;
});


$(function(){	
////////////////click Cancel//////////////////////////
	$(".btn.cancel").click(function(){
		if($(".btn.cancel").hasClass('disabled')){			
 	 	}else{
 	 		document.getElementById('SoldierID').value = '';
 	 		document.getElementById('SoldierName').value = '';
 	 		disable($(".btn.add"));
			disable($(".btn.save"));
			disable($(".btn.cancel"));
 	 	}
 	 	return false;
 	});
	
///////////////////Input Event///////////////////////////
	$("#SoldierName").keyup(function(e){
		var id = $("#SoldierID").val();
		var name = $("#SoldierName").val();
		
		if(name == ''){
			disable($(".btn.add"));
			disable($(".btn.save"));
		}else{	
			enable($(".btn.cancel"));					
			if(id != '' && name!=''){				
				enable($(".btn.save"));				
			}else if(id == '' && name!=''){
				enable($(".btn.add"));
				disable($(".btn.save"));
			}
		}		
	});	
///////////////Save click/////////////////
	$(".btn.save").click(function(){
		if($(this).hasClass("disabled")){
			return false;
		}
		updateSoldier();			
	});		

	$(".btn.add").click(function(){
		if($(this).hasClass("disabled")){
			return false;
		}
		updateSoldier();
	});
});

function editSoldier(key){
	id = $("#Soldier-"+key+" .id").text();
	name = $("#Soldier-"+key+" .name").text();
	nameSV = $("#Soldier-"+key+" .nameSV").text();	
	document.getElementById('SoldierID').value = id;
	document.getElementById('SoldierName').value = name;
	document.getElementById('nameSV').value=nameSV;
	if($(".btn.save").hasClass('disabled')){
		$(".btn.save").removeClass("disabled");		
	}
	if($(".btn.cancel").hasClass('disabled')){
		$(".btn.cancel").removeClass("disabled");		
	}
	if(!$(".btn.add").hasClass('disabled')){
		$(".btn.add").addClass("disabled");
	}
}
/*******click delete button***********/
function deleteSoldier(key){
	id = $("#Soldier-"+key+" .id").text();
	name = $("#Soldier-"+key+" .name").text();
	if(!confirm("Bạn có muốn xóa Soldier: " + name)){
		return false;
	};
	$.ajax({
		type: "POST",
	//	url: "http://localhost/vng/game-tool/sourcecode/chipzin/questline/update",
		url: "<?php echo $this->baseUrl.'/campaign/soldier/delete/'?> ",
		data: "ID="+id,
		dataType:"json",
		success: function(msg){
			if(parseInt(msg.length)==0){					
				window.location.reload();
			}
			else{
				$('#ed').html('');
				$('#ed').append('<p>Các Campaign có Soldier này</p>');
				$.each(msg, function(key, val) 
				{
					$('#ed').append('<tr><td><p>'+ "Battle "+val.BattleID+" trong campaign "+ val.Campaign+'</p></td><td><p><a class="tool-16 edit" href="<?php echo $this->baseUrl;?>/campaign/campaign/edit/id/'+val.Campaign+'"></a></p></td></tr>');
				});

				$("#ed").dialog
				({
					title: "Không xóa được",
					show : "slide",
					height: 280,
					width: 250,
					modal: true,
					buttons: 
					{
						"close": function() 
						{
							$(this).dialog("close");							
						}										
					}
				});		
			}		
		}
	});	
	
}
function updateSoldier(){
	var id = $("#SoldierID").val();
	var name = $("#SoldierName").val();
	$.ajax({
		type: "POST",
		url: "<?php echo $this->baseUrl.'/campaign/soldier/update/'?> ",
		data: "Name=" +name +"&ID="+id,
		success: function(msg){
			if(msg != ""){
				if(parseInt(msg)==1)
				{
					if(!confirm("Bạn có muốn edit Soldier: " + name)){
						return false;
					}
				}
				window.location.reload();
			}
			else{
				alert("Update KO thành công");				
			}			
		}
	});	
}

</script>

