<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl ?>/media/scripts/datetimepicker/jquery-ui.css" />
<script type="text/javascript" src="<?php echo $this->baseUrl ?>/media/scripts/datetimepicker/jquery-ui.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl ?>/media/scripts/datetimepicker/jquery.ui.datetimepicker.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl ?>/media/scripts/jQueryBubblePopup/jquery.bubblepopup.v2.3.1.min.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl ?>/media/scripts/jQueryBubblePopup/jquery.bubblepopup.v2.3.1.css" />

<?php if($this->errMsg) :?>
    <?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>        
    <?php $this->showMessage($this->msg)?>    
<?php endif;?>
<div id="template"  style="display: none;" >
	<fieldset id="event{id}">
		<legend>Sự kiện &nbsp;&nbsp;<a title="Xóa" href="javascript:deleteEvent({id})"><img src="<?php echo $this->baseUrl ?>/media/images/icons/page_white_delete.png"/></a></legend>
		<input name="hidId[]" value="" type="hidden"/>
		<label for="begin">Bắt đầu : </label>
		<input name="txtBeginTime[]" value="" id="txtBeginTime{id}" type="text" tabindex="1" />&nbsp;(mm/dd/yyyy)
		<br />
		<label for="end">Kết thúc : </label>
		<input name="txtEndTime[]" id="txtEndTime{id}" value="" type="text" tabindex="2" />&nbsp;(mm/dd/yyyy)
		<br />			
		<label for="type">Vàng : x</label>
		<input name="txtGold[]" id="txtGold{id}" value="" type="text" tabindex="2" />
		<br /> 	
		<label for="value">Kinh nghiệm : x</label>
		<input name="txtExp[]" id="txtExp{id}" value="" type="text" tabindex="6" />			
  </fieldset>
	<script type="text/javascript" >
		$(function() 
		{
			$("#txtBeginTime{id}, #txtEndTime{id}").datetimepicker({
					dateFormat: 'mm/dd/yyyy HH:MM:00',
					changeYear: true,
					changeMonth:true,
					showButtonPanel:true
				}
			);
		})
	</script>
</div>
<div id="box">
    <h3 id="adduser">Điều chỉnh sự kiện</h3>
	<form id="form" action="" method="post" onSubmit="return validate()">  
		<input type="hidden" name="hidSync" id="hidSync"/>	
		<input type="hidden" name="hidLocation" id="hidLocation"/>
		<?php $this->listEvent($this->data, $this) ?>
		<div id="add" align="right">
			<a href="javascript:addEvent()" title="Thêm sự kiện"><img src="<?php echo $this->baseUrl ?>/media/images/icons/add.png"/></a>
		</div>
	  <div align="center">
		  <input id="button1" type="submit" value="Lưu" />&nbsp;&nbsp;
		  <input id="button2" class="btnSync" type="button" value="Sync" /> 
	  </div>
	</form>
</div>
<script type="text/javascript">
	var count = <?php echo $this->count ?>;
	function addEvent()
	{
		count++;
		var html = $("#template").html();
		html = html.replace(/{id}/gi, count);
		$("#add").before(html);
	}
	
	function deleteEvent(id)
	{
		if(confirm("Bạn có muốn xóa sự kiện này không?") == true)
			$("#event" + id).remove();		
	}
	
	function deleteEventReal(id,idHtml)
	{
		if(confirm("Bạn có muốn xóa sự kiện này không?") == true)
		{
			$.ajax({
				type:"POST",
				url:"<?php echo $this->baseUrl."/".$this->controllerName ?>/delelegoldexp",
				data: "id=" + id,
				success: function(msg)
				{
					if(msg != "")
					{
						alert("Bạn không có quyền thực hiện thao tác này");
						return;
					}
					else
					{
						alert("Xóa thành công");
						$("#event" + idHtml).remove();
					}
				}
			});
		}
	}
	
	$(function(){
		$("input[id*='txtBeginTime_']").each(function(){
			$(this).datetimepicker({
					dateFormat: 'mm/dd/yyyy HH:MM:00',
					changeYear: true,
					changeMonth:true,
					showButtonPanel:true
				}
			)
		});
		
		$("input[id*='txtEndTime_']").each(function(){
			$(this).datetimepicker({
					dateFormat: 'mm/dd/yyyy HH:MM:00',
					changeYear: true,
					changeMonth:true,
					showButtonPanel:true
				}
			)
		});
		
		$('.btnSync').CreateBubblePopup({
													align: 'right',
													
													innerHtml: 'Click to sync data', 
													innerHtmlStyle: {
																		color:'#FFFFFF', 
																		'text-align':'center'
																	},
																	
													themeName: 	'all-black',
													themePath: 	'<?php echo $this->baseUrl ?>/media/scripts/jQueryBubblePopup/jquerybubblepopup-theme'
											   });
		
		$('.btnSync').click(function(){		
			var btn = $(this);

			// show a bubble popup with new options when "this" shoppingcart button is clicked
			btn.ShowBubblePopup({

													align: 'center',
													innerHtml: '<p id="errorpop" style="color:red"></p>'+
																'<p><input id="rdDev" checked name="rdLocation" value="<?php echo DEV ?>" type="radio"/> <span style="color:blue;font-weight:bold">DEV</span>&nbsp;&nbsp;&nbsp;&nbsp;<input id="rdLive" name="rdLocation" type="radio" value="<?php echo LIVE ?>"/> <span style="color:red;font-weight:bold;">LIVE</span></p>' + 
															   '<p><input type="button" onclick="syncData()" id="btnOk" value="Đồng ý"/>&nbsp;&nbsp;<input type="button" id="btnClose" value="Hủy"/></p>',

													innerHtmlStyle:{ 
																	color:'#666666', 
																	'text-align':'left'
																   },

													themeName: 	'azure',
													themePath: 	'<?php echo $this->baseUrl ?>/media/scripts/jQueryBubblePopup/jquerybubblepopup-theme'

												}, false); //save_options = false; it will use new options only on click event, it does not overwrite old options.


			// "freeze" the Bubble Popup then it will not respond to mouse events (as mouseover/mouseout) 
			// until ".ShowBubblePopup()" or ".HideBubblePopup()" is called again.
			btn.FreezeBubblePopup(); 

			// when the "close" link is clicked, hide the bubble popup
			$('#btnClose').click(function(){
				$(btn).HideBubblePopup();
			});
		});//end onclick event
	});
	
	function validate()
	{
		var check = true;
		$("input[name*='txtBeginTime']").each(function(){				
			if($(this).val() == "" && $(this).attr("id") != "txtBeginTime{id}")
			{				
				check = false;
				return;
			}			
		});
		
		if(!check)
		{
			alert("Vui lòng điền đầy đủ thời điểm bắt đầu");
			return false;
		}
		
		check = true;
		$("input[name*='txtEndTime']").each(function(){			
			if($(this).val() == "" && $(this).attr("id") != "txtEndTime{id}")
			{
				check = false;
				return;				
			}			
		});
		
		if(!check)
		{
			alert("Vui lòng điền đầy đủ thời điểm kết thúc");
			return false;
		}
		
		return true;
	}
	
	function syncData()
	{
		if($("#rdDev").is(":checked"))
			$("#hidLocation").val($("#rdDev").val());
		else
			$("#hidLocation").val($("#rdLive").val());
		
		if(confirm("Bạn có chắc thực hiện sync dữ liệu với các server không?") == true)
		{
			$("#hidSync").val(1);
			$("#form").submit();
		}	
	}
</script>