<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>
<style>
.solider{
	width: 40px;
}

table#battle input{
	max-width: 50px;
	overflow: hidden;
	margin-top: 2px;
	margin-bottom: 2px;
}
table#battle{
	border:solid 1px !important; 
}
table#battle .hidden{
	opacity:0.3;
}
table#battle td{
	margin: 0;
	overflow: hidden;
}
select{
	margin: 0;
	padding:0;
	max-width: 110px;
	min-width: 110px;
	height: 25px;
	overflow: hidden;
}
.style{
	margin: auto;text-align: center;padding-top: 2px;padding-bottom: 2px;
}
}
</style>
<form  class="myform" id="formPaging" name="formPaging" action="" method="post">
<div class='mybox'>
	<h3>Campaign Edit</h3>
	<table>
	<tr>
		<td>
			<label>Campaign Id :</label>
			<select name='campaignID' id='campaignID'>
				<option value='<?php echo $this->campaign->ID;?>'><?php echo $this->campaign->ID;?></option>
			</select>
		</td>			
		<td>
			<label>Campaign Name:</label>
			<input type="text" name='Name' id=Name' value='<?php echo $this->campaign->Name;?>' />
		</td>
		<td>
			<label>World Map:</label>
			<input type="text" readonly="readonly" value='<?php echo $this->campaign->Wor;?>' name='nextCampaign' id='nextCampaign'/>
		</td>
		</tr>
	</table>
	<h3>Battle</h3>	
	
	<table id='battle' width="100%" >
		<thead>
			<tr>
				<td width="15px;">ID</td>
				<td width="20px;">Order</td>
				<td>Layout</td>
				<td>Award</td>
			</tr>
		</thead>
	<?php foreach ($this->arrbattle as $rowbattle){?>
		<tr>
			<td><?php echo $rowbattle->ID;?></td>
			<td>
				<input type="text" name='Order' id='Order' value='<?php echo $rowbattle->Order;?>'/>
			</td>
			<td width="auto">
				<?php echo $this->selection($this->arrlayout,$rowbattle->Layout,"Layout",array('key'=>"ID",'name'=>"Name",'default'=>"234234234"))?>
				<br/>
				<table id='tb_layout'>
					<tr>
						<td style="margin: 0;padding: 0;">
							<em>S:</em><?php echo $this->selection($this->arrSoldier,1,"Solider",
												array('key'=>"ID",'name'=>"Name",'default'=>"234234234"))?><br/>
							<em>L:</em><input type='text' class='solider' id='#' name='#'/>
						</td>
						<td>
							<em>S:</em><?php echo $this->selection($this->arrSoldier,1,"Solider",
												array('key'=>"ID",'name'=>"Name",'default'=>"234234234"))?><br/>
							<em>L:</em><input type='text' class='solider' id='#' name='#'/>
						</td>
						<td>
							<em>S:</em><?php echo $this->selection($this->arrSoldier,1,"Solider",
												array('key'=>"ID",'name'=>"Name",'default'=>"234234234"))?><br/>
							<em>L:</em><input type='text' class='solider' id='#' name='#'/>
						</td>						
					</tr>
					<tr>
						<td>
							<em>S:</em><?php echo $this->selection($this->arrSoldier,2,"Solider",
												array('key'=>"ID",'name'=>"Name",'default'=>"234234234"))?><br/>
							<em>L:</em><input type='text' class='solider' id='#' name='#'/>
						</td>
						<td>
							<em>S:</em><?php echo $this->selection($this->arrSoldier,2,"Solider",
												array('key'=>"ID",'name'=>"Name",'default'=>"234234234"))?><br/>
							<em>L:</em><input type='text' class='solider' id='#' name='#'/>
						</td>
						<td>
							<em>S:</em><?php echo $this->selection($this->arrSoldier,2,"Solider",
												array('key'=>"ID",'name'=>"Name",'default'=>"234234234"))?><br/>
							<em>L:</em><input type='text' class='solider' id='#' name='#'/>
						</td>
					</tr>
					<tr>
						<td>
							<em>S:</em><?php echo $this->selection($this->arrSoldier,2,"Solider",
												array('key'=>"ID",'name'=>"Name",'default'=>"234234234"))?><br/>
							<em>L:</em><input type='text' class='solider' id='#' name='#'/>
						</td>
						<td>
							<em>S:</em><?php echo $this->selection($this->arrSoldier,2,"Solider",
												array('key'=>"ID",'name'=>"Name",'default'=>"234234234"))?><br/>
							<em>L:</em><input type='text' class='solider' id='#' name='#'/>
						</td>
						<td>
							<em>S:</em><?php echo $this->selection($this->arrSoldier,1,"Solider",
												array('key'=>"ID",'name'=>"Name",'default'=>"234234234"))?><br/>
							<em>L:</em><input type='text' class='solider' id='#' name='#'/>
						</td>
					</tr>
				</table>
			</td>
			<td width="200px">
			<div id='div_award_<?php echo $rowbattle->ID;?>'>				
				<a href='javascript:addAward(<?php echo $rowbattle->ID; ?>)' class='ico-16 add' ></a><br/>
				
				<?php foreach ($this->arraward[$rowbattle->ID] as $row){?>
				<?php echo $this->selection($this->arrawardtype,$row->ID,"AwardID_$rowbattle->ID[]",array('key'=>'ID','name'=>'Name'))?>	
				<?php }?>
			</div>
			</td>
		</tr>
		<?php }?>
	
	</table>
	<div class="style">
	<a class="btn add" href="">Add</a>
	<a class="btn save" href="">Save</a>
	</div>
</div>
</form>
<!-- Dung de them 1 award -->
<div style="display: none">
	<div id="selectAwardType">
		
		<?php echo $this->selection($this->arrawardtype,1,"AwardID[]",array('key'=>'ID','name'=>'Name'))?>
		
	</div>
</div>
<!--  -->
<script>
	function addAward(key)
	{
		var select = $("#selectAward").html();
		var count = $("#div_award .award-list").size();
		var btnDel= "<a class='tool-16 delete' href='javascript:removeAward("+count+")'></a>";
		var input="<input class='solider' type='text' id='award_input'/>"
		var html = "<div class='award-list' id='award-list-"+count+"'>"+select+input+btnDel+"</div>";
		$("#div_award_"+key).append(html);
	}
	function removeAward(key)
	{
		$("#award-list-"+key).remove();
	}
</script>