<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>
<style>
.soldier{
	width: 40px;
}
table#battle{
	border:1px solid; 	
}

table#battle input{	
	overflow: hidden;
	margin-top: 2px;
	margin-bottom: 2px;
}

table#battle .hidden{
	opacity:0.3;
}
table#battle td{
	margin: 0;
	overflow: hidden;
	vertical-align: middle;
}
.c_order input{
	width:30px;
	text-align:center; 
}
/**************Table Layout********************/
 table#tb_layout{
	border-collapse: separate;
	border-spacing: 10px;
 }
table#tb_layout td select, table#tb_layout td input{
	border:none;
	max-width: 200px;	
	overflow: hidden;
	background-color: #D9EAED;
	padding:0px;
	margin: 0px;
}
table#tb_layout td select{
	width: 70%;
	float: left;
}
table#tb_layout td input{
	width: 22%;	
}
table#tb_layout td.invisible,table#tb_layout td.invisible *{	
	opacity:0.0;
}

table#tb_layout td.visible,table#tb_layout td.visible *{
	background: #EFEFEF;	
	opacity:1.0;
    color: blue;
}
table#tb_layout td.visible{
	border: 2px solid lightblue;
}
/**************************/
td.b_award select{
	width: 65%;
} 
td.b_award input{
	width: 20%;
}

/**************End Table Layout****************/
.style{
	margin: auto;text-align: center;padding-top: 2px;padding-bottom: 2px;
}


</style>
<form  class="myform" id="formPaging" name="formPaging" action="" method="post">
<div class='mybox'>
	<h3>Campaign Edit</h3>
	<table>
	<tr>
		<td>
			<label>World Map:</label>
			<input type="text" readonly="readonly" value='<?php echo $this->campaign->WorldMap;?>' name='nextCampaign' id='nextCampaign'/>
		</td>
		<td>
			<label>Select Campaign:</label>			
			<select name='campaignID' id='campaignID'>							
				<?php echo $this->options($this->arrCampaign,$this->campaign->ID,array('key'=>"ID",'name'=>"Name","flag"=>1))?>				
			</select>
		</td>			
		<td>
			<label>Campaign Name:</label>
			<input type="text" name='Name' id='Name' value='<?php echo $this->campaign->Name;?>' />
		</td>
		
		</tr>
	</table>
	<h3>Battle</h3>	

	<table class="list" id='battle'>
		<thead>
			<tr>
				<td width="15px">ID</td>
				<td width="15px" class="center"><a onclick="order();" href='#'>Order</a></td>
				<td width="600px" class="center">Layout</td>
				<td>Award</td>
				<td class="center" width="20px">Action</td>
				<td width="5"></td>	
			</tr>
		</thead>
		<tbody id="list-battle">	
		<?php foreach ($this->arrbattle as $rowbattle){?>
		<tr class='tr-battle' id='battle-<?php echo $rowbattle->ID?>'>
			<td class="b_id">
                <span><?php echo $rowbattle->ID;?></span>
                <input style="display:none" type="text" id='BattleID' name='BattleID' value='<?php echo $rowbattle->ID;?>'/>
            </td>

			<td class="center c_order">
				<input type="text" name='Order'  id='Order' value='<?php echo $rowbattle->Order;?>'/>
			</td>
			<td class="b_layout" width="300px" style="text-align: center;">				
				<select style="width=100%;border: 2px solid lightblue;" class="layout"  name="Layout" tabindex="2">
					<?php echo $this->options($this->arrlayout,$rowbattle->Layout,array('key'=>"ID",'name'=>"Name"))?>
					<option  value="-1" style="color:red">New Layout</option>	
				</select>
				
				<table id='tb_layout'>
					<tr>
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][0])?"visible":"invisible"?>
						<td id="point0" class="<?php echo  $strclass?>">
							<?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],0);
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[0]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>												
												
							<em>lv:</em><input type='text' class='<?php echo $strclass?>_0' id='levelSolider' name='levelSolider[0]' value="<?php echo $arrBS['Level'];?>"/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][3])?"visible":"invisible"?>
						<td id="point3" class="<?php echo  $strclass?>" >
							<?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],3); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[3]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							<em>lv:</em><input type='text' class='<?php echo $strclass?>_3' id='levelSolider' name='levelSolider[3]' value="<?php echo $arrBS['Level'];?>"/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][6])?"visible":"invisible"?>
						<td id="point6" class="<?php echo  $strclass?>" >
							<?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],6); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[6]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							<em>lv:</em><input type='text' class='<?php echo $strclass?>_6' id='levelSolider' name='levelSolider[6]' value='<?php echo $arrBS['Level'];?>'/>
						</td>						
					</tr>
					<tr>
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][1])?"visible":"invisible"?>
						<td  id="point1" class="<?php echo  $strclass?>" >
							<?php  $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],1); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[1]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							<em>lv:</em><input type='text' class='<?php echo $strclass?>_1' id='levelSolider' name='levelSolider[1]' value='<?php echo $arrBS['Level'];?>'/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][4])?"visible":"invisible"?>
						<td  id="point4"class="<?php echo  $strclass?>" >
							<?php  $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],4); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[4]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							<em>lv:</em><input type='text'class='<?php echo $strclass?>_4' id='levelSolider' name='levelSolider[4]' value='<?php echo $arrBS['Level'];?>'/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][7])?"visible":"invisible"?>
						<td  id="point7"class="<?php echo  $strclass?>" >
							<?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],7);
							 echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[7]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							<em>lv:</em><input type='text' class='<?php echo $strclass?>_7' id='levelSolider' name='levelSolider[7]' value='<?php echo $arrBS['Level'];?>'/>
						</td>
					</tr>
					<tr>
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][2])?"visible":"invisible"?>
						<td id="point2" class="<?php echo  $strclass?>" >
							<?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],2); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[2]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							<em>lv:</em><input type='text' class='<?php echo $strclass?>_2' id='levelSolider' name='levelSolider[2]' value='<?php echo $arrBS['Level'];?>'/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][5])?"visible":"invisible"?>
						<td id="point5" class="<?php echo  $strclass?>" >
							<?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],5); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[5]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							<em>lv:</em><input type='text' class='<?php echo $strclass?>_5' id='levelSolider' name='levelSolider[5]' value='<?php echo $arrBS['Level'];?>'/>
						</td>
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][8])?"visible":"invisible"?>
						<td id="point8" class="<?php echo  $strclass?>" >
							<?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],8); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[8]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							<em>lv:</em><input type='text' class='<?php echo $strclass?>_8' id='levelSolider' name='levelSolider[8]' value='<?php echo $arrBS['Level'];?>'/>
						</td>						
					</tr>
				</table>
			</td>
			<td width="200px" class="b_award">					
				<div><a class='tool-16 add' href=''></a></div>
				<?php foreach ($this->arraward[$rowbattle->ID] as $key=>$row){?>					
					<div>
						<select  name='AwardTypeID[]' onChange='changeAwardType(this)'>
						<?php if (empty($row->AwardTypeID)){?>
							
						<?php } ?>	
						<?php echo $this->options($this->arrawardtype,$row->AwardTypeID,array('key'=>'AwardTypeID','name'=>'Name'))?>
						<option  value="-1" style="color:red">New Type</option>
						</select>					
						<input type='text' id='Value' name='Value[]' value='<?php echo $row->Value?>'/>					
						<a class='tool-16 delete' href='#'></a>	
					</div>
				<?php }?>			
			</td>
			<td class="center action">
				<a class='tool-24 save disabled' id="" href='#'></a><br><br>
				<a class='tool-24 reset disabled' href='javascript:resetBattle(<?php echo $rowbattle->ID ?>)'></a><br><br>
				<a class='tool-24 delete' id="" href='javascript:deleteBattle(<?php echo $rowbattle->ID ?>)'></a>
			</td>
			<!--Status-->
			<td class="td-status"><a title="ok" class="status tool-16 ok"></a></td>
		</tr>
		
		<?php }?>
	</tbody>
	</table>
	<div class="style" style="margin:20px">
		<a class="btn add" href="javascript:addBattle()"> New </a>	
		<a class="btn save" href="javascript:saveAll()">Save All</a>

	</div>
</div>
</form>

<!-- hidden div: dung de de thay doi html -->
<div style='display:none'>

	<!-- # Show loi~-->
	<div id='dialog'>
		<p class='ct'></p>
		<p class='ft'> </p>
	</div>
	<!-- # Show loi~-->
	
	<!-- Dung de them 1 award -->
	<div id="temp-select-award">
		<div>
			<select name="AwardTypeID[]" onChange="changeAwardType(this)">
				<?php echo "<option selected value='' style='color:red'></option>"?>
				<?php echo $this->options($this->arrawardtype,0,array('key'=>'AwardTypeID','name'=>'Name'))?>	
				<?php echo "<option  value='-1' style='color:red'> New Type</option>"?>		
			</select>
			<input type='text' name='Value[]' value=''/>					
			<a class='tool-16 delete' href='#'></a>	
		</div>	

	</div>
	<!-- # Them AwardType~-->
	<div  id='insert-awardtype'>		
		<input  type="text" id="awardtype" name="awardtype" value="AwardType" />		
	</div>
	<!-- # Them AwardType-->
	
	<!-- #Them Layout-->
	<div id='insert-layout'>
		<form  id="layout" name="layout" action="" method="post">
			<table>
				<tr>
					<td colspan="3">
					Tên layout :<input type="text" name="namelayout">
					</td>
				</tr>
				<tr>
					<td>1<input type="checkbox" name="point" value="0" /></td>
					<td>4<input type="checkbox" name="point" value="3" /></td>
					<td>7<input type="checkbox" name="point" value="6" /></td>
				</tr>
				<tr>
					<td>2<input type="checkbox" name="point" value="1" /></td>
					<td>5<input type="checkbox" name="point" value="4" /></td>
					<td>8<input type="checkbox" name="point" value="7" /></td>
				</tr>
				<tr>
					<td>3<input type="checkbox" name="point" value="2" /></td>
					<td>6<input type="checkbox" name="point" value="5" /></td>
					<td>9<input type="checkbox" name="point" value="8" /></td>
				</tr>
			</table>
		</form>	
	</div>
	<!-- #Them Layout-->
	
	<!-- #Them Battle-->
	<div>
		<table id="battle-temp">
		<tbody>	
			<tr class="tr-battle">
			<td class="b_id">
				<span>!</span>
				<input style="display:none" type="text" id="BattleID" name="BattleID" value="">
			</td>

			<td class="center c_order">
				<input type="text" name="Order" id="Order" value="1">
			</td>
			<td width="300px" style="text-align: center;">				
				<select style="width=100%;border: 2px solid lightblue;" class="layout" name="Layout" tabindex="2">
					<option value=""></option>	
					<?php echo $this->options($this->arrlayout,-1,array('key'=>"ID",'name'=>"Name"))?>
					<option  value="-1" style="color:red">New Layout</option>	
				</select>				
				<table id='tb_layout'>
					<tr>						
						<td id="point0" class="visible">
							<?php
							echo $this->selection($this->arrSoldier,-1,"solider[0]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>												
							<em>lv:</em><input type='text' id='levelSolider' name='levelSolider[0]' value=""/>
						</td>						
						<td id="point3" class="visible" > 
							<?php 
							echo $this->selection($this->arrSoldier,-1,"solider[3]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							<em>lv:</em><input type='text' id='levelSolider' name='levelSolider[3]' value=""/>
						</td>						
						<td id="point6" class="visible" >
							<?php 
							echo $this->selection($this->arrSoldier,-1,"solider[6]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							<em>lv:</em><input type='text'  id='levelSolider' name='levelSolider[6]' value=''/>
						</td>						
					</tr>
					<tr>						
						<td  id="point1" class="visible" >
							<?php  
							echo $this->selection($this->arrSoldier,-1,"solider[1]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							<em>lv:</em><input type='text'  id='levelSolider' name='levelSolider[1]' value=''/>
						</td>					
						<td  id="point4"class="visible" >
							<?php 
							echo $this->selection($this->arrSoldier,-1,"solider[4]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							<em>lv:</em><input type='text' id='levelSolider' name='levelSolider[4]' value=''/>
						</td>						
						<td  id="point7"class="visible" >
							<?php 
							 echo $this->selection($this->arrSoldier,-1,"solider[7]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							<em>lv:</em><input type='text'  id='levelSolider' name='levelSolider[7]' value=''/>
						</td>
					</tr>
					<tr>						
						<td id="point2" class="visible" >
							<?php 
							echo $this->selection($this->arrSoldier,-1,"solider[2]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							<em>lv:</em><input type='text' id='levelSolider' name='levelSolider[2]' value=''/>
						</td>						
						<td id="point5" class="visible">
							<?php 
							echo $this->selection($this->arrSoldier,-1,"solider[5]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							<em>lv:</em><input type='text' name='levelSolider[5]' value=''/>
						</td>
						
						<td id="point8" class="visible">
							<?php 
							echo $this->selection($this->arrSoldier,-1,"solider[8]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							<em>lv:</em><input type='text' id='levelSolider' name='levelSolider[8]' value=''/>
						</td>						
					</tr>
				</table>
			</td>
			<td width="200px" class="b_award">					
				<div><a class="tool-16 add" href=""></a></div>							
			</td>
			<td class="center action">
				<a class="tool-24 save disbled" id="" href="#"></a><br><br>
				<a class="tool-24 reset" href="javascript:resetBattle(26)"></a><br><br>
				<a class="tool-24 delete" id="" href="#"></a>
			</td>
			<!--Status-->
			<td class="td-status"><a title="Not Save" class="status tool-16 warning"></a></td>
		</tr>
			</tbody>
		</table>
	
	</div>
</div>


<!-- Javascript  -->
<script>
/************************ThaoNX********************/	 
	function showDiaglog(){	
		$("#dialog").dialog({
				title: "Diaglog",
				height: 400,
				width: 350,
				modal: true,
				buttons: {
					"Save": function() {						
						$(this).dialog("close");							
					}										
				}
		});
	}
	////////////////////////////////
	function updateStatus(e,status,title){
		e.removeClass("ok");	
		e.removeClass("warning");
		e.removeClass("loading");
		e.addClass(status);
		e.attr("title",title);
	}	
	////////////////////////////////
	function addAward(e){
		var parent_td = $(e).parent().parent();
		var parent_tr = parent_td.parent();	
		var html = $("div#temp-select-award div").clone();
		parent_td.append(html);
		parent_tr.change();
	}
	/////////////////////////////
	function removeAward(e){
		var parent_div = $(e).parent();
		var parent_tr = $(e).parent().parent().parent();				
		parent_div.remove();
		parent_tr.change();
	}
	/////////////////////////
	function saveAward(key){
		var data = $("#div-battle-award-"+key+" *").serialize();
		data += "&Action=update-all&BattleID="+key+"";
		$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/campaign/campaign/updateaward'?> ",
			data: data,
			success: function(msg){
				if(msg == '1'){					
					alert("Successfull");
				}else{
					alert("Error");					
				}
				window.location.reload();
			}
		});
	}
	////////////////////////////////
	function saveBattle(e){
		var campaignID = $("#campaignID").val();		
		var parent_tr = $(e).parent().parent();
		var a_status = parent_tr.find(".status");
		var a_save = parent_tr.find(".tool-24.save");
		var a_reset = parent_tr.find(".tool-24.reset");
		updateStatus(a_status,"loading","loading");	
		var data = parent_tr.find("*").serialize();
		var arr_data = parent_tr.find("*").serializeArray();		
		if(validate2(arr_data)==false){
			$("#dialog").dialog({
				title: "Diaglog",
				height: 400,
				width: 350,
				modal: true,
				buttons: {
					"Continue": function() {						
						$(this).dialog("close");							
					}										
				}
		});
			return;
		}
		data += "&Campaign="+campaignID;		
		$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/campaign/battle/save'?> ",
			data: data,
			dataType:"json",
			success: function(msg){	
				if(msg.msg == '1'){					
					 updateStatus(a_status,"ok","ok");
					 a_save.addClass("disabled");
					 a_reset.addClass("disabled");
					 if(msg.BattleID){ 						
						parent_tr.find("td.b_id input[name='BattleID']").attr("value",msg.BattleID);
						parent_tr.find("td.b_id span").text(msg.BattleID);						
                };   
				}else{
					alert(msg.msg);					
				}				
			}
		});		
	}
	////////////////////////
	function deleteBattle(e){
		var parent_tr = $(e).parent().parent();
		var a_status = parent_tr.find(".status");
		var battle_id = parent_tr.find("#BattleID").val();		
		updateStatus(a_status,"loading","loading");			
		if(battle_id){
			$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/campaign/battle/delete'?> ",
			data: {
				BattleID:battle_id
			},
			success: function(msg){				
					if(msg == '1'){					
						parent_tr.remove();						
					}else{
						alert(msg);					
					}
				
				}
			});			
		}else{
			parent_tr.remove();
		}
	}
	////////////////////////
	function resetBattle(key){
		if(!confirm("Reset???")){
			return false;
		}
		$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/campaign/battle/getinfo'?> ",
			data: {
				BattleID:key
			},
			success: function(msg){				
				alert(msg);
			}
		});
	}
	///Save All
	function saveAll(){
		$("table#battle").find("td.action .save").not(".disabled").each(function (index){
			$(this).click();
		});
	}
	///Add battle///
	function addBattle(){		
	 	var html = $("table#battle-temp .tr-battle").clone();		
		$("table#battle tbody#list-battle").append(html);		
	}

	/********************AwardType****************************/
	 //onchange AwardType
	function changeAwardType(element){		
		var selected = element.value;
		if(selected == -1){
			addAwardType();
		}
	}
	//Show Dialog
	function addAwardType(){
		$("#insert-awardtype").dialog({
			title: "New AwardType",
			height: 400,
			width: 250,
			modal: true,
			buttons: {
				"Save": function() {
					type_name = $('div#insert-awardtype #awardtype').val();											
					$.ajax({
						type: "POST",
						url: "<?php echo $this->baseUrl.'/campaign/AwardType/insert' ?> ",
						data: "Name=" + type_name,
						dataType: "json",
						success: function(msg){							
							if(msg.msg=="1"){								
								updateAwardTypeSelect(msg.AwardTypeID,type_name);
							}else{
								alert(msg.msg);
							}														
						}
					});
					$(this).dialog("close");		
				}											
			}
		});		
	}
	//update selectbox award
	function updateAwardTypeSelect(type_id,type_name){
		var option_html = "<option value='"+type_id+"'>"+type_name+"</option>"
		$("select[name='AwardTypeID[]'] option[value='-1']").before(option_html);
		$("select[name='AwardTypeID[]']").each(function(index){
			if($(this).val()==-1){
				$(this).val(type_id);
			}	
		});
		//$("td.b_award select option[value='-1']").before(option_html);
	}
	/*******************Layout**************************/
	//insert layout into database
	function insertLayout(e){
		var arraytemp = new Array();
		var name = document.layout.namelayout.value;
		c_value = "[";
		for (var i=0; i < document.layout.point.length; i++){
			if (document.layout.point[i].checked) {
				arraytemp[i] = 1;
			}else{
				arraytemp[i] = 0;
			}
		}
		c_value += arraytemp[0]+','+arraytemp[3] +','+ arraytemp[6] + ','+ arraytemp[1] + ','+ arraytemp[4] + ','+ arraytemp[7] + ','+ arraytemp[2] + ','+ arraytemp[5] + ','+ arraytemp[8];
		c_value += "]&name="+name;
		$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/campaign/Layout/insert' ?> ",
			data: "point=" + c_value,
			dataType:"json",
			success: function(msg){					
				if(msg.msg == "1"){
					updateLayoutSelect(msg.LayoutID,name);
					$(e).val(msg.LayoutID);
					$(e).change();// delegate to change envent selectbox
				}else{
					alert(msg.msg);
				}
			}
		});	
	}	
	//popup form insert layout
	function popupInsertLayout(e){
		$("#insert-layout").dialog({
				title: "New Layout",
				height: 250,
				width: 220,
				modal: true,
				buttons: {
					"Save": function() {
						insertLayout(e);
						$(this).dialog("close");							
					}										
				}
		});
	}
	//update selectbox Layout
	function updateLayoutSelect(layout_id,layout_name){		
		var option_html = "<option value='"+layout_id+"'>"+layout_name+"</option>";
		$("select.layout option[value='-1']").before(option_html);		
	}
	//update layout point when change layout ID
	function updateLayoutPoint(e,json){//e la the <td>		
		var table = e.children("table#tb_layout");
		$.each(json, function(key, val) {
			if(val==0){
				table.find("td#"+key).removeClass("visible").addClass("invisible");
				table.find("td#"+key +" select").attr('disabled',true);
				table.find("td#"+key +" input").attr('disabled',true).attr("value","");
			}else{
				table.find("td#"+key).removeClass("invisible").addClass("visible");
				table.find("td#"+key +" select").attr('disabled',false);
				table.find("td#"+key +" input").attr('disabled',false);						
			}
		});											
	}
	//change layout
	function changeLayout(e){		
		var parent_td=$(e).parent();		
		var layoutID=$(e).val();
		if(layoutID==-1){			
			popupInsertLayout(e);//e la the <td>		
		}else{	
			$.ajax({
				type: "POST",
				url: "<?php echo $this->baseUrl.'/campaign/campaign/loadlayout'?> ",
				data: "id=" + layoutID,
				dataType: "json",
				success: function(data){				
					updateLayoutPoint(parent_td,data);
				}			
			});
		}
	}
	/***********************************************/
	// validate
	function validate2(data){
		$("#dialog .ct").html("");		
		jQuery.each(data, function(i, field){  
			if(field.value=="" && field.name!='BattleID'){
				$("#dialog .ct").append("<p class='error'>"+ field.name +"không được bỏ trống</p>" );				
			}			
			else if(isNaN(field.value))
			{
				$("#dialog .ct").append("<p class='error'>"+ field.name +"phải là số</p>" );				
			}
			
			else if( (Number(field.value)>100 || Number(field.value)<0) && field.name!='Value[]' && field.name!='BattleID')
				{					
					$("#dialog .ct").append("<p class='error'>"+ field.name +"Level phải nằm trong khoảng 0 ->100</p>" );
				}
			
		});
		if($("#dialog .ct").html()!=""){			
			return false;
		}
		return true;
	}
	function validate(){
			/*flag=true;			
			$(".battle").each(function(key,val){
				num = key+1;
				flag1=true;
				//////test cac o khong bo trong
				for(var i=0;i<8;i++)
				{
					value=$(val).find('.visible_'+i).val();	
					//
					if(value=='')
					{	

						flag1=false;		
						break;	
					}
				}
				if(flag1==false)
				{
					$("#dialog #ct").append("<p class='error'>Battle" + num + ":	<br>không được bỏ trống các ô</p>");					
					flag=false;
				}
				else {
					
				
						flag2=true;
					////////test gia tri 
						for(i=0;i<8;i++)
						{
							value=$(val).find('.visible_'+i).val();							
							if(isNaN(value) && value=='undefined')
							{							alert(value + "_"+i);					
								flag2=false;
								break;
							}
						}
						if(flag2==false)
						{
							$("#dialog #ct").append("<p class='error'>Battle" + num + ":	<br>Phải là số</p>");	
							flag=false;
						}
						
				}
				
			});
		return flag;	*/
	}

/***************JQUERY***************************/
$(document).ready(function(){
	//update disable status
	$("td.invisible").find("select").attr('disabled','disabled');
	$("td.invisible").find("input").attr('disabled',true);
	//change CampaignID selectbox
	$('#campaignID').change(function(){
		 	var campaignID=$(this).val();
		 	var url = "<?php echo $this->baseUrl.'/campaign/campaign/edit/id/'?>"+campaignID;
		 	$(location).attr('href',url);
	});
	///////////////Delegate/////////////////
	
	//Onchange
	$("table#battle").delegate(".tr-battle", "change", function() {
		$(this).find(".action a.save").removeClass("disabled");
		$(this).find(".action a.reset").removeClass("disabled");		
		$(this).find(".td-status a").removeClass("ok").addClass("warning").attr("title","Not Save");
		return false;
	});
	//save a battle
	$("table#battle").delegate("td.action .save", "click", function() {
		if($(this).hasClass("disabled")){
			alert("disabled");
		}else{
			saveBattle(this);
		}		
		return false;		
	});
	//delete a battle
	$("table#battle").delegate("td.action .delete", "click", function() {
		deleteBattle(this);
		return false;		
	});
	///////Add A Award///////
	$("table#battle").delegate("td.b_award .add", "click", function() {
		addAward(this);		
		return false;		
	});
	///////Remove A Award///////
	$("table#battle").delegate("td.b_award .delete", "click", function(){ 	
		removeAward(this);		
		return false;		
	});
	
	///////Onchange Layout///////
	$("table#battle").delegate("select.layout", "change", function(){ 		
		changeLayout(this);		
	});
	
});
	
</script><!-- Javascript  --><!-- Javascript  -->
<!-- End Javascript  -->
