<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>
<style>
.soldier{
	width: 40px;
}
table#battle{
	border:1px solid; 	
}

table#battle input{	
	overflow: hidden;
	margin-top: 2px;
	margin-bottom: 2px;
}

table#battle .hidden{
	opacity:0.3;
}
table#battle td{
	margin: 0;
	overflow: hidden;
	vertical-align: middle;
}
/**************eTable Layout********************/
 table#tb_layout{

	border-collapse: separate;

 }

table#tb_layout td.invisible{
	
	opacity:0.0;
}
table#tb_layout td.invisible *{
	
	opacity:0.0;
}

table#tb_layout td.visible{
	background: #EFEFEF;	
	opacity:1.0;
	color:blue;
	
}
table#tb_layout td.visible *{
	background: #EFEFEF;	
	opacity:1.0;
	color:blue;
	
}
table#tb_layout td select, table#tb_layout td input{
	border:none;
	max-width: 200px;
	min-width: 100%;	
	overflow: hidden;
	background-color: #D9EAED;
	padding:0px;
	margin: 0px;
	
}
table#tb_layout td select{
	
}
table#tb_layout td input{
	color:black;
}
/**************End Table Layout****************/
.style{
	margin: auto;text-align: center;padding-top: 2px;padding-bottom: 2px;
}


</style>
<form  class="myform" id="formPaging" name="formPaging" action="" method="post">
<div class='mybox'>
	<h3>Campaign Edit</h3>
	<table>
	<tr>
		<td>
			<label>Campaign Id :</label>
			<select name='campaignID' id='campaignID'>
				<option value='<?php echo $this->campaign->ID;?>'><?php echo $this->campaign->ID;?></option>
			</select>
		</td>			
		<td>
			<label>Campaign Name:</label>
			<input type="text" name='Name' id='Name' value='<?php echo $this->campaign->Name;?>' />
		</td>
		<td>
			<label>World Map:</label>
			<input type="text" readonly="readonly" value='<?php echo $this->campaign->WorldMap;?>' name='nextCampaign' id='nextCampaign'/>
		</td>
		</tr>
	</table>
	<h3>Battle</h3>	

	<table class="list" id='battle' width="100%">
		<thead>
			<tr>
				<td width="15px;">ID</td>
				<td  class="center" width="50px;" ><a onclick="order();" href='#'>Order</a></td>
				<td class="center">Layout</td>
				<td>Award</td>
				<td class="center" width="20px;">Action</td>
			</tr>
		</thead>
	<tbody id="campaign">	
	<?php foreach ($this->arrbattle as $rowbattle){?>
		<tr class='battle' id='battle-<?php echo $rowbattle->ID?>'>
			<td><?php echo $rowbattle->ID;?><input style="display:none" type="text" id='BattleID' name='BattleID' value='<?php echo $rowbattle->ID;?>'/></td>

			<td class="center">
				<input type="text" name='Order' id='Order' value='<?php echo $rowbattle->Order;?>'/>
			</td>
			<td width="300px">
				
				<select style="width=100%" id="Layout" name="Layout" tabindex="2">
					<?php echo $this->options($this->arrlayout,$rowbattle->Layout,array('key'=>"ID",'name'=>"Name"))?>
					<option  value="insert" style="color:red"> New Layout</option>	
				</select>
				<br/>
				
				<table id='tb_layout' cellpadding="5" cellspacing="5">
					<tr>
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][0])?"visible":"invisible"?>
						<td id="point0" class="<?php echo  $strclass?>">
							<xx></xx><?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],0);
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[0]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?><br/>												
												
							<input type='text' class='soldier' id='levelSolider' name='level[0]' value="<?php echo $arrBS['Level'];?>"/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][3])?"visible":"invisible"?>
						<td id="point3" class="<?php echo  $strclass?>" >
							<xx></xx><?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],3); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[3]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?><br/>
							<yy></yy><input type='text' class='soldier' id='levelSolider' name='level[3]' value="<?php echo $arrBS['Level'];?>"/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][6])?"visible":"invisible"?>
						<td id="point6" class="<?php echo  $strclass?>" >
							<xx></xx><?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],6); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[6]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?><br/>
							<yy></yy><input type='text' class='soldier' id='levelSolider' name='level[6]' value='<?php echo $arrBS['Level'];?>'/>
						</td>						
					</tr>
					<tr>
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][1])?"visible":"invisible"?>
						<td  id="point1" class="<?php echo  $strclass?>" >
							<xx></xx><?php  $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],1); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[1]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?><br/>
							<yy></yy><input type='text' class='soldier' id='levelSolider' name='level[1]' value='<?php echo $arrBS['Level'];?>'/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][4])?"visible":"invisible"?>
						<td  id="point4"class="<?php echo  $strclass?>" >
							<xx></xx><?php  $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],4); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[4]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?><br/>
							<yy></yy><input type='text' class='soldier' id='levelSolider' name='level[4]' value='<?php echo $arrBS['Level'];?>'/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][7])?"visible":"invisible"?>
						<td  id="point7"class="<?php echo  $strclass?>" >
							<xx></xx><?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],7);
							 echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[7]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?><br/>
							<yy></yy><input type='text' class='soldier' id='levelSolider' name='level[7]' value='<?php echo $arrBS['Level'];?>'/>
						</td>
					</tr>
					<tr>
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][2])?"visible":"invisible"?>
						<td id="point2" class="<?php echo  $strclass?>" >
							<xx></xx><?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],2); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[2]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?><br/>
							<yy></yy><input type='text' class='soldier' id='levelSolider' name='level[2]' value='<?php echo $arrBS['Level'];?>'/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][5])?"visible":"invisible"?>
						<td id="point5" class="<?php echo  $strclass?>" >
							<xx></xx><?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],5); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[5]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?><br/>
							<yy></yy><input type='text' class='soldier' id='levelSolider' name='level[5]' value='<?php echo $arrBS['Level'];?>'/>
						</td>
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][8])?"visible":"invisible"?>
						<td id="point8" class="<?php echo  $strclass?>" >
							<xx></xx><?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],8); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[8]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?><br/>
							<yy></yy><input type='text' class='soldier' id='levelSolider' name='level[8]' value='<?php echo $arrBS['Level'];?>'/>
						</td>
					</tr>
				</table>
			</td>
			<td width="200px">
			<div id='div-battle-award-<?php echo $rowbattle->ID;?>'>				
				<a href='javascript:addAward(<?php echo $rowbattle->ID?>)' class='ico-16 add' ></a><br>
				<?php foreach ($this->arraward[$rowbattle->ID] as $key=>$row){?>
					<div class="award-<?php echo $rowbattle->ID?>" id="div-list-award-<?php echo $key ?>">
					<select id='<?php echo $row->ID?>' name='AwardTypeID[]' onChange='updateAward(this)'>
						<?php if (empty($row->AwardTypeID)){?>
							<option $strSelect value="" style="color:red"></option>
						<?php } ?>	
						<?php echo $this->options($this->arrawardtype,$row->AwardTypeID,array('key'=>'AwardTypeID','name'=>'Name'))?>
						<option  value="insert" style="color:red">New Type</option>
					</select>					
					<input type='text' class='soldier' id='Value' name='Value[]' value='<?php echo $row->Value?>'/>
					
					<a class='tool-16 delete' href='javascript:removeAward(<?php echo $rowbattle->ID.",".$key?>)'>&nbsp</a>	
					</div>
				<?php }?>
			</div>
			</td>
			<td class="center">
			<a class='tool-24 save' id="" href='javascript:saveBattle(<?php echo $rowbattle->ID ?>)'></a><br><br>
			<a class='tool-24 reset' href='javascript:resetBattle(<?php echo $rowbattle->ID ?>)'></a><br><br>
			<a class='tool-24 delete' id="" href='javascript:deleteBattle(<?php echo $rowbattle->ID ?>)'></a>
			</td>
		</tr>
		</tbody>	
		<?php }?>
	
	</table>
	<div class="style" style="margin:20px">
		<a class="btn add" href="javascript:addBattle()">New A Battle</a>	
		<a class="btn save" href="javascript:saveAll()">Save All</a>

	</div>
</div>
</form>
<!-- Dung de them 1 award -->
<div style="display: none">
	<div id="optionAwardType">
		<option selected value="" style="color:red"></option>
		<?php echo $this->options($this->arrawardtype,0,array('key'=>'AwardTypeID','name'=>'Name'))?>	
		<option  value="insert" style="color:red"> New Type</option>		
	</div>
</div>
<!--  -->
<!-- Dialog Dung de Show loi~-->
<div id='dialog'>
	<div id='ct'></div>
	<div id='ft'> </div>
</div>
<!--  -->

<!-- Dialog Them AwardType~-->
<div style='display:none' id='insert-awardtype'>	
	<input class='msg' type="text" id="awardtype" name="awardtype" value="AwardType" />
	
</div>
<!--  -->

<!-- Dialog Them Layout-->
<div style='display:none'  id='insert-layout'>
	<table>
		<tr>
			<td>1<input type="checkbox" name="point" value="0" /></td>
			<td>4<input type="checkbox" name="point" value="3" /></td>
			<td>7<input type="checkbox" name="point" value="6" /></td>
		</tr>
		<tr>
			<td>2<input type="checkbox" name="point" value="1" /></td>
			<td>5<input type="checkbox" name="point" value="4" /></td>
			<td>8<input type="checkbox" name="point" value="7" /></td>
		</tr>
		<tr>
			<td>3<input type="checkbox" name="point" value="2" /></td>
			<td>6<input type="checkbox" name="point" value="5" /></td>
			<td>9<input type="checkbox" name="point" value="8" /></td>
		</tr>
	</table>
</div>
<!--  -->
<script>
///////////////ThaoNX/////////////////////
	////////////////////////////////
	function addAward(key)
	{		
		var count = $(".award-"+ key).size();
		var options = $("#optionAwardType").html();
		var input = " <input type='text' class='soldier' id='Value' name='Value[]' value=''/>";
		var btnDelete = " <a class='tool-16 delete' href='javascript:removeAward("+key+","+count+")'>&nbsp</a>"	;
		var select = "<div class='award-"+key+"' id='div-list-award-"+count+"'><select name='AwardTypeID[]' onChange='updateAward(this)' >"+options+"</select>"+input+btnDelete+"</div>";
		$("#div-battle-award-"+key).append(select);
	}
	/////////////////////////////
	function removeAward(battleID,key)
	{
		$("#div-battle-award-"+battleID+ " #div-list-award-"+key).html("");
	}
	/////////////////////////
	function saveAward(key)
	{
		var data = $("#div-battle-award-"+key+" *").serialize();
		data += "&Action=update-all&BattleID="+key+"";
		$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/campaign/campaign/updateaward'?> ",
			data: data,
			success: function(msg){
				if(msg == '1'){					
					alert("Successfull");
				}else{
					alert("Error");					
				}
				window.location.reload();
			}
		});
	}
	////////////////////////////////
	function saveBattle(key)
	{
		var data = $("#battle-"+key+" *").serialize();
		var camID = $("#campaignID").val();
		data += "&campaignID="+camID;
		
		$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/campaign/battle/save'?> ",
			data: data,
			success: function(msg){				
				if(msg == '1'){					
					alert("Successfull");
				}else{
					alert(msg);					
				}				
			}
		});		
	}
	///////////////////////////////
	function deleteBattle(key)
	{	
		if(!confirm("Delete Battle ID: "+key)){
			return false;
		}
		$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/campaign/battle/delete'?> ",
			data: {
				BattleID:key
			},
			success: function(msg){				
				if(msg == '1'){					
					alert("Successfull");
					$("#battle-"+key+" *").remove();
				}else{
					alert("Error");					
				}
				
			}
		});
	}
	function resetBattle(key){
		if(!confirm("Reset???")){
			return false;
		}
		$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/campaign/battle/getinfo'?> ",
			data: {
				BattleID:key
			},
			success: function(msg){				
				alert(msg);
			}
		});
	}
	///Save All////
	function saveAll(){
		$("#dialog #ct").html("");
		var camID = $("#campaignID").val();
		var name = $("#Name").val();		
		$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/test/testpost'?> ",
			data: {
				ID:camID,
				Name:name,				
			},
			success: function(msg){	
				$("#dialog #ct").append("<p class='msg'>"+msg+"<p>");
				$(".battle").each(function(index){			
						data = ($(this).find("*").serialize());						
						data += "&campaignID="+camID;		
						$.ajax({
							type: "POST",
							url: "<?php echo $this->baseUrl.'/campaign/battle/save'?> ",
							data: data,
							success: function(msg){				
								if(msg == '1'){					
									$("#dialog #ct").append("<p class='msg'>Successful<p>");
								}else{
									$("#dialog #ct").append("<p class='error'>"+msg+"<p>");					
								}					
							}
						});
				});		
			}		
			
		});	
		$("#dialog").dialog({
				title: "Updating",
				height: 400,
				width: 350,
				modal: true,
				buttons: {
					"Continue": function() {								
						$(this).dialog("close");						
					},
					"Refresh": function() {								
						$(this).dialog("close");
						window.location.reload();	
					}	
				}
		});
	}
	///Add battle///
	function addBattle()
	{
		var camID = $("#campaignID").val();
		var data = "campaignID="+camID;
		$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/campaign/battle/add' ?> ",
			data: data,
			success: function(msg){	
				alert ("Thành công");	
				window.location.reload();
			}
		});
	}
	
///////////////End-ThaoNX/////////////////////
	////////////////////////////
	function updateAward(element)
	{
		var selected = element.value;	
		if(selected == "insert"){
			$("#insert-awardtype").dialog({
				title: "New AwardType",
				height: 160,
				width: 200,
				modal: true,
				buttons: {
					"Save": function() {
						var award = $('#awardtype').val();
						$.ajax({
							type: "POST",
							url: "<?php echo $this->baseUrl.'/campaign/AwardType/insert' ?> ",
							data: "award=" + award,
							dataType: "json",
							success: function(smg){	
								//smg là json có giá trị là awart_type lớn nhất.
								alert('Thành Công');							
							}
						});	
						$(this).dialog("close");				
					}											
				}
			});		
		}
	}
	///////////////////////////
	$(document).ready(function(){			
			//$("td.invisible").addClass('an');
			$("td.invisible").find("select").attr('disabled','disabled');
			$("td.invisible").find("input").attr('disabled',true);
			//$("td.visible").addClass('hien');
			
			////////////////ThaoNX/////////////////////
			$(".tool-24.disabled").click(function(){
				//alert("disabled");				
				//return false;
			});		
	});
	////////////Layout////////
	$('select#Layout').change(function(){
		var select=$(this).children("option:selected").val();
		var battleID=$(this).parent().parent().find("#BattleID").val();			
		var layoutID=$(this).val();		
		if(layoutID=="insert"){
			$("#insert-layout").dialog({
				title: "New Layout",
				height: 200,
				width: 200,
				modal: true,
				buttons: {
					"Save": function() {
						alert("Chức năng chưa thực hiện xong");
						$(this).dialog("close");						
					}										
				}
			});
			return false;
		}	
			$.ajax({
				type: "POST",
				url: "<?php echo $this->baseUrl.'/campaign/campaign/loadlayout'?> ",
				data: "id=" + layoutID,
				dataType: "json",
				success: function(data){				
					$.each(data, function(key, val) {
						if(val==0){								
							$("#battle-"+battleID +" #"+key).removeClass("visible").addClass("invisible");
							$("#battle-"+battleID +" #"+key).find("select").attr('disabled',true);
							$("#battle-"+battleID +" #"+key).find("input").attr('disabled',true).val('');
						}else{
							$("#battle-"+battleID +" #"+key).removeClass("invisible").addClass("visible");
							$("#battle-"+battleID +" #"+key).find("select").attr('disabled',false);
							$("#battle-"+battleID +" #"+key).find("input").attr('disabled',false);							
						}
					 
					   // $("#battle-"+s+ "#tb_layout td"+key).val(val); 
					});											
				}
			});
		});
	//////Onchange cho campaignID///////
	 $(document).ready(function(){
		 	$('#campaignID').change(function(){
			 	var campaignID=$(this).val();
			 	var url = "<?php echo $this->baseUrl.'/campaign/campaign/edit/id/'?>"+campaignID;
			 	$(location).attr('href',url);			 

			 	});		 	
		 });
	///////Validate cho du lieu////
		function validate()
		{
			var flag=true;
		}
</script>