<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>
<form id ="form" action="" method="post">

<div id="box">
	<h3>Campaign Manager</h3>
	<table class="filter">
		<tr>
			
			<td>Campaign ID : <input style="width:110px;" type="text" name="ID" id="ID" class="searchbox" /></td>
			<td><input type="submit" name="search" id="button1" class="search" value="search" /></td>
		</tr>
		
		<tr>
			
			<td>ID : <input type="text" name="ID1" disabled="disabled" id="ID1" style="width:110px;" /></td>
			
			<td>Name : <input type="text" name="desc1" id="desc1" /></td>
			
			<td>WorldMap : <?php 
			$mdWm = new Models_WorldMap();
			$data2 = $mdWm->fetchall(); 
			$strList .= "<select id='select1' name='select1' >";
			$strList.="<option ></option>";
			foreach ($data2 as $row1)
			{
	
						$strList.="<option>$row1->Name</option>";
			}
			$strList.="
			
			</select>"; echo $strList;?>
			</td>
			<td><input type="submit" name="update" id="button1" class="update" value="Update" style="width:100px;" /></td>
			<td><input type="submit" name="cancel" id="button2" class="cancel" value="Cancel" style="width:100px;" /></td>
			<td><input type="submit" name="add" id="button3" class="add" value="Add"  style="width:100px;" /></td>
		</tr>
	</table>
	<table>	
		<tr>
			<table>
				<thead>
				<th width="40"><a href="#">STT</a></th>
				<th width="40"><a href="#">ID</a></th>
				<th>Tên</th>
				<th width>World Map</th>							
				<th width="80">Thao tác</th>
				</thead>
				<tr>
					<?php $this->listCamp($this->data, $this->page, $this->items, $this) ?>
				</tr>				
			</table>
		</tr>
		
			<div align="center">
				<input id="button4" type="submit" value="Lưu" style="width:100px;">
				
			</div>
	
	</table>
	<?php echo $this->pagingControl($this->items, $this->page, $this->totalRecord, $this) ?>
</div>
</form>
<script type="text/javascript">
function changeMap(id){
	var desc2 = document.getElementById('nextquest-'+id).value;
	$.ajax({
		type: "POST",
		url:"<?php echo $this->baseUrl.'/campaign/campaign/updateworldmap'?> ",
		data: "id=" + id +"&desc2="+ desc2,	
		success: function(data){
			alert(data)			
			if(data != ""){	
			alert('Thay đổi  thành công');				
				location.reload();
			}else{
				alert(data);				
			}
			
		}
	});

}
$(function(){
	$(".search").click(function(){
		searchbox=document.getElementById('ID').value;
		if(searchbox=='')
		{
		
				return false;
		}
		});
});
$(function(){
	/// sua mot QTC
	
	$(".update").click(function(){
		id = document.getElementById('ID1').value;	
		select1 =  document.getElementById('select1').value;
		desc1 = document.getElementById('desc1').value;
		if(id==''){
			return false;
		}
		$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/campaign/campaign/update/'?> ",
			data: {
				id: id,
				select: select1,
				desc: desc1
			},
			success: function(msg){
				if(msg != "")
				{					
					alert(msg);
				}
				else
				{
					alert("Thêm  không thành công");
					
				}
				window.location.reload();
			}
		});
		return false;	
	});

	////Them 1 quest line
	$(".add").click(function(){				
		desc1 = document.getElementById('desc1').value;
		select = document.getElementById('select1').value;
		if(desc1==''){
			return false;
		}
		$.ajax({
			type: "POST",
			url:"<?php echo $this->baseUrl.'/campaign/campaign/add/'?> ",
			data: {
				select: select,
				decs: desc1
			},
			success: function(msg){
				if(msg != "")
				{					
					alert(msg);
				}
				else
				{
					alert("Thêm  không thành công");
					
				}
				window.location.reload();
			}
		});
		return false;	
	});

});


</script>