<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>
<script type="text/javascript" src="<?php echo $this->baseUrl ?>/media/scripts/jQueryBubblePopup/jquery.bubblepopup.v2.3.1.min.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl ?>/media/scripts/jQueryBubblePopup/jquery.bubblepopup.v2.3.1.css" />
<div id="box">
	<h3 id="adduser">Sự kiện Nam Thiên Đệ Nhất Ỉn</h3>
	<form id="form" action="" method="post">
		<input type="hidden" name="hidSync" id="hidSync"/>	
		<input type="hidden" name="hidLocation" id="hidLocation"/>
	  <fieldset id="buykiss">
		  <legend>Mua nụ hôn &nbsp;&nbsp;<a title="Thêm mốc" href="javascript:addKiss()"><img style="vertical-align: middle" src="<?php echo $this->baseUrl ?>/media/images/icons/add.png"/></a></legend>  	  
		  <?php $this->listNamThienBuyKiss($this->arrBuyKiss,$this) ?>
		  <div id="endBuyKiss"></div>
	  </fieldset>
	<fieldset id="quest">
		<legend>Nhiệm vụ &nbsp;&nbsp;<a title="Thêm mốc" href="javascript:addQuest()"><img style="vertical-align: middle" src="<?php echo $this->baseUrl ?>/media/images/icons/add.png"/></a></legend>		
		<?php $this->listNamThienQuest($this->arrQuest,$this) ?>
		<div id="endQuest"></div>		
	 </fieldset>
	<fieldset id="hitpig">
		<legend>Đập heo đất &nbsp;&nbsp;<a title="Thêm mốc" href="javascript:addHitPig()"><img style="vertical-align: middle" src="<?php echo $this->baseUrl ?>/media/images/icons/add.png"/></a></legend>		
		<?php $this->listNamThienHitPig($this->arrHitPig,$this) ?>
		<div id="endHitPig"></div>		
	 </fieldset>
	<fieldset id="speacialgift">
		<legend>Hộp quà đặc biệt</legend>
		<label for="gift" style="width: 122px">Số Kim Ỉn Lệnh rơi ra : </label> 
		<input name="txtGiftCard" value="<?php echo $this->obj->special_gift ?>" id="txtGiftCard" type="text" tabindex="1" />		
		<br />		
	  </fieldset>
	  <div align="center">
	  <input id="button1" type="submit" value="Lưu" /> &nbsp;&nbsp; 	  
	  <input id="button2" class="btnSync" type="button" value="Sync" /> 
	  </div>
	</form>
</div>
<script type="text/javascript">
	function addKiss()
	{
		var count = $("a[name*='akiss_']").length;	
		$("#endBuyKiss").before('<div id="dv_akiss_'+ count +'">Mua <input type="text" name="txtKiss[]" style="width: 30px"/> nụ hôn được <input type="text" name="txtKissCard[]" style="width: 30px"/> Kim Ỉn Lệnh&nbsp;&nbsp;&nbsp;&nbsp;<a name="akiss_'+  count +'" onclick="deleteOption(this)" title="Xóa" href="javascript:;"><img src="<?php echo $this->baseUrl ?>/media/images/icons/delete.gif" /></a></div>');
	}
	
	function deleteOption(self)
	{
		var name = self.name;
		$("div#dv_" + name).remove();
	}
	
	function addQuest()
	{
		var count = $("a[name*='aquest_']").length;	
		$("#endQuest").before('<div id="dv_aquest_'+ count +'">Hoàn thành nhiệm vụ thứ <input type="text" name="txtQuest[]" style="width: 30px"/> thu được <input type="text" name="txtQuestCard[]" style="width: 30px"/> Kim Ỉn Lệnh&nbsp;&nbsp;&nbsp;&nbsp;<a name="aquest_'+  count +'" onclick="deleteOption(this)" title="Xóa" href="javascript:;"><img src="<?php echo $this->baseUrl ?>/media/images/icons/delete.gif" /></a></div>');
	}
	
	function addHitPig()
	{
		var count = $("a[name*='ahitpig_']").length;	
		$("#endHitPig").before('<div id="dv_ahitpig_'+ count +'">Đập heo đất lần thứ <input type="text" name="txtHit[]" style="width: 30px"/> thu được <input type="text" name="txtHitPigCard[]" style="width: 30px"/> Kim Ỉn Lệnh&nbsp;&nbsp;&nbsp;&nbsp;<a name="ahitpig_'+  count +'" onclick="deleteOption(this)" title="Xóa" href="javascript:;"><img src="<?php echo $this->baseUrl ?>/media/images/icons/delete.gif" /></a></div>');
	}
	
	function syncData()
	{
		if($("#rdDev").is(":checked"))
			$("#hidLocation").val($("#rdDev").val());
		else
			$("#hidLocation").val($("#rdLive").val());
		
		if(confirm("Bạn có chắc thực hiện sync dữ liệu với các server không?") == true)
		{
			$("#hidSync").val(1);
			$("#form").submit();
		}	
	}
	
	$(function(){		
		$('.btnSync').CreateBubblePopup({
													align: 'right',
													
													innerHtml: 'Click to sync data', 
													innerHtmlStyle: {
																		color:'#FFFFFF', 
																		'text-align':'center'
																	},
																	
													themeName: 	'all-black',
													themePath: 	'<?php echo $this->baseUrl ?>/media/scripts/jQueryBubblePopup/jquerybubblepopup-theme'
											   });
		
		$('.btnSync').click(function(){		
			var btn = $(this);

			// show a bubble popup with new options when "this" shoppingcart button is clicked
			btn.ShowBubblePopup({

													align: 'center',
													innerHtml: '<p id="errorpop" style="color:red"></p>'+
																'<p><input id="rdDev" checked name="rdLocation" value="<?php echo DEV ?>" type="radio"/> <span style="color:blue;font-weight:bold">DEV</span>&nbsp;&nbsp;&nbsp;&nbsp;<input id="rdLive" name="rdLocation" type="radio" value="<?php echo LIVE ?>"/> <span style="color:red;font-weight:bold;">LIVE</span></p>' + 
															   '<p><input type="button" onclick="syncData()" id="btnOk" value="Đồng ý"/>&nbsp;&nbsp;<input type="button" id="btnClose" value="Hủy"/></p>',

													innerHtmlStyle:{ 
																	color:'#666666', 
																	'text-align':'left'
																   },

													themeName: 	'azure',
													themePath: 	'<?php echo $this->baseUrl ?>/media/scripts/jQueryBubblePopup/jquerybubblepopup-theme'

												}, false); //save_options = false; it will use new options only on click event, it does not overwrite old options.


			// "freeze" the Bubble Popup then it will not respond to mouse events (as mouseover/mouseout) 
			// until ".ShowBubblePopup()" or ".HideBubblePopup()" is called again.
			btn.FreezeBubblePopup(); 

			// when the "close" link is clicked, hide the bubble popup
			$('#btnClose').click(function(){
				$(btn).HideBubblePopup();
			});
		});//end onclick event
	});
</script>