<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>
<style>
	table tr{
		border:1px #CCC solid; 
	}

#response {
	padding:10px;
	background-color:#9F9;
	border:2px solid #396;
	margin-bottom:20px;
}
#list ul{
	width:100%;
	margin-top:30px;
}
#list li {
	width:auto;
	margin: 0 5px 3px;
	padding:8px;
	background-color:#333;
	color:#fff;
	list-style: none;
	display:inline;
}
#list li a{
	color:#fff;
}
.clear{
	clear:both;
}


</style>

</script>
<form  class="myform" id="formPaging" name="formPaging" action="" method="post">

<div class="mybox">
	<h3>Quest</h3>
	<table class="filter">
		<tr>			
			<td><label>Search</label><input type="text" name='ID' id='ID'/>
			<input type="submit" value='Search' name='search'/></td>
			<td><a class="btn add" href="<?php echo $this->baseUrl;?>/shop/ibshop/new">Add</a></td> 
		</tr>
		
	</table>
	<table style="margin-top:10px;">
	<tr>		
		
		 <div id="list">	
   		 <div id="response"> </div>
   		 	<ul>
      			<?php foreach ($this->dataindex as $row){?>
     			<li id="arrayorder_<?php echo $row['ID']?>>"><a href="javascript:void(0)" ><?php echo $row['Name']?></a>
       
      			</li>
      			<?php }?>
   		 </ul>
			
		</tr>
	</table>
	<table class="filter">
	<thead>	
		<tr style="border: 1px;">						
			<td>TabName</td>
			<td>Items</td>
			<td>Tool</td>			
		</tr>
	</thead>
	<tbody>
		<?php $this->listIbShop($this->data, $this->page, $this->items, $this) ?>	
	</tbody>
	</table>
	
<?php echo $this->pagingControl($this->items, $this->page, $this->totalRecord, $this)?>
	<br>
		<center><input type="submit" name="button1" id = "button1" style="width:100px"  value="Save"/></center>
</div>
</form>
<script>
	function deleteIbShop(key)
	{
		if(confirm('Bạn có muốn xóa Item Shop này không'))
		{
			$.ajax({
				type: "POST",
				url:"<?php echo $this->baseUrl.'/shop/ibshop/delete/'?> ",
				data: "id="+key,			
				success: function(data){					
					alert('Xóa thành công');
					window.location.reload();			
				}
			});
		}
	}
</script>
<script type="text/javascript">
$(document).ready(function(){ 	
	function slideout(){
  		setTimeout(function(){
  			$("#response").slideDown("slow", function () {
      		});
		}, 3000);
	}
	
    $("#response").hide();
	$(function() {
		$("#list ul").sortable({ opacity: 0.8, cursor: 'move', update: function() {
			var order = $(this).sortable("serialize") ; 
			$.post("<?php echo $this->baseUrl.'/shop/ibshop/updatetabindex/'?>", order, function(theResponse){
				$("#response").html(theResponse);
				$("#response").slideDown('slow');
				
				slideout();
							
			}); 															 
		}								  
		});
	});
});	
</script>