<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>
<style>
#language table #checkbox
{
	width : 22px;
}
#language table #id
{
	width : 22px;
}
#language table #group
{
	width : 60px;
}
#language table #key
{
	width : 60px;
}
#language table #text
{
	width : 310px;
}
#language table #name
{
	width : 100px;
}
/************************/
#language table div.text
{
	text-align:center;
}
#language table div#ldefault 
{
	float: left;
	width: 48%;
}
#language table div#lindex 
{
	float: right;
	width: 48%;
}
#language table div#lcopy 
{
	float: left;
	margin-top: 36px;
	width: 4%;
}
#language table textarea
{
	height : 80px;
	width:100%;
}

td.ldefault textarea,td.lindex textarea
{
	width:100% !important;
	border: 2px solid lightBlue;
}
#language table input[name="lkey"]
{
	margin-left: 6px;
	margin-bottom: 5px;
}

#language table input[name="searchbox"]
{
	width : 200px;
}
#language table select[name="lgroup"]
{
	width : 200px;
}
#language table select[name="searchtype"]
{	
	width: 100px;
}
#language table tr.alt{
	background:#EAF2D3;
}


#language table tfoot{padding: 5px;text-align: center;height: 30px;color:black}
#language table tfoot a.current{
	border: 2px solid lightBlue;
}
#language table tfoot a{margin: 3px;padding: 3px;border: 1px solid #ddd;overflow: hidden;}
#language table tfoot a:hover{background: #f4f4f4;}
</style>
<form id="language" class="myform" action="<?php echo $this->baseUrl."/localite/string2/index"; ?>" name="language" method="post">
<div id="box">
	<h3>String Manager
	<select name="l_language" onChange="changeLang(this)">
			<?php echo $this->options($this->arr_lang,$this->index_lang->id,array('key'=>'id','name'=>'name'))?>
	</select>
	</h3>
	<table class="" >		
		<tr>
		<td>
			Group :
			<select name="lgroup" onChange="changeGroup(this)">					
				<option value="">Tất cả</option>
				<?php echo $this->options($this->arr_group,$this->item->lgroup,array('key'=>'id','name'=>'name'))?>
			</select>
			<div class="loading" style="display:inline;"></div>	
		</td>
		
			<td>
			
				<em>Find :</em> <input style="" type="text" name="searchbox" id="searchbox" class="searchbox" value="<?php echo $this->searchbox?>"/>
				<em>Search by :</em>
				<select name="searchtype" style=" width = 100px">
					<?php 
						if($this->searchtype == 'skey')
							echo '<option value="skey">Key</option><option value="stext">Text</option>';
						else 
							echo '<option value="stext">Text</option><option value="skey">Key</option>';
					?>
				</select>				
				<input class="btn search" type="submit" name="search" value="search" />
				
			</td>		
		</tr>
		<tr>
			<td>
							
			</td>
		</tr>
		<tr>
			<td  colspan="2">
				<div>
					<input name="lkey" type="text" value="<?php echo $this->max_key?>"></input>
					<a id="btn_add_string" class="tool-24 add" href="" ></a>&nbsp;&nbsp;
					<a id="btn_reset_text" class="tool-24 reset" href="javascript:void(0)" ></a>
				</div>
				<div class="text">
					<div id="ldefault" ><textarea name="ldefault" value="" ><?php echo $this->item->ldefault?></textarea></div>
					<div id="lcopy"><a title="Ctr+D" id="btn_copy" tabindex="1" class="tool-24 copy"></a></div>					
					<div id="lindex"><textarea name="lindex" value=""><?php echo $this->item->lindex?></textarea></div>
				</div>
			</td>
		</tr>
	</table>
	<table class="list" id="tbLocalize">	
		<thead>
			<tr>			
				<td style="width:10px;"><input type="checkbox" name="checkall" value="checkall" onclick="checkAll(this)"/></td>
				<td style="width:50px;"> <a href="#">ID</a></td>
				<td style="width:200px;">Group</td>
				<td style="width:30px;">Key</td>
				<td style="width:30%;">Default Language</td>
				<td style="width:30%;">Index Language: <?php echo $this->index_lang->name?></td>
				<td  style="width:10%;" class="center" >Action</td>
			</tr>
		</thead> 	
		<tbody>	
		<tr id="first"></tr>	
		<?php
		if(!empty($this->arr_string)){
				$alt = "alt";
			foreach($this->arr_string as $key=>$row){
				$alt = ($alt=="alt"?"":"alt");
						
		?>
			<tr id="tr-<?php echo $row->id?>" class="<?php echo $alt;?>">	
				<td><input type="checkbox" name="check" value="" /></td>
				<td><?php echo $row->id?></td>
				<td class="lgroup"><?php echo $row->gname?></td>
				<td class="lkey"><?php echo $row->lkey?></td>
				<td class="ldefault"><p><?php echo $row->ldefault?></p></td>
				<td class="lindex"><p><?php echo $row->lindex?></p></td>
				<td class="center" style="">
					<a id="btn_edit_string" class="tool-24 edit" href="#"></a>&nbsp;
					<a id="btn_del_string" class="tool-24 delete"  href="#" title="<?php echo $row->id.','.$row->gid.','.$row->lkey ?>"></a>					
				</td>
			</tr>
			
		<?php }?>
		<?php }?>
		
		
		</tbody>			
		<tfoot>
		<td colspan="7" id="pagging">
				<?php 
				
				for ($i = 0; $i < $this->num; $i++) {
					$class= '';
					
					if(($i+1)==$this->page) 
						$class = 'current';
					echo '<a class="'.$class.'" href="'.$this->baseUrl.'/localite/string2/index?page='.($i+1).'">'.($i+1).'</a>';
				}				
				?>
				</td>	
		</tfoot>
	</table>

	<div style="margin-top:20px;margin-bottom:20px">
		<a id="btn_del_select" class="btn add" href="#">Delete</a>
	</div>
</div>	
</form>
<script type="text/javascript">
//local var
var ACTION = "";
function showLoading(key){
	var loading = $("div.loading");
	if(key == 1){		
		var loading_str = ('<a class="ico-16 loading">&nbsp</a>');
		loading.html(loading_str);	
	}else if(key==0){
		loading.html("");	
	}
	
}
function changeLang(e){
	$("#language").submit();
}

function changeGroup(e){
	var lgroup = e.value;	
	showLoading(1);
	$.ajax({
		type: "POST",
		url: "<?php echo $this->baseUrl.'/localite/string2/index' ?>",		
		data: {
			action: "ajax",
			//lindex: txt_index,
			lgroup: lgroup,
			//lkey: lkey
		},
		dataType: "json",
		success: function(arrObj){
			//alert(arrObj);return;
			var maxkey = 0;
			if(arrObj.data != null && arrObj.data.length!=0){	
				maxkey = parseInt(arrObj.data[0].lkey);
			}else{
				
			}
			updateTable("load",arrObj);
			$("form#language input[name='lkey']").val(maxkey+1);
			showLoading(0);			
		}			
	});	
	
}
function checkAll(e){	
	$("input:checkbox[name='check']").attr("checked",e.checked);
}
function updateTable(action,obj){
	if(action=="insert"){
		//updateSTT();
		var first_tr 	= $("#tbLocalize").find("tbody tr").eq(0);			
		var alt 		= first_tr.hasClass("alt")?"":"alt";		
		var lgroup_name = $("select[name='lgroup'] option:selected").text();
		console.log(obj.ldefault);		
		var str_tr 		= '<tr id="tr-'+obj.id+'" class="'+alt+'">'+
			'<td><input type="checkbox" name="check" value="checkall" /></td>'+
			'<td>'+obj.id+'</td>'+
			'<td class="lgroup">'+lgroup_name+'</td>'+
			'<td class="lkey">'+obj.lkey+'</td>'+
			'<td class="ldefault"><p>'+obj.ldefault+'</p></td>'+
			'<td class="lindex"><p>'+obj.lindex+'</p></td>'+
			'<td class="center">'+
				'<a id="btn_edit_string" class="tool-24 edit" href="#"></a>&nbsp;'+
				'<a id="btn_del_string" class="tool-24 delete" href="#" title="'+obj.id+','+obj.lgroup+','+obj.lkey+'"></a></td>'+
			'</tr>';					
		first_tr.before(str_tr);		
	}else if(action=="load"){		
		var tbody = $("#tbLocalize").find("tbody");	
		tbody.html('<tr id="first"></tr>');
		var alt = "";
		var count = obj.num;
		var pagging = $("#tbLocalize tfoot td#pagging");
		pagging.html("");
		for(var i=0;i<count;i++){
			var link = "<?php echo $this->baseUrl.'/localite/string2/index?page=' ?>";			
			var cls = '';
			if(i==0)
				cls = 'current';				
			pagging.append('<a class="'+cls+'" href="'+link+(i+1)+'">'+(i+1)+'</a>');
		}
		$.each(obj.data,function(key,val){
			alt = (alt=="alt")?"":"alt";
			var str_tr = '<tr id="tr-'+val.id+'" class="'+alt+'">'+
			'<td><input type="checkbox" name="check" value="checkall" /></td>'+
			'<td>'+val.id+'</td>'+
			'<td class="lgroup">'+val.gname+ '<span class="gid" style="display:none">'+val.gid+'</span></td>'+
			'<td>'+val.lkey+'</td>'+
			'<td class="ldefault"><p>'+val.ldefault+'</p></td>'+
			'<td class="lindex"><p>'+val.lindex+'</p></td>'+
			'<td class="center">'+
				'<a id="btn_edit_string" class="tool-24 edit" href="#"></a>&nbsp;'+
				'<a id="btn_del_string" class="tool-24 delete" href="#" title="'+val.id+','+val.gid+','+val.lkey+'"></a></td>'+
			'</tr>';
			tbody.append(str_tr);
		});
	}
}

function updateSTT(){
	var arr_tr = $("#tbLocalize").find("tbody tr");
	arr_tr.each(function(index){
		$(this).find("td").eq(0).text(index+1);
	});
}
var ctrlDown  = false;
$(document).keydown(function(e){	
	if (e.keyCode == 17) ctrlDown = true;
}).keyup(function(e){	
	if (e.keyCode == 17) ctrlDown = false;
});

$("textarea[name='ldefault']").keydown(function(e){	
	if(e.ctrlKey==true && e.keyCode==68){
		$("a#btn_copy").click();
		return false;
	}
});

$("a#btn_copy").click(function(){
	var txt_default = $("textarea[name='ldefault']").val();
	$("textarea[name='lindex']").val(txt_default);
});
$("form#language").delegate("a#btn_del_string","click",function(){
	
	if(ACTION == "DEL_SELECTED"){
		
	}else if(!confirm("Delete string????")){
		return false;
	}
	$(this).removeClass("delete").addClass("loading");
	var title = $(this).attr("title");
	var arr_param = title.split(",");
	$.ajax({
		type: "POST",
		url: "<?php echo $this->baseUrl.'/localite/string2/delete' ?>",		
		data: {
			lgroup : arr_param[1],
			lkey: arr_param[2],			
		},		
		success: function(msg){		
			if(msg == "true"){
				$("#tbLocalize #tr-"+arr_param[0]).remove();
				showLoading(0);
			}	
			else
				alert(msg);			
		}			
	});
	return false;	
});

$("form#language").delegate("a#btn_add_string","click",function(){
	var txt_default = $("textarea[name='ldefault']").val();
	var txt_index = $("textarea[name='lindex']").val();
	var lgroup = $("select[name='lgroup']").val();
	var lkey = $("input[name='lkey']").val();
	var lgroup = $("select[name='lgroup']").val();
	showLoading(1);
	if(txt_default==""){
		alert("Please fill all require field");
		return false;
	}
	if(lgroup==""){
		alert("Please select a group");
		return false;
	}		
	$.ajax({
		type: "POST",
		url: "<?php echo $this->baseUrl.'/localite/string2/insert' ?>",		
		data: {
			ldefault: txt_default,
			lindex: txt_index,
			lgroup: lgroup,
			lkey: lkey
		},
		dataType: "json",
		success: function(obj){
			if(obj==null){
				alert("Insert Failed!! Key is exist");
			}else{
				$("form#language input[name='lkey']").val(parseInt(obj.max_key)+1);
				$("textarea[name='ldefault']").val("");
				$("textarea[name='lindex']").val("");
				updateTable("insert",obj);				
			}
			showLoading(0);
		}			
	});
	return false;
});

$("form#language").delegate("a#btn_edit_string","click",function(){
	var parent_tr 	= $(this).parent().parent();
	
	var td_ldefault = parent_tr.find(".ldefault");
	var td_lindex 	= parent_tr.find(".lindex");	
	var btn_edit = parent_tr.find("a.tool-24.edit");
	var btn_delete= parent_tr.find("a.tool-24.delete");
	
	var td_ldefault_p = parent_tr.find(".ldefault p");
	var td_lindex_p 	= parent_tr.find(".lindex p");
	var ldefault = td_ldefault_p.html();
	var lindex = td_lindex_p.html();	
	
	td_ldefault.find("p").hide();
	td_lindex.find("p").hide();
	var text_area = $('<textarea>'+ldefault+'</textarea>');
	
	td_ldefault.append(text_area);	
	td_lindex.append('<textarea>'+lindex+'</textarea>');
	
	text_area.focus();
	btn_edit.removeClass("edit").addClass("reset").attr("id","btn_reset_string");
	btn_delete.removeClass("delete").addClass("save").attr("id","btn_save_string");
	return false;
});

$("form#language").delegate("a#btn_reset_string","click",function(){
	
	var parent_tr 	= $(this).parent().parent();	
	var td_ldefault = parent_tr.find(".ldefault");
	var td_lindex 	= parent_tr.find(".lindex");
	var btn_save = parent_tr.find("a.tool-24.save");
	var btn_reset= parent_tr.find("a.tool-24.reset");
		
	td_ldefault.find("p").show();
	td_ldefault.find("textarea").remove();
	td_lindex.find("p").show();
	td_lindex.find("textarea").remove();
	
	btn_save.removeClass("save").addClass("delete").attr("id","btn_del_string");
	btn_reset.removeClass("reset").addClass("edit").attr("id","btn_edit_string");
	return false;
});

$("form#language").delegate("a#btn_del_select","click",function(){
	$("input:checkbox[name='check']:checked").each(function()
	{
		var btn = $(this).parent().parent().find("a#btn_del_string");
		ACTION = "DEL_SELECTED";
		btn.click();
	});
	ACTION = "	";
	return false;
});

$("form#language").delegate("a#btn_save_string","click",function(){
	
	var parent_tr 	= $(this).parent().parent();	
	var td_ldefault = parent_tr.find(".ldefault");
	var td_lindex 	= parent_tr.find(".lindex");
	var btn_save = parent_tr.find("a.tool-24.save");
	var btn_reset= parent_tr.find("a.tool-24.reset");
	var title = $(this).attr("title");
	var arr_param = title.split(",");	
	//td_ldefault.find("p").show();
	//td_lindex.find("p").show();
	//showLoading(1);
	btn_save.removeClass("save").addClass("loading").attr("id","");
	var ldefault = td_ldefault.find("textarea").val();	
	var lindex = td_lindex.find("textarea").val();	
	//
	//
	$.ajax({
		type: "POST",
		url: "<?php echo $this->baseUrl.'/localite/string2/update' ?>",		
		data: {
			lgroup : arr_param[1],
			lkey: arr_param[2],
			ldefault:ldefault,
			lindex:lindex	
		},		
		success: function(msg){		
			if(msg=="true"){
				td_ldefault.find("p").text(ldefault).show();
				td_lindex.find("p").text(lindex).show();
				td_ldefault.find("textarea").remove();
				td_lindex.find("textarea").remove();
				btn_save.removeClass("loading").addClass("delete").attr("id","btn_del_string");
				btn_reset.removeClass("reset").addClass("edit").attr("id","btn_edit_string");
				showLoading(0);
			}
		}			
	});
	return false;
});
</script>