<form  id="form" class="task_form form-task-<?php echo $this->key1?>">
<em>Template</em><select class='task-template' id="template<?php echo $this->key1;?>" onChange='javascript:loadTemplate(<?php echo $this->key1;?>)'>
<option value =""></option>
<?php 
foreach ($this->arrTemplate as $row) {?>
	<option value ="<?php echo $row->TaskID;?>"><?php echo $row->TaskName;?></option>
<?php } ?>
</select>
<a class="btn add" title=' Add' href='javascript:addTemplate(<?php echo $this->key1?>)'>Add To Template</a>
<a class="btn edit" title=' Edit' href='javascript:editTemplate()'>Edit Template</a><br/>
<input type="checkbox" id="Counter" name ="Counter" value="check">&nbsp;Counter
<table>
	<tr>
		<td>Task ID</td>
		<td><input type="text" id="TaskID" name="TaskID" class="disabled" readonly="readonly" class="taskid" value=""/></td>
		<td>Action (*) </td>
		<td>
		<select id="Action" name="Action">
			<?php 
				foreach($this->arrAction as $row)
				{
					$str="";
					if($val->ActionID == $row->ActionID )
					{
						$str= "selected";
					}
			?>
					<option <?php echo $str;?> value="<?php echo $row->ActionID ?>"><?php echo $row->ActionName ?></option>
			<?php
				}
			?>
		</select>
		</td>
		
	</tr>
	<tr>
		<td>Task Name</td>
		<td><input type="text" id="TaskName" name="TaskName" value=""/></td>
		
		<td>Task String</td>
		<td>
			<input type="text" id="TaskString-<?php echo $this->key1?>" name="TaskString" value="" onchange="getvalue('TaskString-<?php echo $this->key1?>')" title="TaskString-string-value-<?php echo $this->key1?>"/>
			<a title="chon" id="stringadd" class="tool-16 explore" href="JavaScript:void(0);" title = "asds" onClick="findstring('TaskString-<?php echo $this->key1?>','')"></a>
			<a title="them" id="newstring" class="tool-16 add" href="JavaScript:void(0);" title = "asds" onClick="newstring('TaskString-<?php echo $this->key1?>','')"></a>
			<p class="string-value" id = "TaskString-string-value-<?php echo $this->key1?>" ></p>
		</td>
		
	</tr>
	<tr>
		<td>Desc</td>
		<td><input type="text" id="DescString" name="DescString" value="" /></td>		
		<td>DescString</td>
		<td>
			<input type="text" id="DescID-<?php echo $this->key1?>" name="DescID" value="" onchange="getvalue('DescID-<?php echo $this->key1?>')" title="DescID-string-value-<?php echo $this->key1?>"/>
			<a title="chn" id="stringadd" class="tool-16 explore" href="JavaScript:void(0);" title = "asds" onClick="findstring('DescID-<?php echo $this->key1?>','')"></a>
			<a title="thêm" id="newstring" class="tool-16 add" href="JavaScript:void(0);" title = "asds" onClick="newstring('DescID-<?php echo $this->key1?>','')"></a>
			<p class="string-value" id = "DescID-string-value-<?php echo $this->key1?>" ></p>
		</td>
		
	</tr>
	<tr>
		<td>Icon Class Name</td>
		<td><input type="text" id="IconClassName" name="IconClassName" value=""/></td>
		<td>Icon Bucket Name</td>
		<td><input type="text" id="IconPackageName" name="IconPackageName" value=""/></td>		
	</tr>
	<tr> 

		<td>Quantity (*) </td>
		<td><input type="text" id="Quantity" name="Quantity" value=""/></td>	
		
		<!-- 
		<td>
		<INPUT TYPE=RADIO NAME="TargetType" VALUE="" CHECKED> Target Type<BR>
		<INPUT TYPE=RADIO NAME="TargetType" VALUE="null"> Target List<BR>
		</td>
		--><td>UnlockCoin (*) </td>
		<td><input type="text" id="UnlockCoin" name="UnlockCoin" value=""/></td>
	</tr>
	<tr>		
		<td>Target(*)</td>
		<td id="target">
			<input checked type="radio" id="Type"  name="Target"  value="TargetType"> Type<input  id="TargetType" style="margin-left: 10px;width: 153px;" type="text" name="TargetType" value=""> <br>
			<div id='target-list-<?php echo $this->key1;?>'>
				<input type="radio" id="List" name="Target" value="TargetList"> List <a  class="ico-16 add add-target" href="javascript:addTarget(<?php echo $this->key1?>)"></a><br>
				<div class='list'>
				</div>
			</div>
		</td>
		<td>Quest Task Client</td>
		<!-- ////////////////Hien Quest Task Client vao commbobox/////////////////// -->
		
		<td>
		<select id="QuestTC" name="QuestTC">
			
			<?php 
				foreach($this->arrQuestTC as $row)
				{
					$str="";
					if($val->QTC_ID == $row->QTC_ID )
					{
						$str= "selected";
					}
			?>
					<option <?php echo $str;?> value="<?php echo $row->QTC_ID ?>"><?php echo $row->QTC_Name ?></option>
			<?php
				}
			?>
		</select>
		</td>	
	</tr>
	<tr>		
</tr>
</table>
</form>

