<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>
<table>
	<tr>
		<td>Task ID</td>
		<td><input type="text" id="TaskID" name="TaskID[]" class="disabled" readonly="readonly" class="taskid" value="<?php echo $this->obj->TaskID?>"/></td>
		<td>Task Name</td>
		<td><input type="text" id="TaskName" name="TaskName[]" value=""/></td>
		
	</tr>
	<tr>
		<td>Task String</td>
		<td><input type="text" id="TaskString" name="TaskString[]" value=""/></td>
		<td>Action (*) </td>
		<td>
		<select id="Action" name="Action[]">
			
			<?php 
				foreach($this->arrAction as $row)
				{
					$str="";
					if($this->obj->ActionID == $row->ActionID )
					{
						$str= "selected";
					}
			?>
					<option selected='<?php echo $str;?>' value="<?php echo $row->ActionID ?>"><?php echo $row->ActionName ?></option>
			<?php
				}
			?>
		</select>
		</td>
	</tr>
	<tr>
		<td>DescID</td>
		<td><input type="text" id="DescID" name="DescID" value=""/></td>
		<td>DescString</td>
		<td><input type="text" id="DescString" name="DescString" value=""/></td>
	</tr>
	<tr>
		<td>Target(*) </td>
		<td><input type="text" id="TargetID" name="TargetID[]" value=""/></td>
		<!-- 
		<td>
		<INPUT TYPE=RADIO NAME="TargetType" VALUE="" CHECKED> Target Type<BR>
		<INPUT TYPE=RADIO NAME="TargetType" VALUE="null"> Target List<BR>
		</td>
		--><td>UnlockCoin (*) </td>
		<td><input type="text" id="UnlockCoin" name="UnlockCoin[]" value="5"/></td>
	</tr>
	<tr>
		<td>Quantity (*) </td>
		<td><input type="text" id="Quantity" name="Quantity[]" value="5"/></td>
		<td>Quest Task Client</td>
		<td><input type="text" id="QTC_ID" name="QTC_ID[]" value=""/></td>
	</tr>
	<tr>
		<td>Icon</td>
		<td colspan="3"></td>
	</tr>
</table>
