<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>
<div>
<table>
	<tr>
		<td>Task ID</td>
		<td><input type="text" id="TaskID" name="TaskID[]" class="taskid" value="<?php echo $this->obj->TaskID?>"/></td>
		<td>Task Name</td>
		<td><input type="text" id="TaskName" name="TaskName[]" value="<?php echo $this->obj->TaskName?>"/></td>
		
	</tr>
	<tr>
		<td>Task String</td>
		<td><input type="text" id="TaskString" name="TaskString[]" value="<?php echo $this->obj->TaskString?>"/></td>
		<td>Action</td>
		<td>
		<select id="Action" name="Action[]">
			<option value="<?php echo $this->obj->ActionID?>"><?php echo $this->objactionname->ActionName?></option>
			<?php 
				foreach($this->arrAction as $row)
				{
			?>
					<option value="<?php echo $row->ActionID ?>"><?php echo $row->ActionName ?></option>
			<?php
				}
			?>
		</select>
		</td>
	</tr>
	<tr>
		<td>Target</td>
		<td><input type="text" id="TargetID" name="TargetID[]" value="<?php echo $this->obj->TargetID?>"/></td>
		<td>UnlockCoin</td>
		<td><input type="text" id="UnlockCoin" name="UnlockCoin[]" value="<?php echo $this->obj->UnlockCoin?>"/></td>
	</tr>
	<tr>
		<td>Quantity</td>
		<td><input type="text" id="Quantity" name="Quantity[]" value="<?php echo $this->obj->Quantity?>"/></td>
		<td>Quest Task Client</td>
		<td><input type="text" id="QTC_ID" name="QTC_ID[]" value="<?php echo $this->obj->QTC_ID?>"/></td>
	</tr>
	<tr>
		<td>Icon</td>
		<td colspan="3"></td>
	</tr>
</table>
</div>
<script>
//$(document).ready(function(){
//		$('.taskid').attr(''
//		});
</script>