<?php
return array(
	'5005' => array(
		'id' => '5005',
		'type' => '8',
		'description' => 'Bao gồm 10 heo ngựa vằn',
		'name' => 'Gói 10 heo ngựa vằn (cái)',
		'haveDefault' => '0',
		'image' => 'PinDai.png',
		'priceInGame' => '0',
		'priceOutGame' => '400',
		'quantity' => '1',
		'status' => '0',
		'currentStatus' => '0',
		'key' => 'ITEM_GIFT_PACKAGE',
		'effect' => array('ITEM_GIFT_PACKAGE'=>'package33'),
		'level' => '0',
		'limited' => '-1',
		'useAtHome' => '0',
		'maxLevel' => '-1',
		'exp' => '0',
		'refineLevel' => '0',
		'expiredCoin' => '0',
		'disCount' => '20',
		'enableInShop' => false,
		'url' => 'http://10.30.9.118/uploadimage/itemgift/PinDai.png',
		'basePriceInGame' => '0',
		'basePriceOutGame' => '500'),
	'5006' => array(
		'id' => '5006',
		'type' => '8',
		'description' => 'Gồm 10 heo hoả tinh đực',
		'name' => 'Gói 10 heo hoả tinh (Đực)',
		'haveDefault' => '0',
		'image' => 'NuHon.png',
		'priceInGame' => '0',
		'priceOutGame' => '300',
		'quantity' => '1',
		'status' => '0',
		'currentStatus' => '0',
		'key' => 'ITEM_GIFT_PACKAGE',
		'effect' => array('ITEM_GIFT_PACKAGE'=>'package34'),
		'level' => '0',
		'limited' => '-1',
		'useAtHome' => '0',
		'maxLevel' => '-1',
		'exp' => '0',
		'refineLevel' => '0',
		'expiredCoin' => '0',
		'disCount' => '25',
		'enableInShop' => true,
		'url' => 'http://10.30.9.118/uploadimage/itemgift/NuHon.png',
		'basePriceInGame' => '0',
		'basePriceOutGame' => '400'),

);
?>