<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

</head>

<body>
<form action="" method="post" enctype="multipart/form-data" name="form1" id="form1">
<hr></hr>
<br></br>
<div>
   <center>
   <label>
    <input type="submit" name="btn" id="btn" value="Export Shop's files " />
  </label>
 </center>
 </div>
 <br></br>
 <hr></hr>
</form>
<fieldset>
</fieldset>
</body>
</html>