<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>

<form id="formPaging" name='formPaging' class="myform" action="" method="post">
<div class="mybox">
	<h3>WORLD MAP EDITOR</h3>
	<table class="filter" style="width: 80%;margin: auto;margin-bottom: 20px;margin-top: 10px";>
		<tr>
			<td>World map ID</td>
			<td><input style="width:110px;" type="text" name="SearchID" id="SearchID" class="searchbox" /></td>
			<td><input type="submit" name="search_Worldmap" class="btn search" id="search_Worldmap" value="search" /></td>
		
		</tr>		
		<tr>
			<td>ID</td>
			<td><input id="WorldmapID" name="WorldmapID" readonly="readonly" type="text" style="width:110px;" /></td>
			<td>Name
			<input id="WorldmapName" type="text" name="WorldmapName"/>
				<a class="btn save disabled " href="">Save</a>
				<a class="btn add disabled " href="">Add</a>
				<a class="btn cancel disabled " href="">Cancel</a>
			</td>
		</tr>
	</table>
	<table class="list" id="list_Worldmap" style="width: 80%;margin:auto ;border: 1px solid;">	
		<thead>
			<tr>									
				<td width="40"><a href="#">ID</a></td>
				<td>Worldmap Name</td>							
				<td class="center" width="80">Action</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<?php $this->ListWorldmap($this->data, $this->page, $this->items, $this) ?>
			</tr>
		</tbody>						
	</table>	
	
	<div align="center" style="margin: 20px;">		
		<input class="btn big sync"  type="submit" value="Sync">
	</div>
</div>
</form>
<script type="text/javascript">
$("a.btn.disabled").click(function(){
	//alert("disabled");
	return false;
});


$(function(){	
////////////////click Cancel//////////////////////////
	$(".btn.cancel").click(function(){
		if($(".btn.cancel").hasClass('disabled')){			
 	 	}else{
 	 		document.getElementById('WorldmapID').value = '';
 	 		document.getElementById('WorldmapName').value = '';
 	 		disable($(".btn.add"));
			disable($(".btn.save"));
			disable($(".btn.cancel"));
 	 	}
 	 	return false;
 	});
	
///////////////////Input Event///////////////////////////
	$("#WorldmapName").keyup(function(e){
		var id = $("#WorldmapID").val();
		var name = $("#WorldmapName").val();
		
		if(name == ''){
			disable($(".btn.add"));
			disable($(".btn.save"));
		}else{	
			enable($(".btn.cancel"));					
			if(id != ''){
				//enable($(".btn.add"));
				enable($(".btn.save"));				
			}else{
				enable($(".btn.add"));
				disable($(".btn.save"));
			}
		}		
	});	
///////////////Save click/////////////////
	$(".btn.save").click(function(){
		if($(this).hasClass("disabled")){
			return false;
		}
		updateWorldmap();			
	});		

	$(".btn.add").click(function(){
		if($(this).hasClass("disabled")){
			return false;
		}
		updateWorldmap();
	});
});

function editWorldmap(key){
	id = $("#Worldmap-"+key+" .id").text();
	name = $("#Worldmap-"+key+" .name").text();
	document.getElementById('WorldmapID').value = id;
	document.getElementById('WorldmapName').value = name;
	if($(".btn.save").hasClass('disabled')){
		$(".btn.save").removeClass("disabled");		
	}
	if($(".btn.cancel").hasClass('disabled')){
		$(".btn.cancel").removeClass("disabled");		
	}
	if(!$(".btn.add").hasClass('disabled')){
		$(".btn.add").addClass("disabled");
	}
}
/*******click delete button***********/
function deleteWorldmap(key){	
	id = $("#Worldmap-"+key+" .id").text();
	name = $("#Worldmap-"+key+" .name").text();
	if(!confirm("Bạn có muốn xóa Worldmap: " + name)){
		return false;
	};
	$.ajax({
		type: "POST",
		url: "<?php echo $this->baseUrl.'/campaign/Worldmap/delete/'?> ",
		data: "ID="+id,
		success: function(msg){				
			if(parseInt(msg)==1){	
				alert('Xóa WolrdMap thành công');										
				window.location.reload();
			}
			else{
				alert(msg);	
				return fasle;	
			}			
		}
	});		
}
function updateWorldmap(){
	var id = $("#WorldmapID").val();
	var name = $("#WorldmapName").val();	
	$.ajax({
		type: "POST",
		url: "<?php echo $this->baseUrl.'/campaign/Worldmap/update/'?> ",
		data: "Name=" +name +"&ID="+id,
		success: function(msg){					
			if(msg != ""){	
				alert(msg);			
				window.location.reload();
			}
			else{
				alert("Update KO thành công");				
			}			
		}
	});	
}

</script>

