<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>
<?php 
if($this->temp)
	$this->showMessage($this->temp)
?>	
<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>
<form  id="form" class="form-template" action="" method="post" enctype="multipart/form-data">
<table>
	<tr>
		<td>Task ID</td>
		<td><input type="text" id="TaskID" name="TaskID" class="disabled" readonly="readonly" class="taskid" value="<?php echo $this->obj->TaskID?>"/></td>
		<td>Task Name</td>
		<td><input type="text" id="TaskName" name="TaskName" value="<?php echo $this->obj->TaskName?>"/></td>
		
	</tr>
	<tr>
		
		
		<td>Action (*) </td>
		<td>
		<select id="ActionID" name="ActionID">
			
			<?php 
				foreach($this->arrAction as $row)
				{
					$str="";
					if($this->obj->ActionID == $row->ActionID )
					{
						$str= "selected";
					}
			?>
					<option <?php echo $str;?> value="<?php echo $row->ActionID ?>"><?php echo $row->ActionName ?></option>
			<?php
				}
			?>
		</select>
		</td>
		<td>Task String</td>
		<td><input type="text" id="TaskString" name="TaskString" value="<?php echo $this->obj->TaskString?>" onchange="getvalue('TaskString')" title="TaskString-string-value"/>
		<a title="chọn" id="stringadd" class="tool-16 explore" href="JavaScript:void(0);" title = "asds" onClick="findstring('TaskString','')"></a>&nbsp;
		<a title="sửa" id="taskstring-value" class="tool-16 edit" href="JavaScript:editstring('<?php echo $this->obj->TaskString?>','taskstring-value');" title = "asds"></a>&nbsp;
		<a title="thêm" id="newstring" class="tool-16 add" href="JavaScript:void(0);" title = "asds" onClick="newstring('TaskString','')"></a>
		<p class="string-value" id = "TaskString-string-value"><?php echo $this->obj->gNameTask?></p><p class="string-value" id = "questdesc-string-value" ><?php echo $this->regquestDS;?></p>
		</td>
	</tr>
	<tr>
		<td>Desc</td>
		<td><input type="text" id="DescString" name="DescString" value="<?php echo $this->obj->DescString?>" onchange="getvalue('DescString')"/></td>
		<td>DescString</td>
		<td><input type="text" id="DescID" name="DescID" value="<?php echo $this->obj->DescID?>" title="DescID-string-value"/>
		<a title="chọn" id="stringadd" class="tool-16 explore" href="JavaScript:void(0);" title = "asds" onClick="findstring('DescID','')"></a>&nbsp;
		<a title="sửa" id="taskstring-value" class="tool-16 edit" href="JavaScript:editstring('<?php echo $this->obj->DescID?>','taskstring-value');" title = "asds"></a>&nbsp;
		<a title="thêm" id="newstring" class="tool-16 add" href="JavaScript:void(0);" title = "asds" onClick="newstring('DescID','')"></a>
		<p class="string-value" id = "DescID-string-value" ><?php echo $this->obj->gNamedesc?></p>
		</td>
	</tr>
	<tr> 

		<td>Quantity (*) </td>
		<td><input type="text" id="Quantity" name="Quantity" value="<?php echo $this->obj->Quantity?>"/></td>	
		
		<!-- 
		<td>
		<INPUT TYPE=RADIO NAME="TargetType" VALUE="" CHECKED> Target Type<BR>
		<INPUT TYPE=RADIO NAME="TargetType" VALUE="null"> Target List<BR>
		</td>
		--><td>UnlockCoin (*) </td>
		<td><input type="text" id="UnlockCoin" name="UnlockCoin" value="<?php echo $this->obj->UnlockCoin?>"/></td>
	</tr>
	<tr>		
		
		<td>Quest Task Client</td>
		<!-- ////////////////Hien Quest Task Client vao commbobox/////////////////// -->
		
		<td colspan="3">
		<select id="QTC_ID" name="QTC_ID">
			
			<?php 
				foreach($this->arrQuestTC as $row)
				{
					$str="";
					if($this->obj->QTC_ID == $row->QTC_ID )
					{
						$str= "selected";
					}
			?>
					<option <?php echo $str;?> value="<?php echo $row->QTC_ID ?>"><?php echo $row->QTC_Name ?></option>
			<?php
				}
			?>
		</select>
		</td>
		
		<!--   <td><input type="text" id="QTC_ID" name="QTC_ID" value="<?php echo $val->QTC_ID?>"/></td>-->
		<!-- /////////////////////////////////// -->
	</tr>
	<tr>
	<td colspan="4" align="center">
		<input type="submit" value="save" id="button1"/>
	</td>
	</tr>
</table>

</form>
<div id="llightbox" style="position:fixed;top:0;left:0;width:100%;height:100%;z-index:9999;display:none;opacity:0.7;background:#222;"></div>
<div id = "stringmain"   style="position:fixed;top:20px;width:80%;height:80%;margin:auto;z-index:10000;background:#fff;overflow:scroll;display:none;padding:5px;border:15px solid #f4f4f4;border-radius:8px;">
<div id='dialog_edit_template'>
		
</div>
<div id='dialog_edit_localize'>
		
</div>
<script type="text/javascript">
////////Init Diaglog//////////
$("#dialog_edit_template").dialog({
				autoOpen: false,
				height: $(window).height()-50,
				width: $(window).width()-100,
				modal: true,
				buttons: {
					"Ok": function() {						
						$(this).dialog("close");
					}
				}
});
//////////////////Localite///////////////////
function getvalue(textbox)
{
	var tam = $('#'+textbox).val();	
	var tam1 = tam.split('@');
	var str_split = tam1[1].split('#');
	var groupname = str_split[0];
	var key = str_split[1]	
	$.ajax({
		type: "POST",
		url: '<?php echo $this->baseUrl?>/localite/string/viewkey',
		data: { 
					value : tam1[1]
			  },
		success: function (result) {			
			tam2 = result.split('/n/');
			var title = $('#'+textbox).attr('title');
			$('p#'+title).html(tam2[1]);
			$('a#'+title).attr("href","javascript:editstring('"+tam+"','"+title+"');");
		}
		}); 
}
function findstring(textbox,link)
{
	$.ajax({
		type: "POST",
		url: '<?php echo $this->baseUrl?>/localite/string/index?ajax=true&size=20'+link,
		data: { 
					
			  },
		success: function (result) {
			
			tam = result.split('<div id="splip"></div>');
			tam2=tam[1];
			tam2=tam2.replace('<input class="btn search" type="submit" name="search" value="search" />','<a style="padding:4px;border:1px solid #ddd;background:#f8f8f8;" href="JavaScript:void(0)" onClick="searchlink()">Tìm kiếm</a>')
			tam2=tam2.replace("searchlink()","searchlink('"+textbox+"')");
			for(i=0;i<20;i++)
			{
				tam2 = tam2.replace("(testajax,","('"+textbox+"',");
				tam2 = tam2.replace("/n/","'");
			}
			for(i=0;i<20;i++)
				tam2 = tam2.replace("/n/","'");
				tam3 = tam[2].split('"');
				tam4 = tam3[1].split('/n/');
				tam5 = tam4[0]/20;
				i=0;
				for(i=0;i<tam5;i++);
				strf = '<tfoot><tr><td colspan="7" align="center"><a onClick="firstpage(/n/'+textbox+'/n/,/n/'+link+'/n/,1)" href="JavaScript:void(0)"><<</a><a onClick="firstpage(/n/'+textbox+'/n/,/n/'+link+'/n/,'+(tam4[1]-1)+')" href="JavaScript:void(0)" ><</a><a>'+tam4[1]+'/'+i+'</a><a onClick="firstpage(/n/'+textbox+'/n/,/n/'+link+'/n/,'+(tam4[1]-(-1))+')" href="JavaScript:void(0)">></a><a onClick="firstpage(/n/'+textbox+'/n/,/n/'+link+'/n/,'+i+')" href="#">>></a></td></tr></tfoot>';
				for(i=0;i<16;i++)
				{
					strf = strf.replace("/n/","'");
				}
				$('#stringmain').html(tam2+strf);
				showlightbox()
		}
		}); 
}
function addstring(textbox,value)
{
	$('#'+textbox).attr("value",value);
	$('#stringmain').html("");
	getvalue(textbox);
	hidelightbox();
}
function searchlink(textbox)
{
	var id = $('input#ID').val();
	var type = $('select[name=l_Search_type]').val();
	var group = $('select[name=l_group]').val();
	findstring(textbox,"&page=1&l_Search_type="+type+"&S_ID="+id+"&l_group="+group);
}
function firstpage(textbox,link,page)
{
	if(link=='')
		link = '&page=1&l_Search_type=lkey&S_ID=-1&l_group=-1';
	tam = link.split('page=');
	tam1 = tam[1].split('&');
	tam2 = 'page='+tam1[0];
	tam3 = link.replace(tam2,"page="+page);
	findstring(textbox,tam3);
}





$('#llightbox').click(function(){
   	$('#stringmain').hide('slow').css('display','none');
	$('#llightbox').animate({opacity:0},500).css('display','none');
});
function hidelightbox(){
	$('#stringmain').hide('slow').css('display','none');
	$('#llightbox').animate({opacity:0},500).css('display','none');
}
function showlightbox(){
	$('table tfoot td a').css('margin','5px');
	$('#llightbox').css('display','block').css('opacity','0').animate({opacity:0.7},200);
	$('#stringmain').css('display','block');
}
function newstring(textbox,link)
{
	$('input#button1').hide();
	var ham = "addnewstring('"+textbox+"')";
	$.ajax({
		type: "POST",
		url: '<?php echo $this->baseUrl?>/localite/string/insert',
		data: { 

			  },
		success: function (result) {
			tam = result.split('<div id="splip"></div>');
			tam1 = tam[1].replace('<input id="button" type="submit" value="OK">','<a style=" border: 1px solid #C3D7DB;padding:2px 4px;margin:4px;" href="JavaScript:void(0)" title="lưu" onClick="'+ham+'">Lưu</a>');
			tam2 = tam1+'</div></div></div>';
			$('#stringmain').html(tam2);
		}
	}); 
	showlightbox();
}
function addnewstring(textbox){
	var key = $('input#id').val();
	var l_group = $('select#l_group').val();
	var gname = $("select#l_group option[value='"+l_group+"']").text();
	var test = $('textarea[name=test]').val();
	var test1 = $('textarea[name=test1]').val();
	if(test==''||test1=='' || l_group==''){alert('Bạn nhập chưa đầy đủ các string vui lòng nhập lại');return;}
	$.ajax({
		type: "POST",
		url: '<?php echo $this->baseUrl?>/localite/string/insert?key='+key+'&l_group='+l_group+'&test='+test+'&test1='+test1,
		data: { 
			  },
		success: function (result) {
			var value = '@'+gname+'#'+key; 
			addstring(textbox,value);
			hidelightbox();
		}
	});
}
function getgroupname(key){
	$.ajax({
		type: "POST",
		url: '<?php echo $this->baseUrl?>/localite/lgroup/getgroupname?id='+key,
		data: { 
			  },
		success: function (result) {
			return result;
		}
	});
}

//////////////Edit Language////////////////
var local_title = "";
function editstring(string,title){
	local_title = title;
	 $.ajax({
		type: "GET",		
		url: "<?php echo $this->baseUrl?>/localite/string/edit?view=dialog&string="+encodeURIComponent(string)+"",
		success: function (msg) {			
			$("#dialog_edit_localize").html(msg);		
			$("#dialog_edit_localize").dialog("open");
		}
	});
}
// init dialog
$("#dialog_edit_localize").dialog({
	autoOpen: false,
	height: 400,
	width: 400,
	modal: true,
	buttons: {
		"Save": function() {
			saveLanguage();
		},
		"Cancel": function() {
			$(this).dialog("close");
		}
	}
});
//save Language
function saveLanguage(){
	var data = $("form#insertstring").serialize();
	data +="&view=dialog";
	var string_value = $("form#insertstring textarea[name='default']").val();
	$.ajax({
		type: "POST",		
		url: "<?php echo $this->baseUrl?>/localite/string/edit/",
		data:data,
		success: function (msg) {						
				$("#dialog_edit_localize").dialog("close");
				$("p#"+local_title).text(msg);			
		}
	});	
}

//////////////////////
function changeMap()
{
	value = $('.l_group').val();
	$.ajax({
		type: "GET",		
		url: "<?php echo $this->baseUrl?>/localite/string/insert?action=getid&idl_group="+value,
		success: function (msg) {
			$('.id').val(msg);
		}
	});
}</script>
