<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>
<form action="" method="post" enctype="multipart/form-data" name="form1" id="form1">
<label>
    <input type="submit" name="btnbk" id="btnbk" value="Backup data" />
  </label>

<br/><br/>
<hr/><hr/><br/><br/>

   <label>Browse file restore :    
    <input type="file" name="file2" id="file2" value="Browse "/>
   </label>
  <br/><br/>
   <center>
   <label>
    <input type="submit" name="btnrt" id="btnrt" value="Restore " />
  </label>
 </center>
 </div>
</form>

</body>
</html>