<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>
<div id="box">
 <h3>Thêm nhóm</h3>
<form id="form" method="post">
<label for="street">Tên :</label>
<input name="name" value="" id="name" type="text" tabindex="1"/>
<input id="button1" type="submit" value="OK"/>
<input id="button1" type="button" value="Quay lại" onclick="history.go(-1)"/>
</form>
</div>
