<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
$model = new Models_Localize_Group();
$name = '';
if($this->id!=''){
	$info = $model->GetGroupInfo($this->id);
	$name = $info['name'];
}
?>
<div id="box">
 <h3>Thêm nhóm</h3>
<form id="form" method="post">
<label for="street">Tên :</label>
<input name="name" value="<?php echo $name?>" id="name" type="text">
<input id="button1" type="submit" value="OK"/>
<input id="button1" type="button" value="Quay lại" onclick="history.go(-1)"/>
</form>
</div>
