<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
$model = new Models_Localite_Group();
?>
<div id="box">
<h3>Danh sách nhóm</h3>
<form id="form" method="post">
	<table width="100%">
		<thead>
			<tr>
				<th width="40">STT</th>
				<th width="14">#</th>
				<th width="35">ID</th>
				<th>Tên nhóm</th>				
				<th width="40" align="center">Thao tác</th>
			</tr>
		</thead>
		<tbody>
			<?php 
			$i = 1;
			foreach ($model->GetAllGroup() as $value) {
				echo '<tr>';
					echo '<td>'.$i.'</td>';
					echo '<td><input id="'.$value['id'].'" type="checkbox" name="'.$value['id'].'"></td>';
					echo '<td>'.$value['id'].'</td>';
					echo '<td>'.$value['name'].'</td>';
					echo '<td>';
						echo '<a href="'.$this->baseUrl.'/localite/lgroup/ledit?id='.$value['id'].'"><img src="'.$this->baseUrl.'/media/images/icons/edit-icon.gif" ></a>';
						echo '<a href="'.$this->baseUrl.'/localite/lgroup/ldelete?id='.$value['id'].'"><img src="'.$this->baseUrl.'/media/images/icons/delete.gif" ></a>';
					echo '</td>';
				echo '</tr>';
				$i++;
			} 
			
			?>
		</tbody>
	</table>
	<div style="margin-top:20px;"><a class="btn add" type="submit" href="<?php echo $this->baseUrl?>/localite/lgroup/ladd">Add</a> 
		<button value="btsave" name="btsave" type="submit">Sửa</button>
		<button value="btdelete" name="btdelete" type="submit">Xóa</button>
	</div>
</form>
</div>
