<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>
<style>
#insertstring>div>div
{
	padding: 5px;
}
#insertstring>div>div>div
{
	padding: 5px;
}
#insertstring>div>div>div>div#idlabel
{
	width:60px;
	float:left;
}
#insertstring>div>div>div>select
{
	width:150px;
}
#insertstring>div>div>div>input#button
{
	margin-left:60px;
}
</style>
<form id="insertstring" class="myform" action="" name="string" method="post">
<div id="splip"></div>
<div id="box">
<h3>Insert Language</h3>
	<div id='body'>
		<div>
			<div id = 'idlabel'><label for="street">Key : </label></div>
			<div >
				<input id="id" type="text" tabindex="1" value="<?php echo $this->string->generateId();?>" name="key">
			</div>
			
		</div>
		<div>
			<div id = 'idlabel'><label for="street">Group : </label></div>
			<select id="l_group" name="l_group" onChange="changeMap(this)">	
				'<option value="">-- Chon Group --</option>';
			<?php 
				foreach ($this->group as $vlgroup) 
				{
					if ($this->current_group == $vlgroup[id]) 
						echo '<option value="'.$vlgroup[id].'" selected="selected">'.$vlgroup['name'].'</option>';
					else 
						echo '<option value="'.$vlgroup[id].'">'.$vlgroup['name'].'</option>';
				}
			?>
			</select>
		</div>
		<div>
			<div id = 'idlabel'><label for="street"><?php echo $this->string->getlangdefault();?> : </label></div>
			<textarea rows="3" cols="30" name="test"><?php if($this->test!=-1) echo $this->test;?></textarea>
		</div>
		<div>
			<div id = 'idlabel'><label for="street"><?php echo $this->string->getlangindex();?> : </label></div>
			<textarea rows="3" cols="30" name="test1"><?php if($this->test1!=-1) echo $this->test1;?></textarea>
		</div>		
		<div style="overflow:hidden;padding:10px;">
			<input id="button" type="submit" value="OK">&nbsp;
			<!--<div id="splip"></div>-->
			<input id="button1" type="button" onclick="history.go(-1)" value="Quay lại">
		</div>
	</div>
</div>

</form>

