<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>
<form action="" method="post" enctype="multipart/form-data" name="form1" id="form1">

 <div> 
  <label>Browse file Define.conf :
  <input type="file" name="file1" id="file1" value="Browse file Define.conf"/>
   </label>
  </div>
  <div> ..</div>
  <div>
   <label>Browse file system.xfj :    
    <input type="file" name="file2" id="file2" value="Browse file system.xfj"/>
   </label>
  </div>
  <div> ..</div>
   <div>
   <center>
   <label>
    <input type="submit" name="btn" id="btn" value="Import file define" />
  </label>
 </center>
 </div>
</form>
<fieldset>
</fieldset>
</body>
</html>