<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Ủn Ỉn Support</title>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl ?>/media/css/theme.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl ?>/media/css/style.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl ?>/media/css/chipzin-style.css" />
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/media/css/jquery-ui-1.8.16.custom.css" />
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/media/css/ui.jqgrid.css" />
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/media/scripts/jqgrid/plugins/ui.multiselect.css" />
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/media/scripts/dynatree/skin/ui.dynatree.css" />

 
 <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/media/flashs/chart/FusionCharts.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl ?>/media/scripts/jquery-1.7.1.min.js"></script>
<script src="<?php echo $this->baseUrl; ?>/media/scripts/jquery-ui-1.8.16.custom.min.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl ?>/media/scripts/form.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl ?>/media/scripts/chip-zin.js"></script>
<script src="<?php echo $this->baseUrl ?>/media/scripts/jqgrid/grid.locale-en.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl; ?>/media/scripts/jqgrid/jquery.jqGrid.min.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl ?>/media/scripts/utility.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl ?>/media/scripts/dynatree/jquery.dynatree.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl ?>/media/scripts/dynatree/jquery.dynatree.min.js.js"></script>
<script>
   var StyleFile = "theme" + document.cookie.charAt(6) + ".css";
   document.writeln('<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl ?>/media/css/' + StyleFile + '">');
</script>
<!--[if IE]>
<link rel="stylesheet" type="text/css" href="css/ie-sucks.css" />
<![endif]-->
</head>

<body>
	<div id="container">
    	<div id="header">
			<h2><img style="vertical-align: middle" height="64" width="64" src="<?php echo $this->baseUrl ?>/media/images/unin.gif"/>&nbsp;Ủn Ỉn Support</h2>
			<?php $this->topMenu($this) ?>			
			<?php $this->showHello($this->user, $this) ?>			
      </div>
        
		<?php $this->topPanel($this->controllerName, $this) ?>      
			
        <div id="wrapper">
            <div id="content">
				<?php echo $this->layout()->content ?>       			              
            </div>            
      </div>
        <div id="footer">
        <div id="credits">
			<img style="vertical-align: middle" width="16" height="16" src="<?php echo $this->baseUrl ?>/media/images/logo.gif"/>&nbsp;<b>Game Studio South</b>
        </div>
        <div id="styleswitcher">
            <ul>
                <li><a href="javascript: document.cookie='theme='; window.location.reload();" title="Default" id="mixswitch">d</a></li>
                <li><a href="javascript: document.cookie='theme=1'; window.location.reload();" title="Blue" id="blueswitch">b</a></li>
                <li><a href="javascript: document.cookie='theme=2'; window.location.reload();" title="Green" id="greenswitch">g</a></li>
                <li><a href="javascript: document.cookie='theme=3'; window.location.reload();" title="Brown" id="brownswitch">b</a></li>
                <li><a href="javascript: document.cookie='theme=4'; window.location.reload();" title="Mix" id="defswitch">m</a></li>                
            </ul>
        </div><br />

        </div>
</div>
</body>
</html>
