<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>

<?php //print_r($this->arrAwardItems)?>
<div  class="mybox" id="quest">
	<h3>Edit Quest</h3>
	<form class="quest" id="form" action="" method="post">
	  <fieldset id="info">
		<legend>Thông tin Quest </legend>
		<table id="quest">
			<tr>
				<td width="55%">
					<label for="QuestID">Quest ID : </label> 
					<input class="disabled" readonly name="QuestID" value="<?php echo $this->obj->QuestID ?>" id="QuestID" type="text" tabindex="1" /></td>
				<td>
					<label for="name" >Quest Line : </label>							
					<?php $this->selectQuestLine2($this->obj->QuestLineID,$this->arrQuestLine) ;?>
				</td>
			</tr>
			<tr>
				<td>
					<label for="questname">Quest Name : </label> 
					<input name="QuestName" class="width" value="<?php echo $this->obj->QuestName?>" id="questnamestring" type="text" tabindex="1" /></td>
				<td>
					<label for="queststring">Quest String: </label> 
					<input name="QuestString" value="<?php echo $this->obj->QuestString?>" id="queststring" type="text" tabindex="1" />					
				</td>

			</tr>
			
			<tr>
				<td>
					<label for="questgroup">Quest Group: </label> 
					<input name="QuestGroup" value="<?php echo $this->obj->QuestGroup?>" id="questgroup" type="text" tabindex="1" />
				</td>
				<td>
					<label for="QuestGroupString">Q_Group String: </label> 
					<input name="QuestGroupString" value="<?php echo $this->obj->QuestGroupString?>" id="questgroupstring" type="text" tabindex="1" />
				</td>		
		
			</tr>
			
			<tr>
				<td>
					<label for="QuestDesc">Quest Desc: </label> 
					<input name="QuestDesc" value="<?php echo $this->obj->QuestDesc?>" id="questdesc" type="text" tabindex="1" />
				</td>
				<td>
					<label for="questdescString">Q_Desc String: </label> 
					<input name="QuestDescString" value="<?php echo $this->obj->QuestDescString?>" id="questdescstring" type="text" tabindex="1" />
				</td>			
			</tr>
				
			
			<tr>
				<td class="q_award" rowspan="2">
					<label>Award:</label>
					<div><a class='tool-16 add' href=''></a></div>					
					<?php foreach($this->arrAward as $row){?>					
						<div>
							<select name='AwardType[]' style='margin-bottom: 1px;width:31%'>
							<?php echo $this->options($this->arrawardtype,$row->AwardTypeID,array('key'=>'AwardTypeID','name'=>'Name'));?>
							</select>							
							<label></label><input name='AwardValue[]' value='<?php echo $row->Value ?>' id='' type='text' tabindex='1' style='margin-bottom: 1px;width:15%'/><a class='tool-16 delete' title='Delete Item' href=''></a>
						</div>
					<?php }?> 
					
				</td>
				<td id="list-need-quest">
					<label>Need Quest : </label>				
					<select name='NeedQuest' style='margin-bottom:5px;margin-top:5px;min-width:50px'>
						<option value=''></option>
						<?php 
						$strSelectQuest = "";
						foreach ($this->arrNeedQuest as $row)
						{
							$select = "";
							if($row->QuestID == $this->obj->NeedQuest)
							{
								$select = "selected";
							}
							$strSelectQuest .= "<option $select value='". $row->QuestID ."'>(ID:$row->QuestID) $row->QuestName</option>";
						}
						echo $strSelectQuest;
						?>
					</select>
				</td>
			</tr>
			<tr>		
					
					<td>
					<label for="temp">Temp Field: </label> 		
					<input name="temp" value="" id="temp" type="text" tabindex="1" />
					</td>
					
			</tr>
			
			<tr>				
				

			</tr>
		</table>
		
		</fieldset>		
		</form>
		<div id="mybox">
		<fieldset id="tasks">
		<legend>Task:  <a id='addItem' class='ico-16 add' title='Add Task' href='javascript:addTask(0)'></a></legend>
			<div id='list-task' style="margin-top: 10px;">	
				
			</div>
			<div style="margin: auto; text-align: center; margin-top: 10px">	
			<a id="saveall" class="btn save" href="javascript:saveAll()">Save All</a>
			</div>		
	  	</fieldset>	
	  	</div>	  	
	</div>
<div id='dialog'>
	<div id='ct'></div>
	<div id='ft'> </div>
</div>
<div id='dialog_edit_template'>
		
</div>
<div style="display:none" id='tempAward'>
	<div >
		<select name='AwardType[]' style='margin-bottom: 1px;width:31%'>
		<?php foreach ($this->arrawardtype as $row)
		{
		?>
		<option value ='<?php echo $row->AwardTypeID;?>'><?php echo $row->Name;?></option>
		<?php 
		}
		?>
		</select>		
		<label></label><input name='AwardValue[]' value='' id='' type='text' tabindex='1' style='margin-bottom: 1px;width:15%'/><a class='tool-16 delete' title='Delete Item' href=''></a>
	</div>
</div>
<script>
//*****************************Award Item****************//

//*****************************Award Item****************//

//Add Award Item
function  addAwardItem(e)
{		
	var parent_div = $(e).parent();
	var parent_td = parent_div.parent();
	var parent_tr = parent_td.parent();
	var html=$("#tempAward").html();
	parent_td.append(html);
	//parent_tr.change();
}
//delete A Award
function deleteAwardItem(e){
	
	var parent_div = $(e).parent();
	//var parent_td = parent_div.parent();
	//var parent_tr = parent_td.parent();
	parent_div.remove();
	//parent_tr.change();
}
//Add A Award///////
$("table#quest").delegate("td.q_award .add", "click", function() {
	addAwardItem(this);		
	return false;		
});
//Remove A Award///////
$("table#quest").delegate("td.q_award .delete", "click", function() {	
	deleteAwardItem(this);		
	return false;		
});
//*****************************Award Item****************//
////////////////////////////////
function  deleteNeedQuest(key){
	//alert("asd");
	var div =  $("div#need_quest_" + key);
	if(div.hasClass("new"))
		div.html("");
	else{	
		div.hide();
		div.children("a").remove();
		div.children("select").children(".data").remove();
		
	}	
}
//////////////////////////////////////////
function addTask(key){
	
	count = $(".task").size();
	if(count >= 3){
		alert("Fail!!!! Limited 3 Task in a Quest");
		return;
	}
	
	quest_id = $("#QuestID").val();
	$.ajax({
		type: "POST",
		url:"<?php echo $this->baseUrl.'/task/add/'?> ",
		data: "id=" + quest_id,	
		success: function(data){			
			if(data != ""){	
				//alert(data);
				loadTask(quest_id);
			}else{
				alert("Error");				
			}
			
		}
	});
}
/////////////////////////////////////////
function deleteTask(key){		
	task_id = $("#task-"+key+" input#TaskID").val();	
	task_name = $("#task-"+key+" input#TaskName").val();
	quest_id = $("#QuestID").val();
	div = 	$("#task-"+key);
	if(!confirm("Do you want to delelte Task: " + task_name)){
		return false;
	}		
	$.ajax({
		type: "POST",
		url:"<?php echo $this->baseUrl.'/task/delete/'?> ",
		data: "id=" + task_id,	
		success: function(msg){				
			if(parseInt(msg)==1){					
				loadTask(quest_id);				
			}else{
				alert("Error");				
			}
			
		}
	});

}
////////////////////////////////////////
function loadTask(key){	
	$.ajax({
		type: "POST",
		url:"<?php echo $this->baseUrl.'/quest/listtask/'?> ",
		data: "id=" + key,	
		success: function(data){		
			if(data != ""){ 				
				$("#list-task").html(data);
				$(".add-target").click(function(){
					addTarget(this);
					return false;
				});
				$("input[name=target]").change(function(){
					targetChange(this);
				});
			}else{
				alert("Error");				
			}
			
		}
	});	
}
loadTask(<?php echo $this->obj->QuestID?>);
///////////////////////////////////////
function targetChange(key){
	
	selected = ($(key).val());
	if(selected == "TargetType"){
		
	}else{
		
	}
}
/////////////////////////////////////
function addTarget(key){
	parent = $(key).parent();	
	count = parent.children('.target-list').size();	
	input ='<input id = "target-'+count+'" class="target-list" style="margin-left: 50px;width: 153px;" type="text" name="TargetList[]" value=""> <br>';
	//btn_delete();
	parent.children('.list').append(input);
}
////////////////////////////////
function validate(){
	flag=true;
	
	$(".task").each(function(key,val){
		num = key+1;
		value = $(val).find(" #TaskString").val();		
		if(value=='')
		{
			$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>TaskString không được để trống</p>");					
			flag=false;
		}		
		value = $(val).find("#TaskName").val();
		
		value = $(val).find("#DescID").val();
		if(value=='')
		{
			$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>DescString không được bỏ trống</p>");	
			flag=false;
		}
		value = $(val).find("#QuestTC").val();
		value = $(val).find("#UnlockCoin").val();
		if(isNaN(value))
		{
			$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>UnlockCoin phải là số</p>");					
			flag=false;
		}
		if(value=='')
		{
			$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>UnlickCoin không được để trống</p>");					
			flag=false;
		}
		value = $(val).find("#Quantity").val();
		if(isNaN(value))
		{
			$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>Quantity phải là số</p>");					
			flag=false;
		}
		if(value=='')
		{
			$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>Quantity không được để trống</p>");					
			flag=false;
		}
		value = $(val).find("#Action").val();	
		if(value=='')
		{
			$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>Hãy chọn Action</p>");					
			flag=false;
		}
		//////////////
		target = $(val).find("#target :radio:checked").val();
		if(target == "TargetType"){
			targetType=$(val).find("#TargetType").val();
			if(targetType=='')
			{
				$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>TargetType không được bỏ trống</p>");					
				flag=false;
			}
			else if(isNaN(targetType))
			{
				$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>TargetType phải là số</p>");					
				flag=false;
			}
		}else{			
			targetList=$(val).find(".target-list").val();
			count = $(val).find(".target-list").size();			
			if(count==0)
			{								
					$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>TargetList chưa được tạo</p>");					
					flag=false;				
			}
			else if(targetList=='' &&count!=0 )
			{
				
				$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>TargetList không được bỏ trống</p>");					
				flag=false;
			}
			else if(isNaN(targetList) &&count!=0)
			{
				$("#dialog #ct").append("<p class='error'>Task " + num + ":	<br>TargetList phải là số</p>");					
				flag=false;
			}
		}
	});
	return flag;	
}
///////////////////////////////
function saveAll(){	
	$("#dialog #ct").html("");
	quest_id = $("#QuestID").val();
	s = $("form#form").serialize();	
	test = validate();
	if(test==false)
	{
		$("#dialog").dialog({			
			height: 300,
			width: 350,
			modal: true,
			buttons: {
				"Continue": function() {								
					$(this).dialog("close");						
				}										
			}
			});		
	}
	else
	{
		$.ajax({
			type: "POST",
			url:"<?php echo $this->baseUrl.'/quest/edit/'?>",
			data: s,		
			success: function(msg){
				if(parseInt(msg)==1){	
					$("#dialog #ct").append("<p class='msg'>Add Quest Success<p>");
					saveTask();	
					//$("#dialog").dialog("open");
					$("#dialog").dialog({
						height: 300,
						width: 350,
						modal: true,
						buttons: {
							"Success": function() {								
								$(this).dialog("close");
								location.replace("<?php echo $this->baseUrl.'/quest/'?>");							
							},
							"Edit": function() {								
								$(this).dialog("close");
								location.replace("<?php echo $this->baseUrl.'/quest/edit/id/'?>"+quest_id);
								//alert(quest_id);
							},
							"New": function() {								
								$(this).dialog("close");
								location.replace("<?php echo $this->baseUrl.'/quest/new/'?>");							
							}										
						}
						});
				}else{				
					$("#dialog #ct").append("<p class='error'>Failed:<br>"+msg+"<p>");				
					$("#dialog").dialog({
						height: 300,
						width: 350,
						modal: true,
						buttons: {
							"Error": function() {								
								$(this).dialog("close");														
							}
						}
						});
				}
							
									
			}
		});	
	}	
}
///////////////////////////////
function saveTask(){
	var key = 0;
	$(".task").each(function (index){		
		
		data = $(".form-task-"+ index).serialize();		
		$.ajax({
			type: "POST",
			url:"<?php echo $this->baseUrl.'/task/save/'?> ",
			data: data + "&QuestID=" + quest_id,	
			success: function(msg){					
				key = key+ 1;
				if(parseInt(msg)==1){
					$("#dialog #ct").append("<p class='success'>Task "+ key +":Success<p>");
				}else{					
					$("#dialog #ct").append("<p class='error'>Task " + key + ":	<br>"+ msg + "</p>");
										
				}	
				
			}
		});
	
	});
}
////////////////////////////////
/////////////////////////Task/////////////////////////////////
function addTemplate(key){
	data = $(".form-task-" + key).serialize();	
	$.ajax({
		type: "POST",
		url:"<?php echo $this->baseUrl.'/Template/save/'?> ",
		data: data,
		dataType:"json",	
		success: function(msg){	
			if( msg.msg=="1"){
				var option_html = "<option value='"+msg.TempID+"'>"+msg.Name+"</option>";
				$("select.task-template").append(option_html);
				alert("Successfull");			
			}else{
				alert(msg.msg);				
			}
		}
	});
}
function loadTemplate(key){
	var id = $("#template"+key).val();	
	$.ajax({
		type: "POST",		
		url:"<?php echo $this->baseUrl.'/task/loadtemplate/'?> ",
		data: "id=" + id,	
		dataType: "json",
		success: function(msg){
			alert(msg);			
			$(".form-task-" + key +" #TaskString").val(msg.TaskString);
			$(".form-task-" + key +" #TaskName").val(msg.TaskName);
			$(".form-task-" + key +" #DescID").val(msg.DescID);
			$(".form-task-" + key +" #DescString").val(msg.DescString);
			$(".form-task-" + key +" #QuestTC").val(msg.QTC_ID);
			$(".form-task-" + key +" #Action").val(msg.ActionID);
			$(".form-task-" + key +" #UnlockCoin").val(msg.UnlockCoin);
			$(".form-task-" + key +" #Quantity").val(msg.Quantity);
			$(".form-task-" + key +" #IconClassName").val(msg.IconClassName);			
			$(".form-task-" + key +" #IconPackageName").val(msg.IconPackageName);
			if(msg.TargetType==null){				
				$(".form-task-" + key+ " .list").html("");
				$(".form-task-" + key + " #TargetType").val('');
				$(".form-task-" + key+ " #List").attr("checked", true);				
				$.each(msg.TargetList, function(key1,val){				
					count = $(".form-task-" + key+' .target-list').size();	
					input ='<input id = "target-'+count+'" class="target-list" style="margin-left: 50px;width: 153px;" type="text" name="TargetList[]" value="'+val.TargetID+'"> <br>'
					$(".form-task-" + key + " .list").append(input);
				});
			}else{								
				$(".form-task-" + key + " #TargetType").val(msg.TargetType);
				$(".form-task-" + key + " .list").html("");
				$(".form-task-" + key + " #Type").attr("checked", true);
			}
		}
	});	
}
function editTemplate(){
	$.ajax({
		type: "POST",		
		url:"<?php echo $this->baseUrl.'/template/index/?layout=disabled'?> ",				
		success: function(msg){			
			$("div#dialog_edit_template").html(msg);
		}
	});	
	$("div#dialog_edit_template").dialog("open");
}

////////Init Diaglog//////////
$("#dialog_edit_template").dialog({
				autoOpen: false,
				height: $(window).height()-50,
				width: $(window).width()-100,
				modal: true,
				buttons: {
					"Ok": function() {						
						$(this).dialog("close");
					}
				}
});
</script>