<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>

<?php //print_r($this->arrAwardItems)?>
<div id="box">
	<h3 id="adduser">Chỉnh sửa Quest</h3>
	<form id="form" action="<?php echo $this->baseUrl.'/Quest/update/' ?>" method="post" enctype="multipart/form-data">
	  <fieldset id="personal">
		<legend>Thông tin Quest</legend>
		<table>
			<tr>
				<td>
					<label for="QuestID">Quest Id : </label> 
					<input name="QuestID" value="<?php echo $this->obj->QuestID ?>" id="alias" type="text" tabindex="1" /></td>
				<td>
					<label for="name" >Quest Line : </label>							
					<?php $this->selectQuestLine2($this->obj->QuestLineID,$this->arrValue) ;?>
				</td>
			</tr>
			<tr>
				<td>
					<label for="questname">Quest Name : </label> 
					<input name="QuestName" value="<?php echo $this->obj->QuestName?>" id="questnamestring" type="text" tabindex="1" /></td>
				<td>
					<label for="queststring">Quest String: </label> 
					<input name="QuestString" value="<?php echo $this->obj->QuestString?>" id="queststring" type="text" tabindex="1" />
					
				</td>
			</tr>
			
			<tr>
				<td>
					<label for="questgroup">Quest Group: </label> 
					<input name="QuestGroup" value="<?php echo $this->obj->QuestGroup?>" id="questgroup" type="text" tabindex="1" />
				</td>
				<td>
					<label for="QuestGroupString">Q_Group String: </label> 
					<input name="QuestGroupString" value="<?php echo $this->obj->QuestGroupString?>" id="questgroupstring" type="text" tabindex="1" />
				</td>
			</tr>
			
			<tr>
				<td>
					<label for="QuestDesc">Quest Desc: </label> 
					<input name="QuestDesc" value="<?php echo $this->obj->QuestDesc?>" id="questdesc" type="text" tabindex="1" />
				</td>
				<td>
					<label for="questdescString">Q_Desc String: </label> 
					<input name="QuestDescString" value="<?php echo $this->obj->QuestDescString?>" id="questdescstring" type="text" tabindex="1" />
				</td>
			</tr>
				
			
			<tr>
				<td rowspan=2">
		<p>Award: </p>
		<label>Gold: </label><input name="AwardGold" value="<?php echo $this->obj->AwardGold?>" id="awardgold" type="text" tabindex="1" /><br/>
		<label>EXP: </label><input name="AwardExp" value="<?php echo $this->obj->AwardExp?>" id="awardexp" type="text" tabindex="1" /><br/>
		<label for="2">ITems: </label><a id='addItem0' title='Add Item' href='javascript:addAwardItem(addItem0)'><img style='vertical-align: middle' src='/vng/game-tool/sourcecode/chipzin/media/images/icons/add.png'></a>
		        <?php $this->ListQuestAwardItems($this->arrAwardItems) ;?>
		 
				</td>
				<td>
					<label for="name">Next Quest : </label> 		
					<?php $this->SelectNextQuest($this->obj->NextQuest,$this->arrnextQuest) ;?>
				</td>
			</tr>
			
			<tr>				
				<td>
					<label for="name">Need Quest : </label> <a title="Thêm Need Quest" href="javascript:addNeedQuest()"><img style="vertical-align: middle" src="/vng/game-tool/sourcecode/chipzin/media/images/icons/add.png"></a><br/>
					<?php $this->listNeedQuest($this->arrNeedQuest,$this->arrQuest)?>															
					
				</td>
			</tr>
		</table>
		</fieldset>
		
		<fieldset id="personal">
		<legend>Task: </legend>
			<div id='list-task'>
				<h3>Task 1</h3>
				<div id='task-0'>
				</div>
				<h3>Task 2</h3>
				<div id='task-1'>
				</div>
				<h3>Task 3</h3>
				<div id='task-2'>
				</div>
			</div>	
	  	</fieldset>
  		<input id="button1" type="submit" value="Save All" /> &nbsp;&nbsp; 	  
 		<input id="button1" type="button" value="Cancel	" onclick="window.location='<?php echo $this->baseUrl ?>/quest/index'" />		
		<br />	
		
	</form>
</div>
<script>
function  addAwardItem(key){	

	var count = $(".awarditem").size();
	count = count + 1;
	var str = " <a title='Add Item' href='javascript:addAwardItem(award_"+count+")'><img style='vertical-align: middle' src='/vng/game-tool/sourcecode/chipzin/media/images/icons/add.png'></a>"
    + " <a title='Delete Item' href='javascript:deleteAwardItem(award_"+count+")'><img style='vertical-align: middle' src='/vng/game-tool/sourcecode/chipzin/media/images/icons/delete.gif'></a>" ;
//	if(key==-1)
//		$("#addItem1").after("<div class='awarditem' id='award1-"+count+"'><label></label><input name='awarditem[]' value='' id='' type='text' tabindex='1'/>"+str+"</div>");
//	else
		$(key).after("<div class='awarditem' id='award_"+count+"'><label></label><input name='awarditem[]' value='' id='' type='text' tabindex='1'/> "+str+"</div>");
}

function  addNeedQuest(key){
	$.ajax({
		type: "POST",
		url:"<?php echo $this->baseUrl.'/quest/listquest/'?> ",		
		success: function(data){
			if(data != "")
			{	
				var count = $(".awarditem").size();
				count = count + 1;	
				var html = "<div class='need-quest' id='need-quest-"+count+"'><label></label>" + data + "</div>";	
				alert(html);		
				//$("#task-" + postion).html(data);
			}
			else
			{
				alert("Thêm  không thành công");
				
			}
			
		}
	});
	
}

function  deleteAwardItem(key){
	s = $(key).remove();	
}

function  deleteNeedQuest(key){
	//alert("asd");
	$("div#need-quest-" + key).remove();
}
//////////////
function loadtask(postion,task_id){
	$.ajax({
		type: "POST",
		url:"<?php echo $this->baseUrl.'/task/edit/'?> ",
		data: "id=" + task_id,
		success: function(data){
			if(data != "")
			{					
				$("#task-" + postion).html(data);
			}
			else
			{
				alert("Thêm  không thành công");
				
			}
			
		}
	});
}
$(function(){
	<?php foreach ($this->arrTask as $key=>$value) {?>
		loadtask(<?php echo$key?>,<?php echo $value->TaskID?>);
	<?php }?>
	
});
</script>