<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>

<form id="quest" name="quest" action="" method="post">
	<h3>Quest</h3>
	<table class="filter">
	
		<tr style="border: 0px;">
			<td><p>Quest ID</p></td>
			<td><input type="text" name="QuestID" id="QuestID" value="<?php print_r( $this->item->QuestID);?>" stype="width: 110px;"/></td>
			<td><p>Quest Line</p></td>
			<td>
				<select name="QuestLineID" id = "QuestLineID"  value="<?php $this->filterQuestLine->QuestLineID?>">
				<option selected value="<?php $this->filterQuestLine->QuestLineID?>"><?php echo( $this->filterQuestLine->QuestLineName);?></option>
				<?php 
				foreach($this->dataquestlineid as $row)
				{
				?>
					<option value="<?php echo $row->QuestLineID ?>"><?php echo $row->QuestLineName ?></option>
					
				<?php
				}
				?>

				</select>
			</td>
			<td><input type="submit" name="button1" id = "button1" value="search"/></td>
		</tr>
	</table>
	<table width="100%">
		<tr>
			<th><a href="#">STT</a></th>
			<th><a href="#">ID</a></th>
			<th><a href="#">Name</a></th>
			<th><a href="#">Quest line ID</a></th>
			<th><a href="#">Tool</a></th>
		</tr>
		<?php $this->listQuest($this->data, $this->page, $this->items, $this) ?>
	</table>
	<?php echo $this->pagingControl($this->items, $this->page, $this->totalRecord, $this) ?>
</form>