<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>
<?php 
if($this->temp)
	$this->showMessage($this->temp)
?>	
<form  class="myform" id="formPaging" name="formPaging" action="" method="post">

<div class="mybox">
	<h3>Quest</h3>
	<table class="filter">	
		<tr style="border: 0px;">
			<td>Quest ID
			<input type="text" name="QuestID" id="QuestID" value="<?php print_r( $this->item->QuestID);?>" style="width: 110px;"/></td>
			<td></td>
			<td>Quest Line
				<select name="QuestLineID" id = "QuestLineID">
				<option value=""> </option>
				<?php 
				foreach($this->dataquestlineid as $row)
				{
					$str = "";
					if($this->filterQuestLine->QuestLineID == $row->QuestLineID){
						$str="selected";
					}
				?>					
					<option '<?php echo $str; ?>' value="<?php echo $row->QuestLineID ?>"><?php echo $row->QuestLineName ?></option>
					
				<?php
				}
				?>
				
				</select>
			</td>
			<td>
				<input type="submit" name="button1" id = "button1" value="search"/>
				<a class="btn add" href="<?php echo $this->baseUrl.'/quest/new'?>">Add</a>
			</td>
		</tr>
	</table>
	<table class="list" id="list_ql" width="100%">
		<thead>
		<tr>
			<td width="10"><input type='checkbox' name='chkid' value='0'/></td>
			<td width="30"><a href="#">ID</a></td>
			<td><a href="#">Name</a></td>
			<td><a href="#">Quest line</a></td>
			<td><a href="#">Tool</a></td>
		</tr>
		</thead>
		<?php $this->listQuest($this->data, $this->page, $this->items, $this) ?>
	</table>
	<?php echo $this->pagingControl($this->items, $this->page, $this->totalRecord, $this) ?>

</div>
</form>