<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>
<?php 
if($this->temp)
	$this->showMessage($this->temp)
?>	
<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>
<form  id="form" class="form-template" action="" method="post" enctype="multipart/form-data">
<table>
	<tr>
		<td>Task ID</td>
		<td><input type="text" id="TaskID" name="TaskID" class="disabled" readonly="readonly" class="taskid" value="<?php echo $this->obj->TaskID?>"/></td>
		<td>Task Name</td>
		<td><input type="text" id="TaskName" name="TaskName" value="<?php echo $this->obj->TaskName?>"/></td>
		
	</tr>
	<tr>
		<td>Task String</td>
		<td><input type="text" id="TaskString" name="TaskString" value="<?php echo $this->obj->TaskString?>"/></td>
		<td>Action (*) </td>
		<td>
		<select id="ActionID" name="ActionID">
			
			<?php 
				foreach($this->arrAction as $row)
				{
					$str="";
					if($this->obj->ActionID == $row->ActionID )
					{
						$str= "selected";
					}
			?>
					<option <?php echo $str;?> value="<?php echo $row->ActionID ?>"><?php echo $row->ActionName ?></option>
			<?php
				}
			?>
		</select>
		</td>
	</tr>
	<tr>
		<td>DescID</td>
		<td><input type="text" id="DescString" name="DescString" value="<?php echo $this->obj->DescString?>"/></td>
		<td>DescString</td>
		<td><input type="text" id="DescID" name="DescID" value="<?php echo $this->obj->DescID?>"/></td>
	</tr>
	<tr> 

		<td>Quantity (*) </td>
		<td><input type="text" id="Quantity" name="Quantity" value="<?php echo $this->obj->Quantity?>"/></td>	
		
		<!-- 
		<td>
		<INPUT TYPE=RADIO NAME="TargetType" VALUE="" CHECKED> Target Type<BR>
		<INPUT TYPE=RADIO NAME="TargetType" VALUE="null"> Target List<BR>
		</td>
		--><td>UnlockCoin (*) </td>
		<td><input type="text" id="UnlockCoin" name="UnlockCoin" value="<?php echo $this->obj->UnlockCoin?>"/></td>
	</tr>
	<tr>		
		
		<td>Quest Task Client</td>
		<!-- ////////////////Hien Quest Task Client vao commbobox/////////////////// -->
		
		<td colspan="3">
		<select id="QTC_ID" name="QTC_ID">
			
			<?php 
				foreach($this->arrQuestTC as $row)
				{
					$str="";
					if($this->obj->QTC_ID == $row->QTC_ID )
					{
						$str= "selected";
					}
			?>
					<option <?php echo $str;?> value="<?php echo $row->QTC_ID ?>"><?php echo $row->QTC_Name ?></option>
			<?php
				}
			?>
		</select>
		</td>
		
		<!--   <td><input type="text" id="QTC_ID" name="QTC_ID" value="<?php echo $val->QTC_ID?>"/></td>-->
		<!-- /////////////////////////////////// -->
	</tr>
	<tr>
	<td colspan="4" align="center">
		<input type="submit" value="save" id="button1"/>
	</td>
	</tr>
</table>

</form>
