<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>
<form id="frmQuestLine" class="myform" action="" method="post">

<div class="mybox">
	<h3>Quest Line</h3>
	<table class="filter" style="width: 80%;margin: auto;margin-bottom: 20px;margin-top: 10px";>
		<tr>
			<td>Quest Line ID</td>
			<td><input style="width:110px;" type="text" name="searchID" id="searchID" class="searchbox" /></td>
			<td><input type="submit" name="search_ql" class="btn search" id="search-ql" value="search" /></td>
		</tr>
		
		<tr>
			<td>ID</td>
			<td><input id="QuestLineID"  class="disabled" name="QuestLineID" type="text"  readonly  style="width:110px;" /></td>
			<td>Name
			<input id="QuestLineName" type="text" name="QuestLineName"/>
				<a class="btn save disabled " href="">Save</a>
				<a class="btn add disabled " href="">Add</a>
				<a class="btn cancel disabled " href="">Cancel</a>
			</td>
		</tr>
	</table>
	<table class="list" id="list_ql" style="width: 80%;margin:auto ;border: 1px solid;">	
		<thead>
			<tr>									
				<td width="40"><a href="#">ID</a></td>
				<td>Quest Line Name</td>							
				<td class="center" width="80">Action</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<?php $this->listQuestLine($this->data, $this->page, $this->items, $this) ?>
			</tr>
		</tbody>						
	</table>		
	<div align="center" style="margin: 20px;">		
		<input class="btn big sync"  type="submit" value="Sync">
	</div>
	
	
	
</div>
</form>
<script type="text/javascript">
/**************************
 * reset event
 */
$("a.btn.disabled").click(function(){
	//alert("disabled");
	return false;
});


$(function(){	
	////////////////click Cancel//////////////////////////
	$(".btn.cancel").click(function(){
		if($(".btn.cancel").hasClass('disabled')){			
 	 	}else{
 	 		document.getElementById('QuestLineID').value = '';
 	 		document.getElementById('QuestLineName').value = '';
 	 		disable($(".btn.add"));
			disable($(".btn.save"));
			disable($(".btn.cancel"));
 	 	}
 	 	return false;
 	});

///////////////////Input Event///////////////////////////
	$("#QuestLineName").keyup(function(e){
		var id = $("#QuestLineID").val();
		var name = $("#QuestLineName").val();
		
		if(name == ''){
			disable($(".btn.add"));
			disable($(".btn.save"));
		}else{	
			enable($(".btn.cancel"));					
			if(id != ''){
				disable($(".btn.add"));
				enable($(".btn.save"));				
			}else{
				enable($(".btn.add"));
				disable($(".btn.save"));
			}
		}
	});
///////////////Save click/////////////////
	$(".btn.save").click(function(){
		if($(this).hasClass("disabled")){
			return false;
		}
		updateQuestLine();			
	});		

	$(".btn.add").click(function(){
		if($(this).hasClass("disabled")){
			return false;
		}
		updateQuestLine();			
	});	
});

///////////////////Function///////////////////////
/*******click edit button***********/
function editQuestLine(key){
	id = $("#quest-line-"+key+" .id").text();
	name = $("#quest-line-"+key+" .name").text();
	document.getElementById('QuestLineID').value = id;
	document.getElementById('QuestLineName').value = name;
	if($(".btn.save").hasClass('disabled')){
		$(".btn.save").removeClass("disabled");		
	}
	if($(".btn.cancel").hasClass('disabled')){
		$(".btn.cancel").removeClass("disabled");		
	}
	if(!$(".btn.add").hasClass('disabled')){
		$(".btn.add").addClass("disabled");
	}
	return false;
}

/*******click edit button***********/
function deleteQuestLine(key){
	id = $("#quest-line-"+key+" .id").text();
	name = $("#quest-line-"+key+" .name").text();
	if(!confirm("Bạn có muốn xóa QuestLine: " + name)){
		return false;
	};
	$.ajax({
		type: "POST",
		url: "http://localhost/vng/game-tool/sourcecode/chipzin/questline/update",
		url: "<?php echo $this->baseUrl.'/QuestLine/delete/'?> ",
		data: "QuestLineID="+id,
		success: function(msg){
			if(msg != ""){					
				alert(msg);
			}
			else{
				window.location.reload();		
			}			
		}
	});	
	return false;
}
///////////UpdateQuestLine///////////////
//Neu co QuestLineID thi se Update, nguoc lai se insert

function updateQuestLine(){
	var id = $("#QuestLineID").val();
	var name = $("#QuestLineName").val();
	$.ajax({
		type: "POST",
		url: "http://localhost/vng/game-tool/sourcecode/chipzin/questline/update",
		url: "<?php echo $this->baseUrl.'/QuestLine/update/'?> ",
		data: "QuestLineName=" + name +"&QuestLineID="+id,
		success: function(msg){
			if(msg != ""){					
				window.location.reload();
			}
			else{
				alert("Update KO thành công");				
			}			
		}
	});	
}


</script>