<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>

<form id="frmSoldierEditor" class="myform" action="" method="post">
<div class="mybox">
	<h1>TYPE MAP EDITOR</h1>
	<table class="filter" style="width: 80%;margin: auto;margin-bottom: 20px;margin-top: 10px";>	
		<tr>
			<td>ID</td>
			<td><input id="TypeID" class="disabled" readonly name="TypeID" type="text" style="width:110px;" /></td>
			<td>Name
			<input id="TypeName" type="text" name="TypeName"/>
				<a class="btn save disabled " href="">Save</a>
				<a class="btn add disabled " href="">Add</a>
				<a class="btn cancel disabled " href="">Cancel</a>
			</td>
		</tr>
	</table>
	<table class="list" id="list_Type" style="width: 80%;margin:auto ;border: 1px solid;">	
		<thead>
			<tr>									
				<td width="40"><a href="#">ID</a></td>
				<td>Type Name</td>							
				<td class="center" width="80">Action</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<?php
		$strList .= "<tbody>";
			foreach($this->data as $key =>$row){				
								
				$edit = "<a class='tool-16 edit' href='javascript:editType($key)'></a>";				
				$delete = "<a class='tool-16 delete' href='javascript:deleteType($key)'></a>";;								
				$strList .= "<tr id='Type-$key'>							
								<td class='id'>$row->ID</td>	
								<td class='name'>$row->Name</td>						
								<td align='center'>								
									$edit&nbsp								
									$delete								
								</td>
							</tr>";
			}
		$strList .= "</tbody>";
		echo $strList; 
		?>
			</tr>
		</tbody>						
	</table>	
	
	<div align="center" style="margin: 20px;">		
		<input class="btn big sync"  type="submit" value="Sync">
	</div>
</div>
</form>
<div id="ed">
</div>
<script type="text/javascript">
$("a.btn.disabled").click(function(){
	//alert("disabled");
	return false;
});


$(function(){	
////////////////click Cancel//////////////////////////
	$(".btn.cancel").click(function(){
		if($(".btn.cancel").hasClass('disabled')){			
 	 	}else{
 	 		document.getElementById('TypeID').value = '';
 	 		document.getElementById('TypeName').value = '';
 	 		disable($(".btn.add"));
			disable($(".btn.save"));
			disable($(".btn.cancel"));
 	 	}
 	 	return false;
 	});
	
///////////////////Input Event///////////////////////////
	$("#TypeName").keyup(function(e){
		var id = $("#TypeID").val();
		var name = $("#TypeName").val();
		
		if(name == ''){
			disable($(".btn.add"));
			disable($(".btn.save"));
		}else{	
			enable($(".btn.cancel"));					
			if(id != ''){
				disable($(".btn.add"));
				enable($(".btn.save"));				
			}else{
				enable($(".btn.add"));
				disable($(".btn.save"));
			}
		}		
	});	
///////////////Save click/////////////////
	$(".btn.save").click(function(){
		if($(this).hasClass("disabled")){
			return false;
		}
		updateType();			
	});		

	$(".btn.add").click(function(){
		if($(this).hasClass("disabled")){
			return false;
		}
		updateType();
	});
});

function editType(key){
	id = $("#Type-"+key+" .id").text();
	name = $("#Type-"+key+" .name").text();
	document.getElementById('TypeID').value = id;
	document.getElementById('TypeName').value = name;
	if($(".btn.save").hasClass('disabled')){
		$(".btn.save").removeClass("disabled");		
	}
	if($(".btn.cancel").hasClass('disabled')){
		$(".btn.cancel").removeClass("disabled");		
	}
	if(!$(".btn.add").hasClass('disabled')){
		$(".btn.add").addClass("disabled");
	}
}
/*******click delete button***********/
function deleteType(key){
	id = $("#Type-"+key+" .id").text();
	name = $("#Type-"+key+" .name").text();
	if(!confirm("Bạn có muốn xóa Type: " + name)){
		return false;
	};
	$.ajax({
		type: "POST",
		url: "<?php echo $this->baseUrl.'/campaign/Typemap/delete/'?> ",
		data: "ID="+id,
		dataType:"json",
		success: function(msg){
			
			if(parseInt(msg.length)==0){					
				window.location.reload();
			}
			else{
				$('#ed').html('');
				$.each(msg, function(key, val) 
				{
					$('#ed').append('<tr><td><p>'+ val.ID+"."+ val.Name+'</p></td><td><p><a class="tool-16 edit" href="<?php echo $this->baseUrl;?>/campaign/campaign/edit/id/'+val.ID+'"></a></p></td></tr>');
				});

				$("#ed").dialog
				({
					title: "Các Campaign có Type map này",
					height: 280,
					width: 250,
					modal: true,
					buttons: 
					{
						"close": function() 
						{
							$(this).dialog("close");							
						}										
					}
				});
						
			}			
		}
	});	
	
}
function updateType(){
	var id = $("#TypeID").val();
	var name = $("#TypeName").val();
	$.ajax({
		type: "POST",
		url: "<?php echo $this->baseUrl.'/campaign/Typemap/update/'?> ",
		data: "Name=" +name +"&ID="+id,
		success: function(msg){
			if(msg != ""){
				if(parseInt(msg)==1)
				{
					if(!confirm("Bạn có muốn edit Type: " + name)){
						return false;
					}
				}
				window.location.reload();
			}
			else{
				alert("Update KO thành công");				
			}			
		}
	});	
}

</script>

