<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>
<form id ="form" action="" name="formPaging"  method="post">

<div id="box">
	<h3>Action</h3>
	<table class="filter">
		<tr>
			<td>Action ID</td>
			<td><input style="width:110px;" type="text" name="ActionID" id="ActionID" class="searchbox" /></td>
			<td><input type="submit" name="search" id="button1" class="search" value="search" /></td>
		</tr>
		
		<tr>
			<td>ID</td>
			<td><input type="text" name="questlineid1"  id="questlineid1" style="width:110px;" /></td>
			<td>DESC</td>
			<td><input type="text" name="desc1" id="desc1" /></td>
			<td><input type="submit" name="update" id="button1" class="update" value="Update" /></td>
			<td><input type="submit" name="cancel" id="button1" class="cancel" value="Cancel" /></td>
			<td><input type="submit" name="add" id="button1" class="add" value="Add" /></td>
		</tr>
	</table>
	<table>	
		<tr>
			<table>
				<thead>
				<th width="40"><a href="#">STT</a></th>
				<th width="40"><a href="#">ID</a></th>
				<th>Description</th>							
				<th width="80">Thao tác</th>
				</thead>
				<tr>
					<?php $this->listAction($this->data, $this->page, $this->items, $this) ?>
				</tr>				
			</table>
		</tr>
		
			<div align="center">

				
			</div>
	
	</table>
	<?php echo $this->pagingControl($this->items, $this->page, $this->totalRecord, $this) ?>
</div>
</form>
<script type="text/javascript">
$(function(){
	$(".search").click(function(){
		searchbox=document.getElementById('ActionID').value;
		if(searchbox=='')
		{		
				return false;
		}
		});
});
$(function(){
	/// su mot Quest Line
	
	$(".add").click(function(){
		id = document.getElementById('questlineid1').value;	
		if(id==''){
			return false;
		}
		desc1 = document.getElementById('desc1').value;
		$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/action/add/'?> ",
			data: "desc1=" + desc1 +"&id="+id,
			success: function(msg){
				if(msg != "")
				{					
					alert(msg);
				}
				else
				{
					alert("Update không thành công");
					
				}
				window.location.reload();
			}
		});
		return false;	
	});

	////Them 1 quest line
	

});
$(function(){
	/// su mot Quest Line
	
	$(".update").click(function(){
		id = document.getElementById('questlineid1').value;	
		if(id==''){
			return false;
		}
		desc1 = document.getElementById('desc1').value;
		$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/action/update/'?> ",
			data: "desc1=" + desc1 +"&id="+id,
			success: function(msg){
				if(msg != "")
				{					
					alert(msg);
				}
				else
				{
					alert("Update không thành công");
					
				}
				window.location.reload();
			}
		});
		return false;	
	});

	////Them 1 quest line
	

});


</script>