<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>


<input id="testajax" class="trandinhdoan sdf" type="text" value="" onchange="getvalue('testajax')" title="string-value">
<div id = "string-value" ></div>

<a title="chọn" id="stringadd" class="tool-16 add" href="#" title = "asds" onClick="findstring('testajax','')"></a>
<a title="thêm" id="newstring" class="tool-16 add" href="#" title = "asds" onClick="newstring('testajax','')"></a>

<div id="llightbox" style="position:fixed;top:0;left:0;width:100%;height:100%;z-index:9999;display:none;opacity:0.7;background:#222;"></div>
<div id = "stringmain"   style="position:fixed;top:100px;width:950px;margin:10px auto;z-index:10000;background:#fff;overflow:scroll;display:none;padding:5px;border:15px solid #f4f4f4;border-radius:8px;">
</div>



<script type="text/javascript">
<!--
function getvalue(textbox)
{
	
	tam = $('#'+textbox).val();
	tam1 = tam.split('@');
	$.ajax({
		type: "POST",
		url: '<?php echo $this->baseUrl?>/localite/string/viewkey',
		data: { 
					value : tam1[1]
			  },
		success: function (result) {
			
			tam = result.split('/n/');
			$('#'+$('#'+textbox).attr('title')).html(tam[1]);
		}
		}); 
}
function findstring(textbox,link)
{
	$.ajax({
		type: "POST",
		url: '<?php echo $this->baseUrl?>/localite/string/index?ajax=true&size=10'+link,
		data: { 
					
			  },
		success: function (result) {
			
			tam = result.split('<div id="splip"></div>');
			tam2=tam[1];
			tam2=tam2.replace('<input class="btn search" type="submit" name="search" value="search" />','<a style="padding:4px;border:1px solid #ddd;background:#f8f8f8;" href="#" onClick="searchlink()">Tìm kiếm</a>')
			tam2=tam2.replace("searchlink()","searchlink('"+textbox+"')");
			for(i=0;i<10;i++)
			{
				tam2 = tam2.replace("(testajax,","('"+textbox+"',");
				tam2 = tam2.replace("/n/","'");
			}
			for(i=0;i<10;i++)
				tam2 = tam2.replace("/n/","'");
				tam3 = tam[2].split('"');
				tam4 = tam3[1].split('/n/');
				tam5 = tam4[0]/10;
				i=0;
				for(i=0;i<tam5;i++);
				strf = '<tfoot><tr><td colspan="7" align="center"><a onClick="firstpage(/n/'+textbox+'/n/,/n/'+link+'/n/,1)" href="#"><<</a><a onClick="firstpage(/n/'+textbox+'/n/,/n/'+link+'/n/,'+(tam4[1]-1)+')" href="#" ><</a><a>'+tam4[1]+'/'+i+'</a><a onClick="firstpage(/n/'+textbox+'/n/,/n/'+link+'/n/,'+(tam4[1]-(-1))+')" href="#">></a><a onClick="firstpage(/n/'+textbox+'/n/,/n/'+link+'/n/,'+i+')" href="#">>></a></td></tr></tfoot>';
				for(i=0;i<16;i++)
				{
					strf = strf.replace("/n/","'");
				}
				$('#stringmain').html(tam2+strf);
				showlightbox()
		}
		}); 
}
function addstring(textbox,value)
{
	$('#'+textbox).attr("value",value);
	$('#stringmain').html("");
	getvalue(textbox);
	hidelightbox();
}
function searchlink(textbox)
{
	var id = $('input#ID').val();
	var type = $('select[name=l_Search_type]').val();
	var group = $('select[name=l_group]').val();
	findstring(textbox,"&page=1&l_Search_type="+type+"&S_ID="+id+"&l_group="+group);
}
function firstpage(textbox,link,page)
{
	if(link=='')
		link = '&page=1&l_Search_type=lkey&S_ID=-1&l_group=-1';
	tam = link.split('page=');
	tam1 = tam[1].split('&');
	tam2 = 'page='+tam1[0];
	tam3 = link.replace(tam2,"page="+page);
	findstring(textbox,tam3);
}





$('#llightbox').click(function(){
   	$('#stringmain').hide('slow').css('display','none');
	$('#llightbox').animate({opacity:0},500).css('display','none');
});
function hidelightbox(){
	$('#stringmain').hide('slow').css('display','none');
	$('#llightbox').animate({opacity:0},500).css('display','none');
}
function showlightbox(){
	$('table tfoot td a').css('margin','5px');
	$('#llightbox').css('display','block').css('opacity','0').animate({opacity:0.7},200);
	$('#stringmain').css('display','block');
}
function newstring(textbox,link)
{
	$('input#button1').hide();
	var ham = "addnewstring('"+textbox+"')";
	$.ajax({
		type: "POST",
		url: '<?php echo $this->baseUrl?>/localite/string/insert',
		data: { 

			  },
		success: function (result) {
			tam = result.split('<div id="splip"></div>');
			tam1 = tam[1].replace('<input id="button" type="submit" value="OK">','<a style=" border: 1px solid #C3D7DB;padding:2px 4px;margin:4px;" href="#" title="lưu" onClick="'+ham+'">Lưu</a>');
			tam2 = tam1+'</div></div></div>';
			$('#stringmain').html(tam2);
		}
	}); 
	showlightbox();
}
function addnewstring(textbox){
	var key = $('input#id').val();
	var l_group = $('select#l_group').val();
	var gname = $("select#l_group option[value='"+l_group+"']").text();
	var test = $('textarea[name=test]').val();
	var test1 = $('textarea[name=test1]').val();
	if(test==''||test1==''){alert('Bạn nhập chưa đầy đủ các string vui lòng nhập lại');return;}
	$.ajax({
		type: "POST",
		url: '<?php echo $this->baseUrl?>/localite/string/insert?key='+key+'&l_group='+l_group+'&test='+test+'&test1='+test1,
		data: { 
			  },
		success: function (result) {
			var value = '@'+gname+'#'+key; 
			addstring(textbox,value);
			hidelightbox();
		}
	});
}
function getgroupname(key){
	$.ajax({
		type: "POST",
		url: '<?php echo $this->baseUrl?>/localite/lgroup/getgroupname?id='+key,
		data: { 
			  },
		success: function (result) {
			return result;
		}
	});
}



//-->
</script>
		


