<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>
<form id ="formPaging" name='formPaging' action="" method="post">

<div id="box">
	<h3>Restore</h3>
	<table class="filter">
	</table>
	<table>	
		<tr>
			<table>
				<thead>
				<th width="40"><a href="#">STT</a></th>
				<th width="40"><a href="#">ID</a></th>
				<th ><a href="#">Thời gian </a></th>
				<th width="80">Thao tác</th>
				</thead>
				<tr>
					<?php $this->listRestore($this->data, $this->page, $this->items, $this) ?>
				</tr>				
			</table>
		</tr>
	
	</table>
	<?php echo $this->pagingControl($this->items, $this->page, $this->totalRecord, $this) ?>
</div>
</form>
<script type="text/javascript">
function Trim(sString)
{
	alert("xu ly");
	while (sString.substring(0,1) == ' s')
	{
	sString = sString.substring(1, sString.length);
	}
	while (sString.substring(sString.length-1, sString.length) == ' ')
	{
	sString = sString.substring(0,sString.length-1);
	}
	return sString;
}
function deleteres(key)
{
	
	id = $("#Id-"+key).text();
	time = $("#Type-"+key+" .datatime").text();	
	if(!confirm("Bạn có muốn xóa restore của thời gian "+time+" này không ?")){
		return false;
	};
	$.ajax({
		type: "POST",
		url: "<?php echo $this->baseUrl.'/campaign/restore/delete'?> ",
		data:{
			id:id,
		},
		success: function(msg){
			alert(msg);
			if(msg){	
					
				window.location.reload();
			}
			else{
				window.location.reload();		
			}			
		}
	});	
	
}
function restore(key)
{
	
	id = $("#Id-"+key).text();
	time = $("#Type-"+key+" .datatime").text();	
	if(!confirm("Bạn có muốn restore data lại thời gian "+time+" này không ?")){
		return false;
	};
	$.ajax({
		type: "POST",
		url: "<?php echo $this->baseUrl.'/campaign/restore/restore'?> ",
		data:{
			id:id,
		},
		success: function(msg){
			alert(msg);
			if(msg){	
					
				window.location.reload();
			}
			else{
				window.location.reload();		
			}			
		}
	});	
	
}
</script>

