<?php
return array(
	161 =>
	array(
		'id' => 161,
		'type' => 4,
		'description' => 'Kinh nghiệm nhận được khi mua: 50 exp, hạn dùng 14 ngày.',
		'haveDefault' => 0,
		'name' => 'Mũ bảo hiểm mô tô',
		'image' => 'HatHelmetGlass.png',
		'priceInGame' => 0,
		'priceOutGame' => 24,
		'quantity' => 1,		
		'status' =>  array (0),
		'currentStatus' => 0,
		'key' => 'TRANG_TRI_MU',
		'effect' => array('TRANG_TRI_MU'=>1),
		'level' => 1,
		'limited' => 336,
		'useAtHome' => 0,
		'maxLevel' => -1,
		'exp' => 50,
		'refineLevel' => 0,
        'expiredCoin' => 15,
		'disCount' => 0,		
		'enableInShop' => true,
	 'effectProperties' => array( null, ),
),
	148 =>
	array(
		'id' => 148,
		'type' => 4,
		'description' => 'Kinh nghiệm nhận được khi mua: 50 exp, hạn dùng 14 ngày.',
		'haveDefault' => 0,
		'name' => 'Mũ Chú hề',
		'image' => 'HatChuHe.png',
		'priceInGame' => 0,
		'priceOutGame' => 24,
		'quantity' => 1,		
		'status' =>  array (0),
		'currentStatus' => 0,
		'key' => 'TRANG_TRI_MU',
		'effect' => array('TRANG_TRI_MU'=>1),
		'level' => 24,
		'limited' => 336,
		'useAtHome' => 0,
		'maxLevel' => -1,
		'exp' => 50,
		'refineLevel' => 0,
        'expiredCoin' => 15,
		'disCount' => 0,		
		'enableInShop' => true,
	 'effectProperties' => array( null, ),
),
	147 =>
	array(
		'id' => 147,
		'type' => 4,
		'description' => 'Kinh nghiệm nhận được khi mua: 20 exp, hạn dùng 14 ngày.',
		'haveDefault' => 0,
		'name' => 'Mắt kính violet',
		'image' => 'GlassesChuHe.png',
		'priceInGame' => 0,
		'priceOutGame' => 14,
		'quantity' => 1,		
		'status' =>  array (0),
		'currentStatus' => 0,
		'key' => 'TRANG_TRI_KINH',
		'effect' => array('TRANG_TRI_KINH'=>1),
		'level' => 14,
		'limited' => 336,
		'useAtHome' => 0,
		'maxLevel' => -1,
		'exp' => 20,
		'refineLevel' => 0,
        'expiredCoin' => 15,
		'disCount' => 0,		
		'enableInShop' => true,
	 'effectProperties' => array( null, ),
),
	158 =>
	array(
		'id' => 158,
		'type' => 4,
		'description' => 'Kinh nghiệm nhận được khi mua: 50 exp, hạn dùng 14 ngày.',
		'haveDefault' => 0,
		'name' => 'Mũ Trạng lợn',
		'image' => 'HatTrangLon.png',
		'priceInGame' => 0,
		'priceOutGame' => 24,
		'quantity' => 1,		
		'status' =>  array (0),
		'currentStatus' => 0,
		'key' => 'TRANG_TRI_MU',
		'effect' => array('TRANG_TRI_MU'=>1),
		'level' => 24,
		'limited' => 336,
		'useAtHome' => 0,
		'maxLevel' => -1,
		'exp' => 50,
		'refineLevel' => 0,
        'expiredCoin' => 15,
		'disCount' => 0,		
		'enableInShop' => true,
	 'effectProperties' => array( null, ),
),
	159 =>
	array(
		'id' => 159,
		'type' => 4,
		'description' => 'Kinh nghiệm nhận được khi mua: 20 exp, hạn dùng 14 ngày.',
		'haveDefault' => 0,
		'name' => 'Trâm hoa mai',
		'image' => 'HatHoaMai.png',
		'priceInGame' => 0,
		'priceOutGame' => 14,
		'quantity' => 1,		
		'status' =>  array (0),
		'currentStatus' => 0,
		'key' => 'TRANG_TRI_MU',
		'effect' => array('TRANG_TRI_MU'=>1),
		'level' => 24,
		'limited' => 336,
		'useAtHome' => 0,
		'maxLevel' => -1,
		'exp' => 20,
		'refineLevel' => 0,
        'expiredCoin' => 15,
		'disCount' => 0,		
		'enableInShop' => true,
	 'effectProperties' => array( null, ),
),
	140 =>
	array(
		'id' => 140,
		'type' => 4,
		'description' => 'Kinh nghiệm nhận được khi mua: 50 exp, hạn dùng 14 ngày.',
		'haveDefault' => 0,
		'name' => 'Áo hoa hồng',
		'image' => 'ShirtXiXon.png',
		'priceInGame' => 0,
		'priceOutGame' => 34,
		'quantity' => 1,		
		'status' =>  array (0),
		'currentStatus' => 0,
		'key' => 'TRANG_TRI_AO',
		'effect' => array('TRANG_TRI_AO'=>1),
		'level' => 40,
		'limited' => 336,
		'useAtHome' => 0,
		'maxLevel' => -1,
		'exp' => 50,
		'refineLevel' => 0,
        'expiredCoin' => 15,
		'disCount' => 0,		
		'enableInShop' => true,
	 'effectProperties' => array( null, ),
),
	108 =>
	array(
		'id' => 108,
		'type' => 4,
		'description' => 'Kinh nghiệm nhận được khi mua: 50 exp, hạn dùng 14 ngày.',
		'haveDefault' => 0,
		'name' => 'Áo xanh Thảo Nguyên',
		'image' => 'ShirtVayHawaii.png',
		'priceInGame' => 0,
		'priceOutGame' => 34,
		'quantity' => 1,		
		'status' =>  array (0),
		'currentStatus' => 0,
		'key' => 'TRANG_TRI_AO',
		'effect' => array('TRANG_TRI_AO'=>1),
		'level' => 40,
		'limited' => 336,
		'useAtHome' => 0,
		'maxLevel' => -1,
		'exp' => 50,
		'refineLevel' => 0,
        'expiredCoin' => 15,
		'disCount' => 0,		
		'enableInShop' => true,
	 'effectProperties' => array( null, ),
),
	160 =>
	array(
		'id' => 160,
		'type' => 4,
		'description' => 'Kinh nghiệm nhận được khi mua: 50 exp, hạn dùng 14 ngày.',
		'haveDefault' => 0,
		'name' => 'Áo Tím hoa sim',
		'image' => 'ShirtHoaSim.png',
		'priceInGame' => 0,
		'priceOutGame' => 34,
		'quantity' => 1,		
		'status' =>  array (0),
		'currentStatus' => 0,
		'key' => 'TRANG_TRI_AO',
		'effect' => array('TRANG_TRI_AO'=>1),
		'level' => 40,
		'limited' => 336,
		'useAtHome' => 0,
		'maxLevel' => -1,
		'exp' => 50,
		'refineLevel' => 0,
        'expiredCoin' => 15,
		'disCount' => 0,		
		'enableInShop' => true,
	 'effectProperties' => array( null, ),
),
	82 =>
	array(
		'id' => 82,
		'type' => 3,
		'description' => 'Kéo dài tuổi thọ heo thêm 20 ngày. Mỗi con heo chỉ được dùng 1 lần.',
		'haveDefault' => 0,
		'name' => 'Heo sâm đặc biệt',
		'image' => 'IncreaseAge.png',
		'priceInGame' => 0,
		'priceOutGame' => 129,
		'quantity' => 1,		
		'status' =>  array (0),
		'currentStatus' => 0,
		'key' => 'TANG_TUOI_THO',
		'effect' => array('TANG_TUOI_THO'=>1728000),
		'level' => 0,
		'limited' => 0,
		'useAtHome' => 1,
		'maxLevel' => -1,
		'exp' => 0,
		'refineLevel' => 0,
        'expiredCoin' => 15,
		'disCount' => 0,		
		'enableInShop' => true,
	),
	123 =>
	array(
		'id' => 123,
		'type' => 3,
		'description' => 'Tăng 9% khả năng ra x-heo.',
		'haveDefault' => 0,
		'name' => 'Thuốc x-heo cấp 4',
		'image' => 'IconHolyMedicine4.png',
		'priceInGame' => 0,
		'priceOutGame' => 19,
		'quantity' => 1,		
		'status' =>  array (0),
		'currentStatus' => 0,
		'key' => 'HOLY_MEDICINE',
		'effect' => array('HOLY_MEDICINE'=>9),
		'level' => 0,
		'limited' => 0,
		'useAtHome' => 0,
		'maxLevel' => -1,
		'exp' => 0,
		'refineLevel' => 4,
        'expiredCoin' => 15,
		'disCount' => 0,		
		'enableInShop' => true,
	),
	124 =>
	array(
		'id' => 124,
		'type' => 3,
		'description' => 'Tăng 12% khả năng ra x-heo.',
		'haveDefault' => 0,
		'name' => 'Thuốc x-heo cấp 5',
		'image' => 'IconHolyMedicine5.png',
		'priceInGame' => 0,
		'priceOutGame' => 69,
		'quantity' => 1,		
		'status' =>  array (0),
		'currentStatus' => 0,
		'key' => 'HOLY_MEDICINE',
		'effect' => array('HOLY_MEDICINE'=>12),
		'level' => 0,
		'limited' => 0,
		'useAtHome' => 0,
		'maxLevel' => -1,
		'exp' => 0,
		'refineLevel' => 5,
        'expiredCoin' => 15,
		'disCount' => 0,		
		'enableInShop' => false,
	),

);
?>