<div id="box">
    <h3>Danh sách shop</h3>
    <div>
        <table id="tblList"></table>
        <div id="pager"></div>
    </div>
</div>

<script type="text/javascript">
    $("document").ready(function()
    {
        /*================ START JQGRID SCRIPT ===============*/
        $('#tblList').jqGrid({
            url:'<?php echo $this->baseUrl?>/ibshop/getshop',
            editurl:'<?php echo $this->baseUrl?>/ibshop/operationshop',
            mtype: 'POST',
            datatype: 'json',
            colNames:["ID","Shop Id","Name"],
            colModel:[
                {name:"id",index:"id",key:true,width:40,editable:false,hidden:true},
                {name:"shop_id_text",index:"shop_id_text",width:200,editable:true, editrules:{required:true},"formoptions": {elmsuffix: ' *'}},
                {name:"name",index:"name",width:300,editable:true, edittype:'checkbox'},
            ],
            rowNum:20,
            rowList:[10,20,30,60,100],
            pager: '#pager',
            shrinkToFit: false,
            rownumbers:true,
            hidegrid:false,
            emptyrecords: "No records.",
            autoheight: true,
            autowidth: true,
            toppager:true,
            viewrecords: true,
            caption: "Danh sách shop",
            subGrid: true,
            subGridRowExpanded: function(subgrid_id, row_id) {
                subgrid_table_id = subgrid_id+"_t";
                subgrid_pager_id = "p_"+subgrid_id;  
                jQuery("#"+subgrid_id).html("<table id='"+subgrid_table_id+"' class='scroll'></table><div id ='"+ subgrid_pager_id + "' class='scroll'></div>");
                jQuery("#"+subgrid_table_id).jqGrid({
                    url:'<?php echo $this->baseUrl?>/ibshop/listtab',
                    editurl:'<?php echo $this->baseUrl?>/ibshop/operationtab',
                    mtype: 'POST',
                    datatype: 'json',
                    postData:{
                        shop_id: function() {return row_id;}
                    },
                    colNames: ['id','shop_id','Type','Name','Position','Status'],
                    colModel: [
                        {name:"id",index:"id",width:80,key:true,hidden:true},
                        {name:"shop_id",index:"shop_id",width:80,hidden:true, editable:true, editoptions:{defaultValue:row_id}},
                        {name:"type",index:"type",width:120,editable:true, hidden:false, edittype:'select', formatter:'select', 
                            editoptions:{value:{<?php foreach ($this->data['itemType'] as $item)
                                                {
                                                    echo $item['id'].':\''.$item['name'].'\',';
                                                }
                                                ?>}}},
                        {name:"name",index:"name",width:200,editable:true, hidden:false},
                        {name:"position",index:"position", width:120,editable:false, hidden:true, editable:true},
                        {name:"status",index:"status",width:120,editable:true, edittype:'select', hidden:false, formatter:'select',
                            editoptions:{value:{<?php foreach ($this->data['tabStatus'] as $item)
                                                {
                                                    echo $item['id'].':\''.$item['name'].'\',';
                                                }
                                                ?>}}},
                    ],
                    emptyrecords: "No records.",
                    height: "100%",
                    autowidth: false,
                    rowNum:20,
                    sortorder: "asc",
                    pager: subgrid_pager_id
                }).jqGrid('navGrid',"#"+subgrid_pager_id,
                    {
                        search:false,edit:true,add:true,del:true,cloneToTop:true}, 
                        editSettings1,
                        addSettings1
                    );
            }
        }).jqGrid('navGrid','#pager',
            {search:false,edit:true,add:true,del:true,cloneToTop:true}, //options
            editSettings1, 
            addSettings1
        ).setGridHeight(450,true);
        /*================ END JQGRID SCRIPT ===============*/
    });
    
    
    var editSettings1 = {
        width: 400,
        beforeShowForm:function(){
            var selRowId = $("#tblList").jqGrid('getGridParam', 'selrow');
            var rowData = $("#tblList").getRowData(selRowId);
            var reason = rowData['Reason'];
            if (reason == '<?php echo AppConstant::COMPENSATION_REASON_KHAC?>')
            {
                $('#tr_ReasonDesc').show();
            }
            else
            {
                $('#tr_ReasonDesc').hide();
            }
        }
    };

    var addSettings1 = {
        recreateForm:true, 
        width: 400,
        modal:false,
        reloadAfterSubmit:true,
        closeOnEscape:true,
        saveKey:[true,13],
        closeAfterEdit:true,
        top:0,
        beforeShowForm:function(){
            $('#tr_ReasonDesc').hide();
        }
    };
</script>