<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>
<style>
#insertstring>div>div
{
	padding: 5px;
}
#insertstring>div>div>div
{
	padding: 5px;
}
#insertstring>div>div>div>div#idlabel
{
	width:60px;
	float:left;
}
#insertstring>div>div>div>select
{
	width:150px;
}
#insertstring>div>div>div>input#button
{
	margin-left:60px;
}
</style>
<form id="insertstring" class="myform" action="" name="string" method="post">
<div id="box">
<h3>Insert Language</h3>
	<div id='body'>
		<div>
			<div id = 'idlabel'><label for="street">Key : </label></div>
			<input readonly="readonly" id="id" type="text" tabindex="1" value="<?php echo $_REQUEST['key'];?>" name="key">
		</div>
		<div>
			<div id = 'idlabel'><label for="street">Group : </label></div>
			<input readonly="readonly" id="id" type="text" tabindex="1" value="<?php echo $this->string->getGroupbyid($_REQUEST['group']);?>" name="l_group">
		</div>
		<div>
			<div id = 'idlabel'><label for="street"><?php echo $this->string->getlangdefault();?> : </label></div>
			<textarea rows="3" cols="30" name="test"><?php if($this->test==-1) echo $this->string->getTextBylang($this->string->getlangdefaultid(),$_REQUEST['key'],$_REQUEST['group']);else echo $this->test;?></textarea>
		</div>
		<div>
			<div id = 'idlabel'><label for="street"><?php echo $this->string->getlangindex();?> : </label></div>
			<textarea rows="3" cols="30" name="test1"><?php if($this->test1==-1) echo $this->string->getTextBylang($this->string->getlangindexid(),$_REQUEST['key'],$_REQUEST['group']);
															else echo $this->test1;?></textarea>
		</div>		
		<div>
			<input id="button" type="submit" value="OK">
			<input id="button1" type="button" onclick="history.go(-1)" value="Quay lại">
		</div>
	</div>
</div>
</form>

