<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>

<form id="Item" class="myform" action="" method="post">
<div class="mybox">
	<h3>Item</h3>
	<table class="filter" style="width: 80%;margin: auto;margin-bottom: 20px;margin-top: 10px";>	
		<tr>
			<td>ID</td>
			<td><input id="itemID"  readonly class="disabled" name="itemID" type="text" style="width:110px;" /></td>
			<td>Name
			<input id="itemName" type="text" name="itemName"/>
				<a class="btn save disabled " href="">Save</a>
				<a class="btn add disabled " href="">Add</a>
				<a class="btn cancel disabled " href="">Cancel</a>
			</td>
		</tr>
	</table>
	<table class="list" id="list_Item" style="width: 80%;margin:auto ;border: 1px solid;">	
		<thead>
			<tr>									
				<td width="40"><a href="#">ID</a></td>
				<td>Name</td>		
				<td>NameSV</td>						
				<td class="center" width="80">Action</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<?php
		$strList .= "<tbody>";
			foreach($this->data as $key =>$row){				
								
				$edit = "<a class='tool-16 edit' href='javascript:editItem($key)'></a>";				
				$delete = "<a class='tool-16 delete' href='javascript:deleteItem($key)'></a>";;								
				$strList .= "<tr id='Item-$key'>							
								<td class='id'>$row->ID</td>	
								<td class='name'>$row->Name</td>	
								<td class='nameSV'>$row->NameSV</td>					
								<td align='center'>								
									$edit&nbsp								
									$delete								
								</td>
							</tr>";
			}
		$strList .= "</tbody>";
		echo $strList; 
		?>
			</tr>
		</tbody>						
	</table>	
	
	<div align="center" style="margin: 20px;">		
		
	</div>
</div>

</form>
<div id="ed">
</div>
<script type="text/javascript">
$("a.btn.disabled").click(function(){
	//alert("disabled");
	return false;
});


$(function(){	
////////////////click Cancel//////////////////////////
	$(".btn.cancel").click(function(){
		if($(".btn.cancel").hasClass('disabled')){			
 	 	}else{
 	 		document.getElementById('itemID').value = '';
 	 		document.getElementById('itemName').value = '';
 	 		disable($(".btn.add"));
			disable($(".btn.save"));
			disable($(".btn.cancel"));
 	 	}
 	 	return false;
 	});
	
///////////////////Input Event///////////////////////////
	$("#itemName").keyup(function(e){
		var id = $("#itemID").val();
		var name = $("#itemName").val();
		
		if(name == ''){
			disable($(".btn.add"));
			disable($(".btn.save"));
		}else{	
			enable($(".btn.cancel"));					
			if(id != ''){
				disable($(".btn.add"));
				enable($(".btn.save"));				
			}else{
				enable($(".btn.add"));
				disable($(".btn.save"));
			}
		}		
	});	
///////////////Save click/////////////////
	$(".btn.save").click(function(){
		if($(this).hasClass("disabled")){
			return false;
		}
		updateItem();			
	});		

	$(".btn.add").click(function(){
		if($(this).hasClass("disabled")){
			return false;
		}
		updateItem();
	});
});

function editItem(key){
	id = $("#Item-"+key+" .id").text();
	name = $("#Item-"+key+" .name").text();
	document.getElementById('itemID').value = id;
	document.getElementById('itemName').value = name;
	if($(".btn.save").hasClass('disabled')){
		$(".btn.save").removeClass("disabled");		
	}
	if($(".btn.cancel").hasClass('disabled')){
		$(".btn.cancel").removeClass("disabled");		
	}
	if(!$(".btn.add").hasClass('disabled')){
		$(".btn.add").addClass("disabled");
	}
}
/*******click delete button***********/
function deleteItem(key){
	id = $("#Item-"+key+" .id").text();
	name = $("#Item-"+key+" .name").text();
	if(!confirm("Bạn có muốn xóa Item: " + name)){
		return false;
	};
	$.ajax({
		type: "POST",
		url: "<?php echo $this->baseUrl.'/shop/item/delete/'?> ",
		data: "ID="+id,
		success: function(msg){
			if(parseInt(msg)==1)
			{			
				window.location.reload();
			}
			else{
				window.location.reload();
			}		
		}
	});	
	
}
function updateItem(){
	var id = $("#itemID").val();
	var name = $("#itemName").val();
	$.ajax({
		type: "POST",
		url: "<?php echo $this->baseUrl.'/shop/item/update/'?> ",
		data: "Name=" +name +"&ID="+id,
		success: function(msg){
			if(msg != ""){
				if(parseInt(msg)==1)
				{
					if(!confirm("Bạn có muốn edit Item: " + name)){
						return false;
					}
				}
				window.location.reload();
			}
			else{
				alert("Update KO thành công");				
			}			
		}
	});	
}

</script>

