<!--<script src="<?php echo $this->baseUrl.DS.MEDIA_JS.DS; ?>jquery-1.4.4.min.js"></script>-->

<script type="text/javascript" src="<?php echo $this->baseUrl ?>/media/scripts/jquery-1.4.4.min.js"></script>
<script type="text/javascript">
$("document").ready(function()
{
	$("title").html("Danh sách ngoại trang");
	$("#postform").submit(function()
	{
		return confirm("Bạn có muốn xóa không ?");
	});
});

function ItemDetail(id)
{
	parent.location = "<?php echo $this->baseUrl ?>/shopeditor/" + "itemdetail?id=" + id;
}

function SelectAll(checkboxall)
{
	$(".deletecheckbox").attr("checked", checkboxall.checked);
}

function Page(url, page)
{
	var link;
	
	if(url.indexOf('?') == -1)
	{
		link = url + "?page=" + page;
	}
	else
	{
		link = url + "&page=" + page;
	}
	
	parent.location = link;
}

function ExportItem()
{
    parent.location = "<?php echo $this->baseUrl ?>/shopeditor/exportitem";
}
</script>

<style>
.text
{   
    background-color: #FFFF80;
    font-weight: bolder;
}

.editbox
{
	width: 150px;
	margin: 5px 5px 5px 5px;
}

.combobox
{
	width: 50px;
	margin: 1px 1px 1px 1px;
}

.comboboxName
{
    border:1px #999 solid;
    padding: 6px 10px; 
    margin:2px 0; 
    font-size:1.3em; 
    color:#666; 
    font-family:Verdana, Geneva, sans-serif;
}
</style>

<div id="header">Danh sách ngoại trang</div>

<div id="main">
    <form id="form" action="" method="get" >
    <table class="centerTable" border="0" style="margin-bottom: 20px;">
        <tr align="center">            
            <td width="50px" style="text-align: center;padding: 0 0">
                <input style="width: 100px;" type="submit" id="button1" value="Export item" name="exportItem" />
                <input style="width: 70px;" type="submit" id="button2" value="Sync" name="Sync" />
            </td>
            <td width="80px" style="text-align: center;">Tên ngoại trang:
                <input type="text" class="editbox" name="searchName" />
            </td>
            <td width="80px" style="text-align: center;">Loại ngoại trang:
	            <select class="combobox2" name="searchType">
                    <option value="0"></option>
	            	<option value="1">Thực phẩm</option>
	            	<option value="2">Ngoại cảnh</option>
	            	<option value="3">Vật phẩm bổ trợ</option>
	            	<option value="4">Ngoại trang</option>
	            	<option value="6">Vật phẩm tinh luyện</option>	          
                    <option value="7">Vật phẩm trung thu</option>              
                    <option value="8">Gói giảm giá</option>              
				</select>
			</td>
				
            <td width="50px">
                <input style="width: 50px;" type="submit" value="Tìm" name="search" />
                <input style="width: 50px;" type="submit" value="All" name="searchAll" />
            </td>
        </tr>
    </table>
    </form>
	
    <form id="postform" action="" method="post">
	<table class="centerTable" border="1px">
		<thead>
		<tr align="center">
			<!--<th width="50px"><input type="checkbox" onchange="SelectAll(this);" /></th>-->
			<th width="50px">Hình</th>
			<th width="150px">Tên</th>
			<th width="50px">Giá bán</th>
            <th width="50px">Đơn vị</th>
            <th width="50px">Bán trong shop</th>
            <th width="50px">% giảm giá</th>
			<th width="75px">Thao tác</th>
		</tr>
		</thead>
		<tbody>
		<?php
		for($i = 0; $i < count($this->dislayData); $i++)
		{
            $imgUrl = $this->baseUrl."/media/images/item/". $this->dislayData[$i]->image;
			/*$imgUrl = $this->baseUrl.DS.MEDIA_LOCALDATA_IMG_ITEM.DS.$this->dislayData[$i]->image;*/
			//<td width='50px'><input class='deletecheckbox' name='checkbox[]' type='checkbox' value='{$this->dislayData[$i]->id}' /></td>
            
            $price = $this->dislayData[$i]->priceInGame ;
            $unitPrice = "vàng" ;
            if( $this->dislayData[$i]->priceOutGame > 0 )
            {
                $price = $this->dislayData[$i]->priceOutGame ;
                $unitPrice = "xu" ;
            }
            
            $enableInShop = "không" ;
            if( $this->dislayData[$i]->enableInShop )
            {
                $enableInShop = "có" ;
            }
            
			echo "
				<tr align='center'>					
					<td width='50px'><img src='$imgUrl' /></td>
					<td width='150px'>{$this->dislayData[$i]->name}</td>
					<td width='50px'>{$price}</td>
                    <td width='50px'>{$unitPrice}</td>
                    <td width='50px'>{$enableInShop}</td>
                    <td width='50px'>{$this->dislayData[$i]->disCount}</td>
					<td width='75px'><a href='javascript:;' title='Sửa' onclick='ItemDetail({$this->dislayData[$i]->id})'><img src='$this->baseUrl/media/images/icons/edit-icon.gif' /></a></td>
				</tr>";
		}
		?>
		<tr align="center">			
			<td colspan="5">
				<?php
				if($this->TotalPage > 1)
				{
					$url = $this->baseUrl."/shopeditor/item";
				
					echo "<table border='1px'>
							<tr>
								<td>
									Page:&nbsp;
									<select name='page' id='pageselection' onchange='Page(\"$url\", this.selectedIndex + 1);'>";
										for($i = 1; $i <= $this->TotalPage; $i++)
										{
											if($i == $this->CurPage)
											{
												echo "<option SELECTED value='$i'>$i</option>";
											}
											else
											{
												echo "<option value='$i'>$i</option>";
											}
										}
					echo "
									</select>
									/ $this->TotalPage
								</td>
							</tr>
						</table>";
				}
				?>
			</td>
		</tr>
		</tbody>
	</table>
	</form>	
</div>