<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>
<style>
.soldier{
	width: 40px;
}
table#battle{
	border:1px solid; 	
}

table#battle input{	
	overflow: hidden;
	margin-top: 2px;
	margin-bottom: 2px;
}

table#battle .hidden{
	opacity:0.3;
}
table#battle td{
	margin: 0;
	overflow: hidden;
	vertical-align: middle;
}
.c_order input{
	width:30px;
	text-align:center; 
}
/**************Table Layout********************/
 table#tb_layout{
	border-collapse: separate;
	border-spacing: 10px;
 }
table#tb_layout td select, table#tb_layout td input{
	border:none;
	max-width: 200px;	
	overflow: hidden;
	background-color: #D9EAED;
	padding:0px;
	margin: 0px;
}
table#tb_layout td select{
	width: 70%;
	float: left;
}
table#tb_layout td input{
	width: 22%;	
}
table#tb_layout td.invisible,table#tb_layout td.invisible *{	
	opacity:0.0;
}

table#tb_layout td.visible,table#tb_layout td.visible *{
	background: #EFEFEF;	
	opacity:1.0;
    color: blue;
}
table#tb_layout td.visible{
	border: 2px solid lightblue;
}


/**************End Table Layout****************/
.style{
	margin: auto;text-align: center;padding-top: 2px;padding-bottom: 2px;
}


</style>
<form  class="myform" id="formPaging" name="formPaging" action="" method="post">
<div class='mybox'>
	<h3>Campaign Edit</h3>
	<table>
	<tr>
		<td>
			<label>World Map:</label>
			<input type="text" readonly="readonly" value='<?php echo $this->campaignId[0]->WorldMap;?>' name='nextCampaign' id='nextCampaign'/>
		</td>
		<td>
			<label>Select Campaign:</label>			
			<select name='campaignID' id='campaignID'>							
				<?php echo $this->options($this->arrCampaign,$this->campaign->ID,array('key'=>"ID",'name'=>"Name"))?>				
			</select>
		</td>			
		<td>
			<label>Campaign Name:</label>
			<input type="text" name='Name' id='Name' value='<?php echo $this->campaign->Name;?>' />
		</td>
		
		</tr>
	</table>
	<h3>Battle</h3>	

	<table class="list" id='battle'>
		<thead>
			<tr>
				<td width="15px">ID</td>
				<td width="15px" class="center"><a onclick="order();" href='#'>Order</a></td>
				<td width="600px" class="center">Layout</td>
				<td>Award</td>
				<td class="center" width="20px">Action</td>
			</tr>
		</thead>
	<tbody id="campaign">	
	<?php foreach ($this->arrbattle as $rowbattle){?>
		<tr class='battle' id='battle-<?php echo $rowbattle->ID?>'>
			<td><?php echo $rowbattle->ID;?><input style="display:none" type="text" id='BattleID' name='BattleID' value='<?php echo $rowbattle->ID;?>'/></td>

			<td class="center c_order">
				<input type="text" name='Order' id='Order' value='<?php echo $rowbattle->Order;?>'/>
			</td>
			<td width="300px" style="text-align: center;">
				
				<select style="width=100%;border: 2px solid lightblue;" id="Layout" name="Layout" tabindex="2">
					<?php echo $this->options($this->arrlayout,$rowbattle->Layout,array('key'=>"ID",'name'=>"Name"))?>
					<option  value="insert" style="color:red"> New Layout</option>	
				</select>
				<br/>
				
				<table id='tb_layout'>
					<tr>
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][0])?"visible":"invisible"?>
						<td id="point0" class="<?php echo  $strclass?>">
							<?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],0);
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[0]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>												
												
							lv:<input type='text' class='<?php echo $strclass?>_0' id='levelSolider' name='levelSolider[0]' value="<?php echo $arrBS['Level'];?>"/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][3])?"visible":"invisible"?>
						<td id="point3" class="<?php echo  $strclass?>" >
							<?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],3); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[3]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							lv:<input type='text' class='<?php echo $strclass?>_3' id='levelSolider' name='levelSolider[3]' value="<?php echo $arrBS['Level'];?>"/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][6])?"visible":"invisible"?>
						<td id="point6" class="<?php echo  $strclass?>" >
							<?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],6); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[6]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							lv:<input type='text' class='<?php echo $strclass?>_6' id='levelSolider' name='levelSolider[6]' value='<?php echo $arrBS['Level'];?>'/>
						</td>						
					</tr>
					<tr>
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][1])?"visible":"invisible"?>
						<td  id="point1" class="<?php echo  $strclass?>" >
							<?php  $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],1); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[1]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							lv:<input type='text' class='<?php echo $strclass?>_1' id='levelSolider' name='levelSolider[1]' value='<?php echo $arrBS['Level'];?>'/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][4])?"visible":"invisible"?>
						<td  id="point4"class="<?php echo  $strclass?>" >
							<?php  $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],4); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[4]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							lv:<input type='text'class='<?php echo $strclass?>_4' id='levelSolider' name='levelSolider[4]' value='<?php echo $arrBS['Level'];?>'/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][7])?"visible":"invisible"?>
						<td  id="point7"class="<?php echo  $strclass?>" >
							<?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],7);
							 echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[7]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							lv:<input type='text' class='<?php echo $strclass?>_7' id='levelSolider' name='levelSolider[7]' value='<?php echo $arrBS['Level'];?>'/>
						</td>
					</tr>
					<tr>
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][2])?"visible":"invisible"?>
						<td id="point2" class="<?php echo  $strclass?>" >
							<?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],2); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[2]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							lv:<input type='text' class='<?php echo $strclass?>_2' id='levelSolider' name='levelSolider[2]' value='<?php echo $arrBS['Level'];?>'/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][5])?"visible":"invisible"?>
						<td id="point5" class="<?php echo  $strclass?>" >
							<?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],5); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[5]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							lv:<input type='text' class='<?php echo $strclass?>_5' id='levelSolider' name='levelSolider[5]' value='<?php echo $arrBS['Level'];?>'/>
						</td>
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][8])?"visible":"invisible"?>
						<td id="point8" class="<?php echo  $strclass?>" >
							<?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],8); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider[8]",
												array('key'=>"ID",'name'=>"Name",'default'=>""))?>
							lv:<input type='text' class='<?php echo $strclass?>_8' id='levelSolider' name='levelSolider[8]' value='<?php echo $arrBS['Level'];?>'/>
						</td>
					</tr>
				</table>
			</td>
			<td width="200px">
			<div id='div-battle-award-<?php echo $rowbattle->ID;?>'>				
				<a href='javascript:addAward(<?php echo $rowbattle->ID?>)' class='ico-16 add' ></a><br>
				<?php foreach ($this->arraward[$rowbattle->ID] as $key=>$row){?>
					<div class="award-<?php echo $rowbattle->ID?>" id="div-list-award-<?php echo $key ?>">
					<select id='<?php echo $row->ID?>' name='AwardTypeID[]' onChange='updateAward(this)'>
						<?php if (empty($row->AwardTypeID)){?>
							<option value="" style="color:red"></option>
						<?php } ?>	
						<?php echo $this->options($this->arrawardtype,$row->AwardTypeID,array('key'=>'AwardTypeID','name'=>'Name'))?>
						<option  value="insert" style="color:red">New Type</option>
					</select>					
					<input type='text' class='soldier' id='Value' name='Value[]' value='<?php echo $row->Value?>'/>
					
					<a class='tool-16 delete' href='javascript:removeAward(<?php echo $rowbattle->ID.",".$key?>)'>&nbsp;</a>	
					</div>
				<?php }?>
			</div>
			</td>
			<td class="center">
			<a class='tool-24 save' id="" href='javascript:saveBattle(<?php echo $rowbattle->ID ?>)'></a><br><br>
			<a class='tool-24 reset' href='javascript:resetBattle(<?php echo $rowbattle->ID ?>)'></a><br><br>
			<a class='tool-24 delete' id="" href='javascript:deleteBattle(<?php echo $rowbattle->ID ?>)'></a>
			</td>
		</tr>
		</tbody>	
		<?php }?>
	
	</table>
	<div class="style" style="margin:20px">
		<a class="btn add" href="javascript:addBattle()">New A Battle</a>	
		<a class="btn save" href="javascript:saveAll()">Save All</a>

	</div>
</div>
</form>
<!-- Dung de them 1 award -->
<div style="display: none">
	
	<div id="optionAwardType">
		<?php echo "<option selected value='' style='color:red'></option>"?>
		<?php echo $this->options($this->arrawardtype,0,array('key'=>'AwardTypeID','name'=>'Name'))?>	
		<?php echo "<option  value='insert' style='color:red'> New Type</option>"?>		
	</div>
</div>
<!--  -->
<!-- Dialog Dung de Show loi~-->
<div id='dialog'>
	<div id='ct'></div>
	<div id='ft'> </div>
</div>
<!--  -->

<!-- Dialog Them AwardType~-->
<div style='display:none' id='insert-awardtype'>
	<?php foreach($this->arrawardtype as $value){?>
		<p id="p-type-<?php echo $value->AwardTypeID?>)">
		ID:<?php echo $value->AwardTypeID?><input type="text" name="awardtype[]" id="awardtype[]" value="<?php echo $value->Name?>"/>
		<a class='tool-16 delete' href='javascript:deleteAwardType(<?php echo $value->AwardTypeID?>)'>&nbsp;</a>	
		</p>			
	<?php }?>
	<p id="p-new-type">
		New<input  type="text" id="awardtype" name="awardtype" value="AwardType" />
		<a class='tool-16 add' href='javascript:addAwardType(<?php echo $value->AwardTypeID?>)'>&nbsp;</a>
	</p>
	
	
	
</div>
<!--  -->

<!-- Dialog Them Layout-->

<div style='display:none'  id='insert-layout'>
<form  id="layout" name="layout" action="" method="post">
	<table>
		<tr>
			<td colspan="3">
			Tên layout :<input type="text" name="namelayout">
			</td>
		</tr>
		<tr>
			<td>1<input type="checkbox" name="point" value="0" /></td>
			<td>4<input type="checkbox" name="point" value="3" /></td>
			<td>7<input type="checkbox" name="point" value="6" /></td>
		</tr>
		<tr>
			<td>2<input type="checkbox" name="point" value="1" /></td>
			<td>5<input type="checkbox" name="point" value="4" /></td>
			<td>8<input type="checkbox" name="point" value="7" /></td>
		</tr>
		<tr>
			<td>3<input type="checkbox" name="point" value="2" /></td>
			<td>6<input type="checkbox" name="point" value="5" /></td>
			<td>9<input type="checkbox" name="point" value="8" /></td>
		</tr>
	</table>
</form>	
</div>

<!--  -->
<script>
///////////////ThaoNX/////////////////////
	////////////////////////////////
	function addAward(key)
	{		
		var count = $(".award-"+ key).size();
		var options = $("#optionAwardType").html();
		var input = " <input type='text' class='soldier' id='Value' name='Value[]' value=''/>";
		var btnDelete = " <a class='tool-16 delete' href='javascript:removeAward("+key+","+count+")'>&nbsp</a>"	;
		var select = "<div class='award-"+key+"' id='div-list-award-"+count+"'><select name='AwardTypeID[]' onChange='updateAward(this)' >"+options+"</select>"+input+btnDelete+"</div>";
		$("#div-battle-award-"+key).append(select);
	}
	/////////////////////////////
	function removeAward(battleID,key)
	{
		$("#div-battle-award-"+battleID+ " #div-list-award-"+key).html("");
	}
	/////////////////////////
	function saveAward(key)
	{
		var data = $("#div-battle-award-"+key+" *").serialize();
		data += "&Action=update-all&BattleID="+key+"";
		$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/campaign/campaign/updateaward'?> ",
			data: data,
			success: function(msg){
				if(msg == '1'){					
					alert("Successfull");
				}else{
					alert("Error");					
				}
				window.location.reload();
			}
		});
	}
	////////////////////////////////
	function saveBattle(key)
	{
		var data = $("#battle-"+key+" *").serialize();
		var camID = $("#campaignID").val();
		data += "&campaignID="+camID;		
		$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/campaign/battle/save'?> ",
			data: data,
			success: function(msg){	
				if(msg == '1'){					
					alert("Successfull");
				}else{
					alert(msg);					
				}				
			}
		});		
	}
	///////////////////////////////
	function deleteBattle(key)
	{	
		if(!confirm("Delete Battle ID: "+key)){
			return false;
		}
		$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/campaign/battle/delete'?> ",
			data: {
				BattleID:key
			},
			success: function(msg){				
				if(msg == '1'){					
					alert("Successfull");
					$("#battle-"+key+" *").remove();
				}else{
					alert("Error");					
				}
				
			}
		});
	}
	function resetBattle(key){
		if(!confirm("Reset???")){
			return false;
		}
		$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/campaign/battle/getinfo'?> ",
			data: {
				BattleID:key
			},
			success: function(msg){				
				alert(msg);
			}
		});
	}
	///Save All////
	function saveAll(){
		$("#dialog #ct").html("");
		var camID = $("#campaignID").val();
		var name = $("#Name").val();
		test=validate();
		if(test==false)
		{
			$("#dialog").dialog({			
				height: 400,
				width: 350,
				modal: true,
				buttons: {
					"Continue": function() {								
						$(this).dialog("close");						
					}										
				}
				});		
		}
		else
		{
			$.ajax({
				type: "POST",
				url: "<?php echo $this->baseUrl.'/test/testpost'?> ",
				data: {
					ID:camID,
					Name:name,				
				},
				success: function(msg){	
					$("#dialog #ct").append("<p class='msg'>"+msg+"<p>");
					$(".battle").each(function(index){			
							data = ($(this).find("*").serialize());						
							data += "&campaignID="+camID;		
							$.ajax({
								type: "POST",
								url: "<?php echo $this->baseUrl.'/campaign/battle/save'?> ",
								data: data,
								success: function(msg){				
									if(msg == '1'){					
										$("#dialog #ct").append("<p class='msg'>Successful<p>");
									}else{
										$("#dialog #ct").append("<p class='error'>"+msg+"<p>");					
									}					
								}
							});
					});		
				}		
				
			});	
			$("#dialog").dialog({
					title: "Updating",
					height: 400,
					width: 350,
					modal: true,
					buttons: {
						"Continue": function() {								
							$(this).dialog("close");						
						},
						"Refresh": function() {								
							$(this).dialog("close");
							window.location.reload();	
						}	
					}
			});
		}
	}
	///Add battle///
	function addBattle()
	{
		var camID = $("#campaignID").val();
		var data = "campaignID="+camID;
		$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/campaign/battle/add' ?> ",
			data: data,
			success: function(msg){	
				alert ("Thành công");	
				window.location.reload();
			}
		});
	}
	
///////////////End-ThaoNX/////////////////////
	////////////////////////////
	function addAwardType(key){
		alert("chua lam");
	}
	function updateAward(element)
	{
		var selected = element.value;
		if(selected == "insert"){
			$("#insert-awardtype").dialog({
				title: "New AwardType",
				height: 400,
				width: 250,
				modal: true,
				buttons: {
					"Save": function() {
						var award = $('#awardtype').val();
						alert(award);
						$.ajax({
							type: "POST",
							url: "<?php echo $this->baseUrl.'/campaign/AwardType/insert' ?> ",
							data: "award=" + award,
							dataType: "json",
							success: function(smg){	
								//smg là json có giá trị là awart_type lớn nhất.
								alert('Thành Công');							
							}
						});	
						$(this).dialog("close");				
					}											
				}
			});		
		}
	}
	///////////////////////////
	$(document).ready(function(){			
			//$("td.invisible").addClass('an');
			$("td.invisible").find("select").attr('disabled','disabled');
			$("td.invisible").find("input").attr('disabled',true);
			//$("td.visible").addClass('hien');
			
			////////////////ThaoNX/////////////////////
			$(".tool-24.disabled").click(function(){
				//alert("disabled");				
				//return false;
			});		
	});
	////////////Layout////////
	$('select#Layout').change(function(){
		
		var battleID=$(this).parent().parent().find("#BattleID").val();			
		var layoutID=$(this).val();		
		if(layoutID=="insert"){
			$("#insert-layout").dialog({
				title: "New Layout",
				height: 250,
				width: 220,
				modal: true,
				buttons: {
					"Save": function() {
						var arraytemp = new Array();
						var name = document.layout.namelayout.value;
						c_value = "[";
						for (var i=0; i < document.layout.point.length; i++)
						{
							if (document.layout.point[i].checked)
						    {
								arraytemp[i] = 1;
						    }
							else
							{
								arraytemp[i] = 0;
							}
						}
						c_value += arraytemp[0]+','+arraytemp[3] +','+ arraytemp[6] + ','+ arraytemp[1] + ','+ arraytemp[4] + ','+ arraytemp[7] + ','+ arraytemp[2] + ','+ arraytemp[5] + ','+ arraytemp[8];
						c_value += "]&name="+name;
						$.ajax({
							type: "POST",
							url: "<?php echo $this->baseUrl.'/campaign/Layout/insert' ?> ",
							data: "point=" + c_value,
							success: function(smg){	
								alert('Thành công');							
							}
						});	
						$(this).dialog("close");							
					}										
				}
			});
			return false;
		}	
			$.ajax({
				type: "POST",
				url: "<?php echo $this->baseUrl.'/campaign/campaign/loadlayout'?> ",
				data: "id=" + layoutID,
				dataType: "json",
				success: function(data){				
					$.each(data, function(key, val) {
						if(val==0){								
							$("#battle-"+battleID +" #"+key).removeClass("visible").addClass("invisible");
							$("#battle-"+battleID +" #"+key).find("select").attr('disabled',true);
							$("#battle-"+battleID +" #"+key).find("input").attr('disabled',true).val('');
						}else{
							$("#battle-"+battleID +" #"+key).removeClass("invisible").addClass("visible");
							$("#battle-"+battleID +" #"+key).find("select").attr('disabled',false);
							$("#battle-"+battleID +" #"+key).find("input").attr('disabled',false);							
						}
					 
					   // $("#battle-"+s+ "#tb_layout td"+key).val(val); 
					});											
				}
			});
		});
	//////Onchange cho campaignID///////
	 $(document).ready(function(){
		 	$('#campaignID').change(function(){
			 	var campaignID=$(this).val();
			 	var url = "<?php echo $this->baseUrl.'/campaign/campaign/edit/id/'?>"+campaignID;
			 	$(location).attr('href',url);			 

			 	});		 	
		 });
	///////Validate cho du lieu////		
		function validate(){
			flag=true;			
			$(".battle").each(function(key,val){
				num = key+1;
				flag1=true;
				//////test cac o khong bo trong
				for(var i=0;i<8;i++)
				{
					value=$(val).find('.visible_'+i).val();	
					//
					if(value=='')
					{	

						flag1=false;		
						break;	
					}
				}
				if(flag1==false)
				{
					$("#dialog #ct").append("<p class='error'>Battle" + num + ":	<br>không được bỏ trống các ô</p>");					
					flag=false;
				}
				else {
					
				
						flag2=true;
					////////test gia tri 
						for(i=0;i<8;i++)
						{
							value=$(val).find('.visible_'+i).val();							
							if(isNaN(value) && value=='undefined')
							{							alert(value + "_"+i);					
								flag2=false;
								break;
							}
						}
						if(flag2==false)
						{
							$("#dialog #ct").append("<p class='error'>Battle" + num + ":	<br>Phải là số</p>");	
							flag=false;
						}
						
				}
				
			});
			return flag;	
			}
</script>