<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>
<style>
.soldier{
	width: 40px;
}

table#battle input{
	max-width: 50px;
	overflow: hidden;
	margin-top: 2px;
	margin-bottom: 2px;
}
table#battle{
	border:solid 1px !important; 
}
table#battle .hidden{
	opacity:0.3;
}
table#battle td{
	margin: 0;
	overflow: hidden;
}
select{
	margin: 0;
	padding:0;
	max-width: 110px;
	min-width: 110px;
	height: 25px;
	overflow: hidden;
}
.style{
	margin: auto;text-align: center;padding-top: 2px;padding-bottom: 2px;
}
}
</style>
<form  class="myform" id="formPaging" name="formPaging" action="" method="post">
<div class='mybox'>
	<h3>Campaign Edit</h3>
	<table>
	<tr>
		<td>
			<label>Campaign Id :</label>
			<select name='campaignID' id='campaignID'>
				<option value='<?php echo $this->campaign->ID;?>'><?php echo $this->campaign->ID;?></option>
			</select>
		</td>			
		<td>
			<label>Campaign Name:</label>
			<input type="text" name='Name' id=Name' value='<?php echo $this->campaign->Name;?>' />
		</td>
		<td>
			<label>World Map:</label>
			<input type="text" readonly="readonly" value='<?php echo $this->campaign->Wor;?>' name='nextCampaign' id='nextCampaign'/>
		</td>
		</tr>
	</table>
	<h3>Battle</h3>	
	
	<table id='battle' width="100%" >
		<thead>
			<tr>
				<td width="15px;">ID</td>
				<td width="20px;">Order</td>
				<td>Layout</td>
				<td>Award</td>
			</tr>
		</thead>
	<?php foreach ($this->arrbattle as $rowbattle){?>

		<tr>
			<td><?php echo $rowbattle->ID;?></td>
			<td>
				<input type="text" name='Order' id='Order' value='<?php echo $rowbattle->Order;?>'/>
			</td>
			<td width="auto">
				<?php echo $this->selection($this->arrlayout,$rowbattle->Layout,"Layout",array('key'=>"ID",'name'=>"Name"))?>
				<br/>
				
				<table id='tb_layout'>
					<tr>
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][0])?"visile":"invisible"?>
						<td class="<?php echo  $strclass?>" style="margin: 0;padding: 0;">
							<xx></xx><?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],0);
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider_$rowbattle->ID"._0,
												array('key'=>"ID",'name'=>"Name",'default'=>"234234234"))?><br/>												
												
							<yy></yy><input type='text' class='soldier' id='levelSolider' name='levelSolider' value="<?php echo $arrBS['Level'];?>"/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][1])?"visile":"invisible"?>
						<td class="<?php echo  $strclass?>" >
							<xx></xx><?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],1); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider_$rowbattle->ID"._1,
												array('key'=>"ID",'name'=>"Name",'default'=>"234234234"))?><br/>
							<yy></yy><input type='text' class='soldier' id='levelSolider' name='levelSolider' value="<?php echo $arrBS['Level'];?>"/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][2])?"visile":"invisible"?>
						<td class="<?php echo  $strclass?>" >
							<xx></xx><?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],2); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider_$rowbattle->ID"._2,
												array('key'=>"ID",'name'=>"Name",'default'=>"234234234"))?><br/>
							<yy></yy><input type='text' class='soldier' id='levelSolider' name='levelSolider' value='<?php echo $arrBS['Level'];?>'/>
						</td>						
					</tr>
					<tr>
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][3])?"visile":"invisible"?>
						<td class="<?php echo  $strclass?>" >
							<xx></xx><?php  $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],3); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider_$rowbattle->ID"._3,
												array('key'=>"ID",'name'=>"Name",'default'=>"234234234"))?><br/>
							<yy></yy><input type='text' class='soldier' id='levelSolider' name='levelSolider' value='<?php echo $arrBS['Level'];?>'/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][4])?"visile":"invisible"?>
						<td class="<?php echo  $strclass?>" >
							<xx></xx><?php  $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],4); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider_$rowbattle->ID"._4,
												array('key'=>"ID",'name'=>"Name",'default'=>"234234234"))?><br/>
							<yy></yy><input type='text' class='soldier' id='levelSolider' name='levelSolider' value='<?php echo $arrBS['Level'];?>'/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][5])?"visile":"invisible"?>
						<td class="<?php echo  $strclass?>" >
							<xx></xx><?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],5);
							 echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider_$rowbattle->ID"._5,
												array('key'=>"ID",'name'=>"Name",'default'=>"234234234"))?><br/>
							<yy></yy><input type='text' class='soldier' id='levelSolider' name='levelSolider' value='<?php echo $arrBS['Level'];?>'/>
						</td>
					</tr>
					<tr>
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][6])?"visile":"invisible"?>
						<td class="<?php echo  $strclass?>" >
							<xx></xx><?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],6); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider_$rowbattle->ID"._6,
												array('key'=>"ID",'name'=>"Name",'default'=>"234234234"))?><br/>
							<yy></yy><input type='text' class='soldier' id='levelSolider' name='levelSolider' value='<?php echo $arrBS['Level'];?>'/>
						</td>
						
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][70])?"visile":"invisible"?>
						<td class="<?php echo  $strclass?>" >
							<xx></xx><?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],7); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider_$rowbattle->ID"._7,
												array('key'=>"ID",'name'=>"Name",'default'=>"234234234"))?><br/>
							<yy></yy><input type='text' class='soldier' id='levelSolider_2' name='levelSolider' value='<?php echo $arrBS['Level'];?>'/>
						</td>
						<?php $strclass = ($this->arrPoint[$rowbattle->ID][8])?"visile":"invisible"?>
						<td class="<?php echo  $strclass?>" >
							<xx></xx><?php $arrBS = $this->GetPoint($this->arrBattleSolider[$rowbattle->ID],8); 
							echo $this->selection($this->arrSoldier,$arrBS['Solider'],"solider_$rowbattle->ID"._8,
												array('key'=>"ID",'name'=>"Name",'default'=>"234234234"))?><br/>
							<yy></yy><input type='text' class='soldier' id='levelSolider_1' name='levelSolider' value='<?php echo $arrBS['Level'];?>'/>
						</td>
					</tr>
				</table>
			</td>
			<td width="200px">
			<div id='div-battle-award-<?php echo $rowbattle->ID;?>'>				
				<a href='javascript:saveAward(<?php echo $rowbattle->ID; ?>)' class='ico-16 save disabled'></a>&nbsp;&nbsp<a href='javascript:addAward(<?php echo $rowbattle->ID?>)' class='ico-16 add' ></a><br>
				<?php foreach ($this->arraward[$rowbattle->ID] as $key=>$row){?>
					<div class="award-<?php echo $rowbattle->ID?>" id="div-list-award-<?php echo $key ?>">
					<select id='<?php echo $row->ID?>' name='AwardTypeID[]' onChange='updateAward(<?php echo $row->ID?>,this)'>
						<?php if (empty($row->AwardTypeID)){?>
							<option $strSelect value="" style="color:red"></option>
						<?php } ?>	
						<?php echo $this->options($this->arrawardtype,$row->AwardTypeID,array('key'=>'AwardTypeID','name'=>'Name'))?>
						<option  value="insert" style="color:red"> Insert A Type</option>
					</select>					
					<input type='text' class='soldier' id='Value' name='Value[]' value='<?php echo $row->Value?>'/>
					
					<a class='tool-16 delete' href='javascript:removeAward(<?php echo $rowbattle->ID.",".$key?>)'>&nbsp</a>	
					</div>
				<?php }?>
			</div>
			</td>
		</tr>
		<?php }?>
	
	</table>
	<div class="style">
	<a class="btn add" href="">Add</a>
	<a class="btn save" href="">Save</a>
	</div>
</div>
</form>
<!-- Dung de them 1 award -->
<div style="display: none">
	<div id="optionAwardType">
		<option selected value="" style="color:red"></option>
		<?php echo $this->options($this->arrawardtype,0,array('key'=>'AwardTypeID','name'=>'Name'))?>		
	</div>
</div>
<!--  -->
<script>
	function addAward(key)
	{		
		var count = $(".award-"+ key).size();
		var options = $("#optionAwardType").html();
		var input = " <input type='text' class='soldier' id='Value' name='Value[]' value=''/>";
		var btnDelete = " <a class='tool-16 delete' href='javascript:removeAward("+key+","+count+")'>&nbsp</a>"	;
		var select = "<div class='award-"+key+"' id='div-list-award-"+count+"'><select name='AwardTypeID[]'>"+options+"</select>"+input+btnDelete+"</div>";
		$("#div-battle-award-"+key).append(select);
		
		
	}
	function removeAward(battleID,key)
	{
		$("#div-battle-award-"+battleID+ " #div-list-award-"+key).html("");
	}
	/////////////////////////
	function saveAward(key)
	{
		var data = $("#div-battle-award-"+key+" *").serialize();
		data += "&Action=update-all&BattleID="+key+"";
		$.ajax({
			type: "POST",
			url: "<?php echo $this->baseUrl.'/campaign/campaign/updateaward'?> ",
			data: data,
			success: function(msg){
				if(msg == '1'){					
					alert("Successfull");
				}else{
					alert("Error");					
				}
				window.location.reload();
			}
		});
	}
	///////////
	$(document).ready(function(){
			
			$("td.invisible").css("");
			
		
	});
	////////////////////////////
	function updateAward(id,element)
	{
		var selected = element.value;
		if(selected == "insert"){
			alert("Ch?c nang chua th?c hi?n");			
		}
	}
	///Load Layout///////
	function LoadLayout(key){
			alert(key);
	}
</script>