<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

</head>

<body>
<form action="" method="post" enctype="multipart/form-data" name="form1" id="form1">
<hr></hr>
<br></br>
 <div> 
  <label>Browse file : shop.[version].xfj :
  &nbsp&nbsp<input type="file" name="file1" id="file1" value="Browse file shop.[version].xfj"/>
   </label>
  </div>
  <br></br>
  <div>
   <label>Browse file : Type.def.php :    
    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<input type="file" name="file2" id="file2" value="Browse file Type.def.php"/>
   </label>
  </div>
  <br></br>
  <div> 
  &nbsp&nbsp&nbsp<label>Browse file : ShopHero.conf.php :
  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<input type="file" name="file3" id="file3" value="Browse file : ShopHero.conf.php"/>
   </label>
  </div>
  <br></br>
  <div> 
 &nbsp&nbsp&nbsp <label>Browse file : ShopSoldier.conf.php :
  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<input type="file" name="file4" id="file4" value="Browse file : ShopSoldier.conf.php"/>
   </label>
  </div>
  <br></br>
  
  <div> 
  &nbsp&nbsp&nbsp<label>Browse file : ShopBuilding.conf.php :
 &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <input type="file" name="fileBuilding" id="fileBuilding" value="Browse file : ShopBuilding.conf.php"/>
   </label>
  </div>
  <br></br>
  <div> 
  &nbsp&nbsp&nbsp<label>Browse file : ShopItem.conf.php :
  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<input type="file" name="fileItem" id="fileItem" value="Browse file : ShopItem.conf.php"/>
   </label>
  </div>
  <br></br>
  <div> 
  &nbsp&nbsp&nbsp<label>Browse file : ShopItemQuantity.conf.php :
  <input type="file" name="fileQuan" id="fileQuan" value="Browse file : ShopItemQuantity.conf.php"/>
   </label>
  </div>
  <br></br>
  
   <div>
   <center>
   <label>
    <input type="submit" name="btn" id="btn" value="Import file define" />
  </label>
 </center>
 </div>
 <br></br>
 <hr></hr>
</form>
<fieldset>
</fieldset>
</body>
</html>