<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;

?>
<style>
@import url("<?php echo $this->baseUrl.'/media/css/jsonview.css' ?>");
input.fill{
{
	width:98%;
}
</style>
<script type="text/javascript" src="<?php echo $this->baseUrl.'/media/scripts/jquery.contextMenu.js' ?>" ></script>

<script>	
var screen_w = 800;		
var screen_w = 600;	
var link_post_to	 =  "<?php echo $this->options->PostTo?>";
var link_get_from	 =  "<?php echo $this->options->GetFrom?>";


	$(function(){		
		var screen_h =  $(document).height();		
		$("div#container").animate({"width": "98%"}, "slow");	
		$("div#content").animate({"width": "98%"}, "slow");	
		$("div#tree").css({"height": screen_h - 400});	
		$("div#grid").css({"height": screen_h - 400});	
		JSONVIEWER.init();
		
		$("button#view_logs").click(function(){
			$("div#tabs-2").hide();	
			$("div#tabs-1").hide();	
			$("div#tabs-3").show();
			showLogs();	
		});
		////////////////		
		$("button#view_changed").click(function(){
			$("div#tabs-2").hide();				
			$("div#tabs-3").hide();
			$("div#tabs-1").show();
		});
		////////////////////////
		$("button#view_tree").click(function(){
			$("div#tabs-2").show();	
			$("div#tabs-1").hide();
			$("div#tabs-3").hide();		
		});
		/////////////////////////
		$("button#load").click(function(){			
			$("div#tabs-2").show();	
			$("div#tabs-1").hide();
			$("div#tabs-3").hide();				
			var root = $("#tree .ul-node-0 .li-node-0");
			root.children("ul").remove();
			$("div#tree-loading").html('<a class="tool-24 loading"></a>');			
			JSONVIEWER._count = 1;	
			$.ajax({
				type: "POST",
				url: link_get_from,
				dataType:"json",
				success:function(data){
					$("div#tree-loading").html('');					
					var s = JSONVIEWER.processNodes(data,1,"");			
					root.append(s);
					initEvent();
				},
				error:function(){
					alert("Link Error ! Please check Get Data Link in Options");
				}
			});	
		});
		/////////////////////////
		$("button#save_changed").click(function(){			
			var rows = $("table.values").find("tbody").find("tr");			
			rows.each(function(index){
				var node_id = $(this).attr("id");
				var path = $(this).find("td.name").attr("title");
				var type = $(this).find("td.type").text();
				var old_value = $(this).find("td.value input").attr("old_value");
				var new_value = $(this).find("td.value input").val();
				if(type !="array" && type != "object" && old_value!=new_value){
					updateToTable(path,old_value,new_value,node_id);
					// $.ajax({
						// type: "POST",
						// url: "<?php echo $this->baseUrl?>/compensation/compensation/savechanged/",
						// data:{
							// path:path,
							// old_value:old_value,
							// new_value:new_value
						// },
						// success:function(data){
							// if(data=="1"){ // save successfull
								
							// }
						// }
					// });		
				}
			});
		});
		///////////////////////////
		$("button#options").click(function(){
			$("div#options-loading").html('');	
			$("div#dialog_options").dialog({				
				height: 400,
				width: 800,
				modal: true,
				buttons: {
					"Save": function() {
						var data = $("form#options").serialize();
						var post_to = $("form#options input[name='PostTo']").val();
						var get_from = $("form#options input[name='GetFrom']").val();	
						$("div#options-loading").html('<a class="tool-24 loading"></a>');								
						$.ajax({							
							type: "POST",
							url: "<?php echo $this->baseUrl?>/compensation/compensation/options/",						
							data:{
								PostTo: post_to,
								GetFrom: get_from
							},
							success:function(data){									
								if(data !== "1"){
									messagebox(data);
								}else{									
									link_post_to = post_to;
									link_get_from = get_from;
									$("div#dialog_options").dialog("close");	
								}									
							}							
						});	
						
					},
					"Cancel": function() {
						$(this).dialog("close");
					}
				}
			});
		});
		//////////////////////		
		$("button#sync-values").click(function(){
			var table = $("table.tb_value_sync tbody");
			var rows = table.find("tr");
			var data = new Array();
			rows.each(function(index){
				var checked = $(this).find("td.checkbox input").is(":checked");
				if(checked){
					var path = $(this).find("td.path").text();				
					var new_value = $(this).find("td.new_value input").val();
					var old_value = $(this).find("td.old_value input").val();		
					var obj = {
						"path":path,
						"new_value":new_value,
						"old_value":old_value
					}
					data.push(obj);
					$(this).find("td.checkbox input").attr("checked",false);
				}
			});			
			postTo(data);						
		});
		//////////////////////
		$("button#delete-log").click(function(){			
			var table_logs = $("table.tb_logs tbody");
			var rows = table_logs.find("tr");
			var arr_delete = new Array();
			rows.each(function(){
				var checked = $(this).find("td.checkbox input").is(":checked");
				if(checked){
					var id = $(this).attr("id");
					arr_delete.push(id);
				}
			});
			$.ajax({
					type: "POST",
					url: "<?php echo $this->baseUrl?>/compensation/compensation/deletelogs/",			
					data:{
						ARRAY_ID:arr_delete,
					},				
					success:function(msg){
						if(msg==1){
							$.each(arr_delete,function(key,value){
								table_logs.find("tr#"+value).remove();
							});
						}else{
							messagebox(msg);
						}
						
					},
					error :function(){
						alert("Post failure ! Please check Post Link in Options");
					}
				});	
		});
		/////////////////////		
		function postTo(data){			
			if(link_post_to != ""){
				$.ajax({
					type: "POST",
					url: link_post_to,			
					data:{
						Modify: data
					},				
					success:function(msg){	
						saveLogs(data);
						messagebox(msg);
					},
					error :function(){
						alert("Post failure ! Please check Post Link in Options");
					}
				});	
			}else{
				alert("Link Error ! Please check Post Link in Options");
			}
			
		}
		/////////////////////		
		function saveLogs(data){
			$.ajax({
				type: "POST",
				url: "<?php echo $this->baseUrl?>/compensation/compensation/logs/",			
				data:{
					Modify: data,
				},				
				success:function(data){						
				}
			});	
		}
		/////////////////////		
		function showLogs(){			
			$("div#logs-loading").html('<a class="tool-24 loading"></a>');
			var table_logs = $("table.tb_logs tbody");
			$.ajax({
				type: "POST",
				url: "<?php echo $this->baseUrl?>/compensation/compensation/getlogs/",			
				dataType: "json",					
				success:function(data){
					//messagebox(data);
					table_logs.html("");
					$.each(data,function(key,item){						
						table_logs.append('<tr id="'+item.ID+'">'+
						'<td class="checkbox" style="text-align:center"><input type="checkbox"/></td>'+
						'<td class="path">'+item.Path+'</td>'+
						'<td class="old_value">'+item.OldValue+'</td>'+
						'<td class="old_value">'+item.NewValue+'</td>'+
						'<td class="old_value">'+item.User+'</td>'+
						'<td class="old_value">'+item.Date+'</td>'+
						'</tr>');
					});
					$("div#logs-loading").html('');
				}
			});	
		}
		///////////////////
		function updateToTable(path,old_value,new_value,node_id){
			var table_value = $("table.tb_value_sync tbody");
			
			var exist_tr = table_value.find("tr#"+node_id);
			var new_tr = $('<tr id="'+node_id+'">'+
					'<td class="checkbox" style="text-align:center"><input checked type="checkbox"/></td>'+
					'<td class="path">'+path+'</td>'+
					'<td class="old_value"><input style="width: 98%;"  disabled value="'+old_value+'" /></td>'+
					'<td class="new_value"><input style="width: 98%;"  value="'+new_value+'" /></td>'+
					'<td style="text-align:center"><a title="Delete!!" href="#" class="tool-24 delete"></a>'+
					'&nbsp;&nbsp;<a title="Sync Now" href="#" class="tool-24 save"></a></td>'+
					'</tr>');
			if(exist_tr.html()!=null){//exist tr width node_id
				exist_tr.html(new_tr.html());
			}else{					// don't exist tr width node_id
				table_value.append(new_tr);
			}
		}
		/////////////////////
		function messagebox(mess){
			$("div#dialog_messagebox").html(mess);
			$("div#dialog_messagebox").dialog({				
				height: 500,
				width: 800,
				modal: true,
				buttons: {					
					"Close": function() {
						$(this).dialog("close");
					}
				}
			});
		}
	});
	(function($){
		JSONVIEWER ={
			init: function() {				
				this._table = $("div#grid table.values tbody");
				this._count = 1;
				
				$("div#tree").delegate(".x-icon.plus","click",function(e){
					
					$(this).removeClass("plus").addClass("minus");
					$(this).parent().find("ul").show();
					$(this).parent().find("div").show();			
					e.preventDefault();
					return false;
				});
				$("div#tree").delegate(".x-icon.minus","click",function(e){
				
					$(this).removeClass("minus").addClass("plus");
					$(this).parent().children("div").hide();
					$(this).parent().children("ul").hide();									
					e.preventDefault();
					return false;
				});
				$("div#tree").delegate(".x-div","click",function(e){
					JSONVIEWER._table.html("");
					var name = $(this).find("span.name").text();
					var type = $(this).find("span.name").attr("title");
					var value = $(this).find("span.value").text();	
					var path = $(this).attr("path");
					var node_id = $(this).attr("id");
					//var cur_path= $(this).attr("path");
					$("div#grid input#cur_path").val(path);
					JSONVIEWER.addToGridView(name,type,value,path,node_id);					
					// e.preventDefault();
					$(".selected").removeClass("selected");
					$(this).addClass("selected");
					//var $tabs = $("#tabs" ).tabs();
					//$tabs.tabs('select', 0); 
					return false;
				});	
				$("div#tree").delegate(".x-icon.object,.x-icon.array","click",function(e){
					JSONVIEWER._table.html("");
					var arr_div = $(this).parent().children("*");
					var cur_path= $(this).attr("path");
					$("div#grid input#cur_path").val(cur_path);
					arr_div.each(function(index){
						if($(this).hasClass("x-div")){ // value
							var name = $(this).find("span.name").text();
							var type = $(this).find("span.name").attr("title");
							var value = $(this).find("span.value").text();
							var path = $(this).attr("path");
							var node_id = $(this).attr("id");
							JSONVIEWER.addToGridView(name,type,value,path,node_id);	
						}else if($(this).hasClass("ul-node")){// object or array
							var name_object = $(this).find(".x-icon.object").eq(0).text();							
							if(name_object==""){
								var name_object = $(this).find(".x-icon.array").eq(0).text();
								var path_object = $(this).find(".x-icon.array").eq(0).text();
								var node_id = $(this).find(".x-icon.array").eq(0).attr("id");
								JSONVIEWER.addToGridView(name_object,"array","...",path_object,node_id);
							}else{
								var path_object = $(this).find(".x-icon.object").eq(0).attr("path");
								var node_id = $(this).find(".x-icon.object").eq(0).attr("id");						
								JSONVIEWER.addToGridView(name_object,"object","...",path_object,node_id);
							}							
						}
						
					});
					$(".selected").removeClass("selected");
					$(this).addClass("selected");
					return false;
				});
				$("div#grid").delegate("td.value input.disabled","dblclick",function(e){
					var id_node = $(this).val();
					$("div#tree #"+id_node).click();
				});
			},
			processNodes: function(node,level,path) {
				if(node==null){
					return '<span class="x-text value">null</span>';
				};
				var return_str = '';
				var type = jQuery.type(node);								
				switch(jQuery.type(node))
				{	
					case 'boolean':												
					case 'number':
						return_str += '<span class="x-text value">'+node+'</span>';
						break;
					case 'string':						
						return_str += '<span class="x-text value">"'+node+'"</span>';
						break;
					case 'object':						
						// $.each(node, function(item,value){								
							// return_str += JSONVIEWER.processNodes(this,);								
						// });
						// break;
					case 'array':
						/*object*/						
						var type_value = "";
						var curent_path = "";
						level++;
						if(node != null){							
							$.each(node, function(item,value){
								JSONVIEWER._count = JSONVIEWER._count + 1;	
								type_value = jQuery.type(value);
								curent_path = path + "/"+item;								
								if(type_value =="object" || type_value=="array"){
									
									return_str += '<ul class="ul-node"><li>';
									for(var i = 0; i<level-1;i++){
										return_str +='<span class="x-icon line"></span>';
									}
									
									return_str += '<span class="x-icon minus"></span>';
									return_str += '<span id ="obj-node-'+JSONVIEWER._count+'" path='+curent_path+' class="x-icon '+type_value+'">'+item+'</span>';
									
								}else{
									return_str += '<div class="x-div" id="obj-node-'+JSONVIEWER._count+'" path='+curent_path+'>';
									for(var i = 0; i<level-1;i++){
										return_str +='<span class="x-icon line"></span>';
									}
									return_str += '<span class="x-icon ebow"></span>';
									return_str += '<span title="'+type_value+'" class="x-icon name '+type_value+'">'+item+'</span> : ';
								}
															
								return_str += JSONVIEWER.processNodes(value,level,path+"/"+ item);
									
								if(type_value =="object" || type_value=="array"){
									return_str += '</li></ul>';									
								}else{
									return_str +="</div>";
								}
							});
							
						};
						break;										
				}
				/*Clean up any undefined elements*/
				return_str = return_str.replace('undefined', '');
				return return_str;
			},
			addToGridView: function(name,type,value,path,node_id){				
				if(type=="object"){
					this._table.append('<tr><td class="name" title='+path+'>'+name+'</td><td>'+type+'</td><td class="value"><input title="double Click" old_value='+value+' class="disabled" readonly value='+node_id+' /></td></tr>');
				}else{
					this._table.append('<tr id="'+node_id+'"><td class="name" title='+path+'>'+name+'</td><td>'+type+'</td><td class="value" ><input  old_value='+value+' value='+value+' /></td></tr>');				
				}
				
			}
		}
	})(jQuery);
	function initEvent(){
		 $(".x-icon.object").contextMenu({ menu: 'myMenu', leftButton: true }, 
        function(action, el, pos) { contextMenuWork(action, el, pos); });
	}
	
    function contextMenuWork(action, el, pos) {	
        switch (action) {
            case "expand":
                {
                    //Popup Delete Confirmation - included in demo and in download
					var objects = el.parent().children("ul");
					$.each(objects,function(key,item){
						//alert($(this).html());
						$(this).children("li").children(".x-icon.plus").click();
					});
                    break;
                }
            case "collapse":
                {
                    //Popup Insert Dialog- included in demo and in download
					var objects = el.parent().children("ul");
					$.each(objects,function(key,item){
						//alert($(this).html());
						$(this).children("li").children(".x-icon.minus").click();
					});
                    break;
                }
			case "cancle":
                {                 
                    break;
                }
        }
   }
</script>
<div id="x-toolbar" >
		<div style="float:left">
		<button id="load" class="button">Load data</button>
		<button id="options" class="button">Options</button>
		
		</div>
		<div style="float:right;margin-right:130px">
		<button id="view_logs" class="button">View Logs</button>
		<button id="view_tree" class="button">View Tree</button>	
		<button id="view_changed" class="button">View changed</button>		
		</div>
</div>
<div id="tabs-1" style="padding:0px;display:none">
			<table class="tb_value_sync" style="margin: auto;width:100%;">
				<thead>
				<tr>
					<td style="width:40px"></td>
					<td>path</td>
					<td>Old value</td>
					<td>New value</td>
					<td style="width:75px;text-align:center">Action</td>
				</tr>
				</thead>
				<tbody>
				<!-- Load Ajax Here-->
				</tbody>
			</table>
			<div style="text-align:center">
					<button style=" padding: 10px;" id="sync-values">Sync</button>
					<button style=" padding: 10px;" id="delete-values">Delete</button>
			</div>
</div><!-- End#Tabs-1-->

	
<div id="tabs-2" >
	<div id="tree" class="x-panel">
		<ul class="ul-node-0" class="ul-node">
			<li class="li-node-0">
				<span class="x-icon minus"></span>
				<span class="x-icon object">JSon</span>						
			</li> 
		</ul>
		<div id="tree-loading">
		</div>
	</div><!-- end #tree-->
	<div id="slpit"><div class="ct"></div></div>
	<div id="grid" class="x-panel">
			<div style="padding:0px">				
				<div>
					<button style=" padding: 6px;" id="save_changed">Save</button>
					<input type="text" style="width:80%" id="cur_path" value=""/>
				</div>
				<table class = "values" style="margin: 0px;width: 100%;">
					<thead>
						<tr>
							<td>name</td>
							<td>type</td>
							<td>value</td>
						</tr>
					</thead>
					<tbody>			
					</tbody>
				</table>
			</div>		
		</div><!-- end #grid-->

</div>


<div id="tabs-3" style="padding:0px;display:none">
			<table class="tb_logs" style="margin: auto;width: 100%;">
				<thead>
				<tr>
					<td style="width:40px"></td>
					<td>path</td>
					<td>Old value</td>
					<td>New value</td>
					<td>UserName</td>
					<td>Date</td>					
				</tr>
				</thead>
				<tbody>
				<!-- Load Ajax Here-->
				</tbody>
			</table>
			<div style="text-align:center;margin:10px" id="logs-loading"></div>
			<div style="text-align:center">
				
					<button style=" padding: 10px;" id="delete-log">Delete</button>
			</div>
</div><!-- End#Tabs-3-->
	
<div id="dialog_options" style="display:none">
	<form id="options">
	<label>GetFrom</label><input name="GetFrom" style="width: 98%;" value="<?php echo $this->options->GetFrom?>">
	<label>PostTo</label><input name="PostTo" style="width: 98%;" value="<?php echo $this->options->PostTo?>">
	</form>
	<div style="text-align:center" id="options-loading"></div>
</div>

<div id="dialog_messagebox">
	
</div>
<ul id="myMenu" class="contextMenu">          
    <li class="expand"><a href="#expand">Expand All</a></li>                    
    <li class="collapse"><a href="#collapse">Collapse All</a></li>            
	<li class="cancle"><a href="#cancle">Cancle</a></li>           
</ul>