<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php 
endif;
?>
<style>
	table tr{
		border:1px #CCC solid; 
}

</style>
<form  class="myform" id="formPaging" name="formPaging" action="" method="post">

<div class="mybox">
	<h3>Quest</h3>
	<table class="filter">
		<tr>			
			<td><label>Search</label><input type="text" name='ID' id='ID'/>
			<input type="submit" value='Search' name='search'/></td>
			<td><a class="btn add" href="<?php echo $this->baseUrl;?>/shop/ibshop/new">Add</a></td> 
		</tr>
	</table>
	<table class="filter">
	<thead>	
		<tr style="border: 1px;">			
			<td>Tab</td>
			<td>Order</td>
			<td>Items</td>
			<td>Tool</td>			
		</tr>
	</thead>
	<tbody>
		<?php $this->listIbShop($this->data, $this->page, $this->items, $this) ?>	
	</tbody>
	</table>
	
<?php echo $this->pagingControl($this->items, $this->page, $this->totalRecord, $this)?>
	<br>
		<center><input type="submit" name="button1" id = "button1" style="width:100px"  value="Save"/></center>
</div>
</form>
<script>
	function deleteIbShop(key)
	{
		if(confirm('Bạn có muốn xóa Item Shop này không'))
		{
			$.ajax({
				type: "POST",
				url:"<?php echo $this->baseUrl.'/shop/ibshop/delete/'?> ",
				data: "id="+key,			
				success: function(data){					
					alert('Xóa thành công');
					window.location.reload();			
				}
			});
		}
	}
</script>