<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Ủn Ỉn Support</title>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl ?>/media/css/theme.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl ?>/media/css/style.css" />
<script type="text/javascript" src="<?php echo $this->baseUrl ?>/media/scripts/jquery-1.4.4.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl ?>/media/scripts/form.js"></script>
<!--[if IE]>
<link rel="stylesheet" type="text/css" href="css/ie-sucks.css" />
<![endif]-->
</head>

	<body style="background: none">		
        <div id="wrapper">            
			<?php echo $this->layout()->content ?>  
      </div>
</body>
</html>
