<?php if($this->errMsg) :?>
    <?php $this->showError($this->errMsg)?>
<?php endif; ?>
<div id="box">    
    <h3 id="reward">Tặng thưởng</h3>
    <form id="form" action="" method="post" enctype="multipart/form-data">     
    <label for="street">File : </label> 
    <input type="file" name="file" id="file"/>    
    &nbsp;<input id="button1" type="submit" value="OK" />     
    <br />
    </form>
</div>