<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>

<?php ?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<link rel="stylesheet" href="<?php echo $this->baseUrl."/media/css/"?>chartcss/bootstrap.min.css" />
 <link rel="stylesheet" href="<?php echo $this->baseUrl."/media/css/"?>chartcss/jquery.jOrgChart.css" />
 <link rel="stylesheet" href="<?php echo $this->baseUrl."/media/css/"?>chartcss/custom.css" />
 <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl."/media/css/"?>chartcss/prettify.css" />

<script src="<?php echo $this->baseUrl."/media/scripts/"?>chart/prettify.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl."/media/scripts/"?>jquery-1.7.1.min.js"></script>
<script src="<?php echo $this->baseUrl."/media/scripts/"?>chart/jquery.jOrgChart.js"></script>
<script>
    jQuery(document).ready(function() {
        $("#org").jOrgChart({
			chartElement : '#chart'
		});
		
		/* Extra Code */
		$("#show-list").click(function(e){
			e.preventDefault();	
		});
    });
</script>
</head>
 <body onload="prettyPrint()" style="background : url('<?php echo $this->baseUrl."/media/images"?>/bkgd.png') repeat top left;">
	<div class="topbar">
		
	</div>
	
	<ul id="org" style="display:none">
	    <li>Root
	    	<?php foreach($this->arrQuest as $key=>$val){ ?>
	    		<ul>
	    			<li><?php echo $val->QuestName;?>
	    			</li>
	    		</ul>
	    	<?php }?>
	    </li>
   </ul>			
	
	<div id="chart" class="orgChart"></div>

</body></html>