<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl ?>/media/scripts/datetimepicker/jquery-ui.css" />
<script type="text/javascript" src="<?php echo $this->baseUrl ?>/media/scripts/datetimepicker/jquery-ui.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl ?>/media/scripts/datetimepicker/jquery.ui.datetimepicker.js"></script>
<?php if($this->errMsg) :?>
	<?php $this->showError($this->errMsg)?>
<?php endif; ?>
<?php if($this->msg) :?>		
	<?php $this->showMessage($this->msg)?>	
<?php endif;?>
<form id="form" name="formPaging" action="" method="post">
<div id="box">
	<h3>Lịch sử thao tác</h3>
	<br/>
	<table class="filter">
		<tr>
			<th>Tài khoản</th>
			<td><input type="text" name="txtUsername" value="<?php echo $this->formIndex->txtUsername ?>"/></td>
			<th>Ngày</th>
			<td>
				<input id="txtDate" name="txtDate" value="<?php echo $this->formIndex->txtDate ?>"/> (mm/dd/yyyy)
			</td>
			<td>
				<input id="button1" type="submit" value="Tìm" name="btnSearch" />
			</td>
		</tr>
	</table>
	
	<table width="100%">
		<thead>
			<tr>							
				<th width="150px">Thời gian</th>
				<th width="150px">Người dùng</th>
				<th>Thao tác</th>
				<th>Ghi chú</th>
			</tr>
		</thead>
		<?php $this->listLog($this->data, $this->page, $this->items, $this) ?>		
	</table>	
	<?php echo $this->pagingControl($this->items, $this->page, $this->totalRecord, $this) ?>		
</div>
</form>
<script type="text/javascript">
	$(function(){		
		$("#txtDate").datetimepicker({
				dateFormat: 'mm/dd/yyyy',
				changeYear: true,
				changeMonth:true,
				showButtonPanel:true
			}
		);		
	});

</script>
