<div id="footer">
	<div id="credits">
		<img style="vertical-align: middle" width="16" height="16" src="<?php echo $this->baseUrl ?>/media/images/logo.gif"/>&nbsp;<b>P2 TEAM</b>
	</div>
	<div id="styleswitcher">
		<ul>
			<li><a href="javascript: document.cookie='theme='; window.location.reload();" title="Default" id="mixswitch">d</a></li>
			<li><a href="javascript: document.cookie='theme=1'; window.location.reload();" title="Blue" id="blueswitch">b</a></li>
			<li><a href="javascript: document.cookie='theme=2'; window.location.reload();" title="Green" id="greenswitch">g</a></li>
			<li><a href="javascript: document.cookie='theme=3'; window.location.reload();" title="Brown" id="brownswitch">b</a></li>
			<li><a href="javascript: document.cookie='theme=4'; window.location.reload();" title="Mix" id="defswitch">m</a></li>                
		</ul>
	</div><br />
</div>